"""ARMA with Laplace innovations by conditional (CSS-style) maximum
likelihood — LAD/median ARMA, robust to heavy-tailed innovations.

Model
-----
ARMA(p, q) in mean-deviation form, innovations iid Laplace(0, b):

    z_t = y_t - m
    z_t = sum_i phi_i z_{t-i} + e_t + sum_j theta_j e_{t-j}
    p(e) = (2 b)^{-1} exp(-|e|/b).

Conditional (CSS) likelihood: residuals are generated by the exact
inverse filter e_t = theta(L)^{-1} phi(L) z_t with zero pre-sample
values (z_s = e_s = 0 for s <= 0) — implemented with
``scipy.signal.lfilter``, which runs precisely this recursion.  The
first max(p, q) residuals are dropped from the criterion to soften the
zero-initialisation, giving

    loglik = sum_{t > max(p,q)} [ -log(2 b) - |e_t| / b ].

Profiling the scale: b_hat = mean|e_t| in closed form, so

    profile loglik = -n [ log(2 b_hat) + 1 ],

and maximising it is IDENTICAL to minimising mean |e_t| — least absolute
deviations (LAD) ARMA.  Equivalently this is quantile regression at
tau = 1/2 with ARMA dynamics: the fit targets the conditional MEDIAN.
Under the symmetric (asymmetry-free) Laplace density median = mean, so
(phi, theta) are comparable with Gaussian ARMA estimates; under skewed
innovations only the intercept m differs (it absorbs the median of the
innovation distribution).  LAD-ARMA is consistent and asymptotically
normal under weak conditions and far more efficient than Gaussian
CSS/OLS when innovations are heavy-tailed (Davis & Dunsmuir 1997; Ling
2005); under exactly-Laplace innovations it IS the MLE, with an
asymptotic efficiency gain of a factor 2 in variance over Gaussian
CSS for location-type parameters.

Estimation detail
-----------------
* Stationarity/invertibility enforced through the tanh-partial-
  autocorrelation reparameterisation (Monahan 1984; Jones 1980): the
  optimiser works on unconstrained r, pacf = tanh(r), Durbin-Levinson
  maps pacf -> AR coefficients; the MA polynomial uses the same map with
  a sign flip (theta = -DL(tanh(r_ma))), which parameterises exactly the
  invertible region.
* |e| is kinked at 0; for L-BFGS-B stability the criterion uses the
  smooth approximation sqrt(e^2 + delta^2) with delta = 1e-6 sd(y)
  (negligible bias; the REPORTED loglik/scale use the exact |e| at the
  optimum).  This is a pragmatic smoothing, not the linear-programming
  route used in the exact-LAD literature — honest simplification.
* ``innovations='gaussian'`` runs the identical pipeline with
  e^2/Gaussian likelihood (profile: minimise mean e^2), i.e. classical
  CSS — the apples-to-apples benchmark used in tests.py for the
  parameter-recovery comparison under t(2.5) innovations.
* Exact (full, unconditional) Laplace ARMA likelihood is not available
  in closed form; CSS conditioning is the standard practical route and
  is what "exact CSS-style MLE (conditional likelihood)" means here.

References
----------
- Davis & Dunsmuir (1997), "Least absolute deviation estimation for
  ARMA processes", Econometric Theory 13(3).
- Ling (2005), "Self-weighted LAD estimation for infinite variance
  autoregressive models", JRSS-B 67(3) (LAD under very heavy tails).
- Koenker & Bassett (1978), Econometrica (LAD = median regression).
- Monahan (1984), Biometrika 71(2) (stationarity reparameterisation);
  Jones (1980), Technometrics 22(3).
- Box & Jenkins (1976) for CSS conditioning.

Provenance: implemented from the published literature above; no
proprietary code consulted.  Research code, not part of the public
tsecon API.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
from scipy.optimize import minimize
from scipy.signal import lfilter


def _pacf_to_ar(r: np.ndarray) -> np.ndarray:
    """Durbin-Levinson map: unconstrained r -> stationary AR coefficients.

    pacf_k = tanh(r_k); recursion a^{(k)} = [a^{(k-1)} - pacf_k *
    reverse(a^{(k-1)}), pacf_k].  Bijection onto the stationary region
    (Monahan 1984).
    """
    a = np.zeros(0)
    for rk in np.tanh(np.asarray(r, float)):
        a = np.r_[a - rk * a[::-1], rk]
    return a


def arma_css_resid(y: np.ndarray, m: float, phi: np.ndarray,
                   theta: np.ndarray) -> np.ndarray:
    """Exact CSS residual recursion e = theta(L)^{-1} phi(L) (y - m).

    lfilter(b=[1,-phi], a=[1,theta], x) computes
    e_t = x_t - sum phi_i x_{t-i} - sum theta_j e_{t-j} with zero initial
    conditions — the Box-Jenkins conditional-sum-of-squares recursion.
    """
    z = np.asarray(y, float) - m
    b = np.r_[1.0, -np.asarray(phi, float)]
    a = np.r_[1.0, np.asarray(theta, float)]
    return lfilter(b, a, z)


@dataclass
class ALARMAResult:
    innovations: str
    p: int
    q: int
    mean: float
    phi: np.ndarray
    theta: np.ndarray
    scale: float          # Laplace b = mean|e| ; Gaussian sigma = rms(e)
    loglik: float
    aic: float
    bic: float
    resid: np.ndarray = field(repr=False)
    converged: bool
    n_used: int


def fit_arma_css(
    y: np.ndarray,
    p: int = 1,
    q: int = 1,
    innovations: str = "laplace",
    maxiter: int = 500,
) -> ALARMAResult:
    """CSS-MLE of ARMA(p, q) with Laplace (LAD/median) or Gaussian errors."""
    y = np.asarray(y, float)
    T = y.shape[0]
    m0 = max(p, q)
    if T < 10 * max(1, m0) + 20:
        raise ValueError("series too short for requested order")
    if innovations not in ("laplace", "gaussian"):
        raise ValueError("innovations must be 'laplace' or 'gaussian'")
    delta = 1e-6 * (np.std(y) + 1e-12)

    def unpack(psi):
        m = psi[0]
        phi = _pacf_to_ar(psi[1:1 + p]) if p else np.zeros(0)
        theta = -_pacf_to_ar(psi[1 + p:1 + p + q]) if q else np.zeros(0)
        return m, phi, theta

    if innovations == "laplace":
        def neg(psi):
            m, phi, theta = unpack(psi)
            e = arma_css_resid(y, m, phi, theta)[m0:]
            return np.log(np.mean(np.sqrt(e * e + delta * delta)))
        start_m = float(np.median(y))
    else:
        def neg(psi):
            m, phi, theta = unpack(psi)
            e = arma_css_resid(y, m, phi, theta)[m0:]
            return 0.5 * np.log(np.mean(e * e))
        start_m = float(np.mean(y))

    # multi-start: zero dynamics and a mildly persistent start
    starts = [np.r_[start_m, np.zeros(p + q)],
              np.r_[start_m, 0.4 * np.ones(p), -0.2 * np.ones(q)]]
    best = None
    for psi0 in starts:
        res = minimize(neg, psi0, method="L-BFGS-B",
                       options={"maxiter": maxiter})
        if best is None or res.fun < best.fun:
            best = res

    m, phi, theta = unpack(best.x)
    e = arma_css_resid(y, m, phi, theta)
    eu = e[m0:]
    n = eu.shape[0]
    if innovations == "laplace":
        b = float(np.mean(np.abs(eu)))
        loglik = -n * (np.log(2.0 * b) + 1.0)
        scale = b
    else:
        s2 = float(np.mean(eu * eu))
        loglik = -0.5 * n * (np.log(2.0 * np.pi * s2) + 1.0)
        scale = float(np.sqrt(s2))
    npar = 1 + p + q + 1  # mean + AR + MA + scale
    return ALARMAResult(
        innovations=innovations, p=p, q=q, mean=float(m),
        phi=np.asarray(phi), theta=np.asarray(theta), scale=scale,
        loglik=float(loglik), aic=2.0 * npar - 2.0 * loglik,
        bic=np.log(n) * npar - 2.0 * loglik, resid=e,
        converged=bool(best.success), n_used=n,
    )


def simulate_arma(T, phi, theta, m=0.0, innov="laplace", df=2.5, seed=0,
                  burn=200):
    """Simulate ARMA(p,q) with laplace / student-t(df) / gaussian innovations
    (unit-ish scale, not variance-standardised — documented in tests)."""
    rng = np.random.default_rng(seed)
    n = T + burn
    if innov == "laplace":
        e = rng.laplace(0.0, 1.0, n)
    elif innov == "t":
        e = rng.standard_t(df, n)
    elif innov == "gaussian":
        e = rng.standard_normal(n)
    else:
        raise ValueError(innov)
    phi = np.atleast_1d(np.asarray(phi, float))
    theta = np.atleast_1d(np.asarray(theta, float))
    # z = phi(L)^{-1} theta(L) e  via lfilter(b=[1,theta], a=[1,-phi])
    z = lfilter(np.r_[1.0, theta], np.r_[1.0, -phi], e)
    return m + z[burn:]


def _demo(reps=30, T=400, seed=123):
    """Small parameter-recovery comparison under t(2.5) innovations."""
    phi0, th0 = 0.6, 0.3
    est = {"laplace": [], "gaussian": []}
    for r in range(reps):
        y = simulate_arma(T, phi0, th0, innov="t", df=2.5, seed=seed + r)
        for k in est:
            f = fit_arma_css(y, 1, 1, innovations=k)
            est[k].append([f.phi[0], f.theta[0]])
    for k, v in est.items():
        v = np.array(v)
        rmse = np.sqrt(np.mean((v - [phi0, th0]) ** 2, axis=0))
        print(f"{k:8s} rmse(phi)={rmse[0]:.4f} rmse(theta)={rmse[1]:.4f}")


if __name__ == "__main__":
    _demo()
