//! # tsecon-predreg — predictive regressions with a persistent regressor
//!
//! Inference for the one-step predictive regression
//!
//! ```text
//! r_{t+1} = alpha + beta * x_t + u_{t+1},      x_t = rho * x_{t-1} + e_t
//! ```
//!
//! in the *Stambaugh setting*: the predictor `x` is persistent (near unit
//! root) and its AR(1) innovation `e` is correlated with the regression error
//! `u`. That combination breaks ordinary OLS inference — the slope is biased
//! in finite samples and the naive t-test badly over-rejects as `rho -> 1`.
//! This crate provides three answers, each drawing its least squares from
//! [`tsecon_hac`] (the library's single OLS owner) and its chi-square tail
//! from [`tsecon_stats`]:
//!
//! ## Module map
//!
//! - [`ols_predictive`] / [`OlsPredReg`]: the plain OLS predictive
//!   regression — `beta_ols`, its nonrobust standard error, and t-statistic.
//! - [`stambaugh`] / [`StambaughCorrection`]: the Stambaugh (1999) closed-form
//!   bias correction using the least-squares AR(1) root and the Kendall bias
//!   `E[rho_hat - rho] ~ -(1 + 3 rho) / n`. Exposes `beta_ols`, the bias
//!   term, and `beta_corrected` with its standard error.
//! - [`ivx`] / [`IvxResult`] and [`ivx_multi`] / [`IvxMultiResult`]: the IVX
//!   estimator and its Wald predictability test (Kostakis, Magdalinos &
//!   Stamatogiannis 2015), scalar and multivariate. The Wald statistic for
//!   `H0: beta = 0` is asymptotically chi-square UNIFORMLY over the
//!   persistence of `x` — the property that motivates IVX — configured via
//!   [`IvxConfig`] (defaults `cz = -1`, `alpha = 0.95`).
//!
//! ## Validation
//!
//! The published formulas are pinned to a NumPy documented-formula golden
//! (`fixtures/predreg.json`, generated by
//! `fixtures/generate_predreg_fixtures.py`) to ~1e-10, and — more importantly
//! — the statistical claims are established by seeded Monte-Carlo property
//! tests: the IVX-Wald test holds its nominal size across
//! `rho in {0.9, 0.95, 0.99, 1.0}` including the exact unit root (where the
//! naive OLS t-test over-rejects two-to-five-fold), has power against a true
//! predictive slope, and the Stambaugh correction measurably reduces the
//! finite-sample bias of `beta_ols`.
//!
//! ```
//! use tsecon_predreg::{ivx, stambaugh, IvxConfig};
//!
//! // Persistent predictor, one-step-ahead return.
//! let x: Vec<f64> = (0..300).map(|t| (t as f64) * 0.01).collect();
//! let r: Vec<f64> = x.iter().map(|xt| 0.02 * xt + 0.1).collect();
//!
//! let s = stambaugh(&r, &x).unwrap();
//! assert!(s.beta_corrected.is_finite());
//!
//! let fit = ivx(&r, &x, IvxConfig::default()).unwrap();
//! assert!(fit.wald >= 0.0 && (0.0..=1.0).contains(&fit.pvalue));
//! ```

#![warn(missing_docs)]
#![warn(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod align;
mod error;
mod ivx;
mod ols;
mod stambaugh;

pub use error::PredRegError;
pub use ivx::{ivx, ivx_multi, IvxConfig, IvxMultiResult, IvxResult};
pub use ols::{ols_predictive, OlsPredReg};
pub use stambaugh::{stambaugh, StambaughCorrection};
