//! # tsecon-copula — static bivariate copulas
//!
//! The E12 dependence slice (ROADMAP §0 build-next, "Static copulas"):
//! Gaussian, Student-t, Clayton, Gumbel, and Frank copulas fitted to
//! probability-scale *pseudo-observations*, with Kendall-tau inversion
//! or full MLE, AIC/BIC family selection, and closed-form tail
//! dependence. **Bivariate throughout in this slice** — `d > 2` for the
//! elliptical families (a correlation-matrix parameterization) is a
//! natural extension deferred honestly, as are rotated/survival
//! Archimedean copulas (so Clayton/Gumbel here model *positive*
//! dependence only) and any dynamic/time-varying copula.
//!
//! ## Workflow
//!
//! A copula separates dependence from the margins: fit the margins any
//! way you like, transform each to the probability scale, then model
//! only the joint ranks. The one-line route:
//!
//! * [`pseudo_obs`] — the average-rank transform `u = rank/(n+1)`
//!   (scipy `rankdata(method="average")` semantics, golden-pinned; the
//!   `n+1` denominator keeps every value strictly inside `(0, 1)`).
//!   Ranks see only order, so the fit is invariant to strictly monotone
//!   transforms of each margin — the whole point of the copula
//!   decomposition, asserted by a property test (`x` vs `exp(x)`:
//!   bit-identical fits).
//! * [`copula_fit`] — one family, `Mle` (default surface) or `Tau`
//!   inversion; returns parameters, observed-information SEs, loglik,
//!   AIC/BIC, empirical + implied Kendall tau, and the tail-dependence
//!   pair.
//! * [`copula_select`] — every requested family on the same data,
//!   ranked by AIC/BIC with a teaching verdict.
//!
//! ## The families and their closed forms
//!
//! | family | params | Kendall tau | tail dependence (L, U) |
//! |---|---|---|---|
//! | gaussian | `rho` | `2 arcsin(rho)/pi` | `(0, 0)` |
//! | t | `rho, nu` | `2 arcsin(rho)/pi` | `lam = 2 t_{nu+1}(-sqrt((nu+1)(1-rho)/(1+rho)))`, both |
//! | clayton | `theta > 0` | `theta/(theta+2)` | `(2^{-1/theta}, 0)` |
//! | gumbel | `theta >= 1` | `(theta-1)/theta` | `(0, 2 - 2^{1/theta})` |
//! | frank | `theta != 0` | `1 + 4(D1(theta)-1)/theta` | `(0, 0)` |
//!
//! `D1` is the Debye function ([`special`] module: Bernoulli series /
//! exponential-tail forms, ~1e-16). The Gaussian copula CDF uses a
//! transcription of Genz (2004) BVND; the t copula CDF (no closed form
//! anywhere — statsmodels raises `NotImplementedError`) uses the exact
//! conditional 1-D integral by adaptive Simpson to ~1e-12.
//!
//! ## Estimation, honestly graded
//!
//! `Tau` is the statsmodels `fit_corr_param` route (closed-form
//! inversion of tau-b); for the t family tau pins `rho` only and `nu`
//! is profiled by MLE (statsmodels provides no `nu` estimate at all).
//! Tau fits carry NaN SEs — the delta-method SE around tau's asymptotic
//! variance is deferred, not faked. `Mle` maximizes the copula
//! log-likelihood (BFGS + Nelder-Mead polish in an unconstrained
//! working space, started from the tau inversion) with
//! observed-information SEs; a non-PD Hessian (e.g. t's `nu` drifting
//! to its Gaussian-limit barrier on near-Gaussian data) reports NaN SEs
//! with `se_valid = false`.
//!
//! ## Validation
//!
//! `fixtures/tsecon-copula.json` (generated by
//! `fixtures/generate_tsecon-copula_fixtures.py`; statsmodels 0.14.6,
//! scipy 1.17.1) pins:
//!
//! * pdf/logpdf/cdf grids per family at fixed parameters against
//!   statsmodels' analytic densities and CDFs at 1e-10 (Gaussian CDF
//!   against the exact Owen's-T closed form, itself equal to scipy's
//!   `multivariate_normal.cdf` at 5e-15; t CDF against scipy `quad` on
//!   the same conditional representation, cross-checked against
//!   `multivariate_t.cdf` at that reference's ~2e-4 QMC noise);
//! * tau-inversion fits against `fit_corr_param` (elliptical /
//!   Clayton / Gumbel closed maps at 1e-12; Frank against an exact
//!   quad-Debye brentq root — statsmodels' own `theta_from_tau` has
//!   measured roundtrip gaps up to ~3e-11 and is recorded, not pinned);
//! * MLE fits against a scipy Nelder-Mead polish of the *statsmodels*
//!   log-density (statsmodels exposes no copula MLE): params at 1e-6,
//!   loglik at the respective optima at 1e-10 plus ours-never-worse,
//!   observed-information SEs at 1e-4 (same central-4 stencil both
//!   sides);
//! * Kendall tau against `scipy.stats.kendalltau` (1e-15; same tau-b
//!   estimand and float evaluation order, ties included) and
//!   [`pseudo_obs`] against `rankdata(method="average")/(n+1)` exactly;
//! * tail dependence against the closed forms, each *verified in the
//!   generator by the numeric copula limit* — which caught a genuine
//!   reference defect: statsmodels 0.14.6 `StudentTCopula.dependence_tail`
//!   has an operator-precedence bug (`(df+1)*(1-corr)/1 + corr`), e.g.
//!   0.1438 where the true value is 0.2532 at `rho = 0.5, nu = 4`; the
//!   correct Demarta-McNeil form is pinned and the buggy value recorded.
//!
//! Property tests establish: monotone-margin invariance of the whole
//! pipeline (bit-identical fits on `x` vs monotone transforms of `x`),
//! parameter recovery on deterministic conditional-inversion samples
//! from each family, near-zero tau/rho on independent data, exchange
//! symmetry (`fit(u1, u2) == fit(u2, u1)` bitwise for these exchangeable
//! families), tau/parameter roundtrips, Debye/BVND special values, and
//! teaching errors on degenerate input (too few pairs, values outside
//! `(0, 1)`, constant columns, perfect dependence, Clayton/Gumbel under
//! negative dependence).
//!
//! ```
//! use tsecon_copula::{copula_fit, pseudo_obs, Family, FitMethod};
//!
//! // Two deterministic, positively dependent margins (any scale works —
//! // pseudo_obs sees only ranks).
//! let n = 200;
//! let x: Vec<f64> = (0..n).map(|i| (i as f64 * 0.37).sin() + i as f64 * 0.01).collect();
//! let y: Vec<f64> = x.iter().map(|v| v + (v * 7.0).cos() * 0.3).collect();
//! let u = pseudo_obs(&[x, y]).unwrap();
//! let fit = copula_fit(&u[0], &u[1], Family::Gaussian, FitMethod::Mle).unwrap();
//! assert!(fit.params[0] > 0.5); // strong positive dependence detected
//! assert_eq!(fit.tail_upper, 0.0); // and the Gaussian's honest tail story
//! ```
//!
//! References: Joe (2014), *Dependence Modeling with Copulas*, CRC;
//! Genest (1987), Biometrika 74(3); Genz (2004), Statistics and
//! Computing 14; Demarta & McNeil (2005), Int. Statist. Rev. 73(1);
//! McNeil, Frey & Embrechts (2015), *Quantitative Risk Management*, ch. 7.

#![warn(missing_docs)]
#![warn(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod common;
mod error;
mod family;
mod fit;
mod special;

pub use common::MIN_OBS;
pub use error::CopulaError;
pub use family::{
    copula_cdf, copula_loglik, copula_logpdf, copula_pdf, param_to_tau, tail_dependence,
    tau_to_param, Family, FRANK_THETA_MAX,
};
pub use fit::{
    copula_fit, copula_select, pseudo_obs, CopulaFit, CopulaSelect, FitMethod, SkippedFamily,
    FRANK_MLE_THETA_MAX, NU_BOUNDS,
};

/// Empirical Kendall tau-b of two equal-length series (scipy
/// `kendalltau` semantics, ties included) — exposed because the
/// tau-inversion route makes it a quantity users will want directly.
///
/// # Errors
///
/// [`CopulaError::EmptyInput`] / [`CopulaError::NonFinite`] /
/// [`CopulaError::LengthMismatch`] on malformed input;
/// [`CopulaError::Degenerate`] when a column is constant.
pub fn kendall_tau(x: &[f64], y: &[f64]) -> Result<f64, CopulaError> {
    common::check_series(x, "x")?;
    common::check_series(y, "y")?;
    if x.len() != y.len() {
        return Err(CopulaError::LengthMismatch {
            n1: x.len(),
            n2: y.len(),
        });
    }
    common::kendall_tau(x, y)
}
