//! Golden-value tests for the SETAR concentrated-LS fit and the Hansen
//! sup-F statistic against `fixtures/setar.json` (generated by
//! `fixtures/generate_setar_fixtures.py`).
//!
//! The reference is a documented-ALGORITHM transcription: an independent
//! dense NumPy implementation of Tong-Lim (1980) concentrated least squares
//! and the Hansen (1997) sup-F, not a third-party library (no SETAR
//! reference exists in the test venv — the generator header states the
//! grading honestly). Tolerances: thresholds (order statistics of the data)
//! at 1e-12 relative; coefficients, SEs, SSRs, variances, ICs, and sup-F at
//! 1e-10 relative (normal-equation sweep + QR refit here vs. LAPACK lstsq
//! there); counts exact. The bootstrap p-value is a Monte Carlo quantity
//! and is deliberately NOT pinned — see `setar_properties.rs`.

use serde_json::Value;
use tsecon_regime::{setar, setar_test};

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/setar.json");
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

/// Relative comparison; falls back to absolute when the reference is 0.
fn assert_close(actual: f64, expected: f64, rtol: f64, ctx: &str) {
    if expected == 0.0 {
        assert!(
            actual.abs() <= rtol,
            "{ctx}: actual {actual}, expected 0 (atol {rtol})"
        );
    } else {
        let rel = ((actual - expected) / expected).abs();
        assert!(
            rel <= rtol,
            "{ctx}: actual {actual}, expected {expected}, rel err {rel:e} > {rtol:e}"
        );
    }
}

fn assert_vec_close(actual: &[f64], expected: &[f64], rtol: f64, ctx: &str) {
    assert_eq!(actual.len(), expected.len(), "{ctx} length");
    for (i, (&a, &e)) in actual.iter().zip(expected).enumerate() {
        assert_close(a, e, rtol, &format!("{ctx}[{i}]"));
    }
}

#[test]
fn setar_fit_matches_numpy_transcription() {
    let fx = fixture();
    let series = &fx["series"];
    for case in fx["fit"].as_array().expect("fit cases") {
        let name = case["series"].as_str().expect("series");
        let p = case["p"].as_u64().expect("p") as usize;
        let delays: Vec<usize> = case["delays"]
            .as_array()
            .expect("delays")
            .iter()
            .map(|v| v.as_u64().expect("delay") as usize)
            .collect();
        let trim = case["trim"].as_f64().expect("trim");
        let constant = case["constant"].as_bool().expect("constant");
        let ctx = format!("fit[{name}/p={p}/delays={delays:?}/trim={trim}]");

        let y = f64s(&series[name]);
        let r = setar(&y, p, &delays, trim, constant).expect("setar runs");

        assert_close(
            r.threshold,
            case["threshold"].as_f64().expect("threshold"),
            1e-12,
            &format!("{ctx} threshold"),
        );
        assert_eq!(
            r.delay,
            case["delay"].as_u64().expect("delay") as usize,
            "{ctx} delay"
        );
        assert_vec_close(
            &r.coefs_low,
            &f64s(&case["coefs_low"]),
            1e-10,
            &format!("{ctx} coefs_low"),
        );
        assert_vec_close(
            &r.coefs_high,
            &f64s(&case["coefs_high"]),
            1e-10,
            &format!("{ctx} coefs_high"),
        );
        assert_vec_close(
            &r.se_low,
            &f64s(&case["se_low"]),
            1e-10,
            &format!("{ctx} se_low"),
        );
        assert_vec_close(
            &r.se_high,
            &f64s(&case["se_high"]),
            1e-10,
            &format!("{ctx} se_high"),
        );
        assert_eq!(
            r.n_low,
            case["n_low"].as_u64().expect("n_low") as usize,
            "{ctx} n_low"
        );
        assert_eq!(
            r.n_high,
            case["n_high"].as_u64().expect("n_high") as usize,
            "{ctx} n_high"
        );
        assert_eq!(
            r.nobs,
            case["nobs"].as_u64().expect("nobs") as usize,
            "{ctx} nobs"
        );
        assert_eq!(
            r.min_regime,
            case["min_regime"].as_u64().expect("min_regime") as usize,
            "{ctx} min_regime"
        );
        assert_eq!(r.k, case["k"].as_u64().expect("k") as usize, "{ctx} k");
        assert_close(
            r.ssr,
            case["ssr"].as_f64().expect("ssr"),
            1e-10,
            &format!("{ctx} ssr"),
        );
        assert_close(
            r.sigma2,
            case["sigma2"].as_f64().expect("sigma2"),
            1e-10,
            &format!("{ctx} sigma2"),
        );
        assert_close(
            r.sigma2_low,
            case["sigma2_low"].as_f64().expect("sigma2_low"),
            1e-10,
            &format!("{ctx} sigma2_low"),
        );
        assert_close(
            r.sigma2_high,
            case["sigma2_high"].as_f64().expect("sigma2_high"),
            1e-10,
            &format!("{ctx} sigma2_high"),
        );
        assert_close(
            r.aic,
            case["aic"].as_f64().expect("aic"),
            1e-10,
            &format!("{ctx} aic"),
        );
        assert_close(
            r.bic,
            case["bic"].as_f64().expect("bic"),
            1e-10,
            &format!("{ctx} bic"),
        );
        assert_vec_close(
            &r.thresholds,
            &f64s(&case["thresholds"]),
            1e-12,
            &format!("{ctx} thresholds"),
        );
        assert_vec_close(
            &r.ssr_path,
            &f64s(&case["ssr_path"]),
            1e-10,
            &format!("{ctx} ssr_path"),
        );
    }
}

#[test]
fn setar_supf_statistic_matches_numpy_transcription() {
    let fx = fixture();
    let series = &fx["series"];
    for case in fx["test"].as_array().expect("test cases") {
        let name = case["series"].as_str().expect("series");
        let p = case["p"].as_u64().expect("p") as usize;
        let delay = case["delay"].as_u64().expect("delay") as usize;
        let trim = case["trim"].as_f64().expect("trim");
        let ctx = format!("supf[{name}/p={p}/d={delay}/trim={trim}]");

        let y = f64s(&series[name]);
        // A tiny n_boot: only the observed statistic is pinned here.
        let r = setar_test(&y, p, delay, trim, true, 9, 0).expect("setar_test runs");

        assert_close(
            r.stat,
            case["stat"].as_f64().expect("stat"),
            1e-10,
            &format!("{ctx} stat"),
        );
        assert_close(
            r.threshold,
            case["threshold"].as_f64().expect("threshold"),
            1e-12,
            &format!("{ctx} threshold"),
        );
        assert_eq!(
            r.nobs,
            case["nobs"].as_u64().expect("nobs") as usize,
            "{ctx} nobs"
        );
        assert_close(
            r.ssr_linear,
            case["ssr_linear"].as_f64().expect("ssr_linear"),
            1e-10,
            &format!("{ctx} ssr_linear"),
        );
        assert_close(
            r.ssr_setar,
            case["ssr_setar"].as_f64().expect("ssr_setar"),
            1e-10,
            &format!("{ctx} ssr_setar"),
        );
        assert_vec_close(
            &r.thresholds,
            &f64s(&case["thresholds"]),
            1e-12,
            &format!("{ctx} thresholds"),
        );
        assert_vec_close(
            &r.f_path,
            &f64s(&case["f_path"]),
            1e-10,
            &format!("{ctx} f_path"),
        );
        assert_eq!(r.boot_stats.len(), 9, "{ctx} boot draws");
        assert!(
            r.p_value > 0.0 && r.p_value <= 1.0,
            "{ctx} p_value in (0, 1]"
        );
    }
}
