//! Golden-value tests for the Hansen (1997/2000) threshold confidence set
//! against `fixtures/setar_ci.json` (generated by
//! `fixtures/generate_setar_ci_fixtures.py`).
//!
//! Two kinds of pins, graded as the generator header states:
//!
//! * documented-FORMULA golden — the closed-form critical value
//!   `c(level) = -2 ln(1 - sqrt(level))` and the p-value function
//!   `p(x) = 1 - (1 - exp(-x/2))^2`, pinned at 1e-14 relative (full double
//!   precision), and Hansen (2000) Table 1 reproduced to the printed two
//!   decimals;
//! * cross-IMPLEMENTATION golden — an independent NumPy transcription of
//!   the LR profile, Hansen's programs' `eta^2` convention, the interval /
//!   hull construction, the null-threshold inversion, and the slope
//!   unions, pinned at 1e-10 relative (thresholds — order statistics of
//!   the data — at 1e-12; counts and flags exact). No third-party
//!   threshold-CI code runs in the fixture container.
//!
//! The fit underneath must be `setar`'s own: `threshold`, `thresholds`,
//! and `ssr_path` are asserted BIT-identical to `setar`'s output, not
//! merely close.

use serde_json::Value;
use tsecon_regime::{
    hansen_lr_critical_value, hansen_lr_pvalue, setar, setar_threshold_ci, RegimeError,
    ThresholdCiOptions,
};

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/setar_ci.json");
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

/// Relative comparison; falls back to absolute when the reference is 0.
fn assert_close(actual: f64, expected: f64, rtol: f64, ctx: &str) {
    if expected == 0.0 {
        assert!(
            actual.abs() <= rtol,
            "{ctx}: actual {actual}, expected 0 (atol {rtol})"
        );
    } else {
        let rel = ((actual - expected) / expected).abs();
        assert!(
            rel <= rtol,
            "{ctx}: actual {actual}, expected {expected}, rel err {rel:e} > {rtol:e}"
        );
    }
}

fn assert_vec_close(actual: &[f64], expected: &[f64], rtol: f64, ctx: &str) {
    assert_eq!(actual.len(), expected.len(), "{ctx} length");
    for (i, (&a, &e)) in actual.iter().zip(expected).enumerate() {
        assert_close(a, e, rtol, &format!("{ctx}[{i}]"));
    }
}

fn opts_of(case: &Value) -> ThresholdCiOptions {
    ThresholdCiOptions {
        level: case["level"].as_f64().expect("level"),
        het_robust: case["het_robust"].as_bool().expect("het_robust"),
        slope_level: case["slope_level"].as_f64(),
        slope_region_level: case["slope_region_level"].as_f64().unwrap_or(0.80),
        null_threshold: case["null_threshold"].as_f64(),
    }
}

#[test]
fn closed_form_critical_values_and_pvalues_match_the_documented_formulas() {
    let fx = fixture();
    for row in fx["critical_values"].as_array().expect("critical_values") {
        let level = row["level"].as_f64().expect("level");
        let expected = row["crit"].as_f64().expect("crit");
        let got = hansen_lr_critical_value(level).expect("valid level");
        assert_close(got, expected, 1e-14, &format!("crit[{level}]"));
        // The inversion the set relies on: p(c(level)) = 1 - level.
        let p = hansen_lr_pvalue(got).expect("nonnegative");
        assert_close(p, 1.0 - level, 1e-12, &format!("p(c({level}))"));
    }
    for row in fx["pvalues"].as_array().expect("pvalues") {
        let x = row["x"].as_f64().expect("x");
        let expected = row["p"].as_f64().expect("p");
        let got = hansen_lr_pvalue(x).expect("nonnegative");
        assert_close(got, expected, 1e-14, &format!("pvalue[{x}]"));
    }
}

#[test]
fn hansen_2000_table_1_is_reproduced_to_the_printed_decimals() {
    let fx = fixture();
    let table = fx["_meta"]["hansen_2000_table_1"]
        .as_object()
        .expect("table 1");
    assert_eq!(table.len(), 7, "all seven printed levels");
    for (level_str, printed) in table {
        let level: f64 = level_str.parse().expect("level key");
        let printed = printed.as_f64().expect("printed value");
        let got = hansen_lr_critical_value(level).expect("valid level");
        assert_eq!(
            format!("{got:.2}"),
            format!("{printed:.2}"),
            "Table 1 at level {level}: computed {got} vs printed {printed}"
        );
    }
    // Spot values as they appear in the paper.
    assert_eq!(
        format!("{:.2}", hansen_lr_critical_value(0.95).unwrap()),
        "7.35"
    );
    assert_eq!(
        format!("{:.2}", hansen_lr_critical_value(0.90).unwrap()),
        "5.94"
    );
    assert_eq!(
        format!("{:.2}", hansen_lr_critical_value(0.99).unwrap()),
        "10.59"
    );
}

#[test]
fn threshold_ci_matches_numpy_transcription_and_reuses_the_setar_fit_bit_for_bit() {
    let fx = fixture();
    let series = &fx["series"];
    let cases = fx["cases"].as_array().expect("cases");
    assert!(cases.len() >= 7, "expected the seven generated cases");
    let mut saw_disjoint = false;
    let mut saw_het = false;
    let mut saw_slope = false;
    for case in cases {
        let name = case["series"].as_str().expect("series");
        let p = case["p"].as_u64().expect("p") as usize;
        let delays: Vec<usize> = case["delays"]
            .as_array()
            .expect("delays")
            .iter()
            .map(|v| v.as_u64().expect("delay") as usize)
            .collect();
        let trim = case["trim"].as_f64().expect("trim");
        let constant = case["constant"].as_bool().expect("constant");
        let opts = opts_of(case);
        let ctx = format!(
            "ci[{name}/p={p}/delays={delays:?}/trim={trim}/level={}/het={}]",
            opts.level, opts.het_robust
        );

        let y = f64s(&series[name]);
        let r = setar_threshold_ci(&y, p, &delays, trim, constant, &opts).expect("ci runs");

        // Bit-identity with the plain fit: same grid, same profile, same
        // estimate — the set sits on exactly the fit `setar` reports.
        let fit = setar(&y, p, &delays, trim, constant).expect("setar runs");
        assert_eq!(
            r.threshold.to_bits(),
            fit.threshold.to_bits(),
            "{ctx} threshold bits"
        );
        assert_eq!(r.delay, Some(fit.delay), "{ctx} delay");
        assert_eq!(r.thresholds, fit.thresholds, "{ctx} thresholds bits");
        assert_eq!(r.ssr_path, fit.ssr_path, "{ctx} ssr_path bits");
        assert_eq!(r.nobs, fit.nobs, "{ctx} nobs");
        assert_eq!(r.k, fit.k, "{ctx} k");

        // The transcription.
        assert_close(
            r.threshold,
            case["threshold"].as_f64().expect("threshold"),
            1e-12,
            &format!("{ctx} threshold"),
        );
        assert_eq!(
            r.delay,
            Some(case["delay"].as_u64().expect("delay") as usize)
        );
        assert_eq!(r.nobs, case["nobs"].as_u64().expect("nobs") as usize);
        assert_eq!(r.k, case["k"].as_u64().expect("k") as usize);
        assert_eq!(r.level, opts.level);
        assert_eq!(r.het_robust, opts.het_robust);
        assert_close(
            r.lr_crit,
            case["lr_crit"].as_f64().expect("lr_crit"),
            1e-14,
            &format!("{ctx} lr_crit"),
        );
        assert_close(
            r.eta2,
            case["eta2"].as_f64().expect("eta2"),
            1e-10,
            &format!("{ctx} eta2"),
        );
        if !opts.het_robust {
            assert_eq!(
                r.eta2, 1.0,
                "{ctx} eta2 is exactly one without the correction"
            );
        } else {
            saw_het = true;
        }
        assert_close(
            r.lr_crit_scaled,
            case["lr_crit_scaled"].as_f64().expect("lr_crit_scaled"),
            1e-10,
            &format!("{ctx} lr_crit_scaled"),
        );
        assert_vec_close(
            &r.thresholds,
            &f64s(&case["thresholds"]),
            1e-12,
            &format!("{ctx} thresholds"),
        );
        assert_vec_close(
            &r.ssr_path,
            &f64s(&case["ssr_path"]),
            1e-10,
            &format!("{ctx} ssr_path"),
        );
        assert_vec_close(
            &r.lr_stat,
            &f64s(&case["lr_stat"]),
            1e-10,
            &format!("{ctx} lr_stat"),
        );
        let in_set: Vec<bool> = case["in_set"]
            .as_array()
            .expect("in_set")
            .iter()
            .map(|v| v.as_bool().expect("bool"))
            .collect();
        assert_eq!(r.in_set, in_set, "{ctx} in_set");
        let intervals: Vec<(f64, f64)> = case["intervals"]
            .as_array()
            .expect("intervals")
            .iter()
            .map(|iv| {
                let pair = f64s(iv);
                (pair[0], pair[1])
            })
            .collect();
        assert_eq!(r.intervals.len(), intervals.len(), "{ctx} interval count");
        for (i, (got, want)) in r.intervals.iter().zip(&intervals).enumerate() {
            assert_close(got.0, want.0, 1e-12, &format!("{ctx} interval[{i}].low"));
            assert_close(got.1, want.1, 1e-12, &format!("{ctx} interval[{i}].high"));
        }
        if intervals.len() > 1 {
            saw_disjoint = true;
        }
        assert_eq!(
            r.is_connected,
            case["is_connected"].as_bool().expect("is_connected"),
            "{ctx} is_connected"
        );
        assert_close(
            r.ci_low,
            case["ci_low"].as_f64().expect("ci_low"),
            1e-12,
            &format!("{ctx} ci_low"),
        );
        assert_close(
            r.ci_high,
            case["ci_high"].as_f64().expect("ci_high"),
            1e-12,
            &format!("{ctx} ci_high"),
        );
        assert_eq!(
            r.n_in_set,
            case["n_in_set"].as_u64().expect("n_in_set") as usize,
            "{ctx} n_in_set"
        );

        match opts.null_threshold {
            None => {
                assert_eq!(r.null_threshold_used, None, "{ctx} no null used");
                assert_eq!(r.lr_at_null, None, "{ctx} no lr_at_null");
                assert_eq!(r.pvalue_at_threshold, None, "{ctx} no p-value");
            }
            Some(_) => {
                assert_close(
                    r.null_threshold_used.expect("used"),
                    case["null_threshold_used"].as_f64().expect("used"),
                    1e-12,
                    &format!("{ctx} null_threshold_used"),
                );
                assert_close(
                    r.lr_at_null.expect("lr0"),
                    case["lr_at_null"].as_f64().expect("lr0"),
                    1e-10,
                    &format!("{ctx} lr_at_null"),
                );
                assert_close(
                    r.pvalue_at_threshold.expect("p0"),
                    case["pvalue_at_threshold"].as_f64().expect("p0"),
                    1e-10,
                    &format!("{ctx} pvalue_at_threshold"),
                );
            }
        }

        match opts.slope_level {
            None => assert!(r.slope.is_none(), "{ctx} no slope block"),
            Some(sl) => {
                saw_slope = true;
                let s = r.slope.as_ref().expect("slope block");
                let want = &case["slope"];
                assert_eq!(s.level, sl);
                assert_eq!(s.region_level, opts.slope_region_level);
                assert_close(
                    s.region_low,
                    want["region_low"].as_f64().expect("region_low"),
                    1e-12,
                    &format!("{ctx} region_low"),
                );
                assert_close(
                    s.region_high,
                    want["region_high"].as_f64().expect("region_high"),
                    1e-12,
                    &format!("{ctx} region_high"),
                );
                assert_eq!(
                    s.n_region,
                    want["n_region"].as_u64().expect("n_region") as usize,
                    "{ctx} n_region"
                );
                for (key, got) in [
                    ("low_lower", &s.low_lower),
                    ("low_upper", &s.low_upper),
                    ("high_lower", &s.high_lower),
                    ("high_upper", &s.high_upper),
                ] {
                    assert_vec_close(got, &f64s(&want[key]), 1e-10, &format!("{ctx} {key}"));
                }
            }
        }
    }
    assert!(saw_disjoint, "the fixture must exercise a disjoint set");
    assert!(saw_het, "the fixture must exercise the eta^2 correction");
    assert!(saw_slope, "the fixture must exercise the slope unions");
}

#[test]
fn unidentified_eta2_on_linear_data_is_a_teaching_error_not_a_number() {
    // The generator documents this refusal on the `linear_ar2` series: no
    // threshold effect, so delta^ ~ 0 and the quadratic fit of
    // e^2 (x'delta)^2 is negative at gamma^ (eta^2 = -0.27 in NumPy).
    let fx = fixture();
    let y = f64s(&fx["series"]["linear_ar2"]);
    let opts = ThresholdCiOptions {
        level: 0.80,
        het_robust: true,
        ..ThresholdCiOptions::default()
    };
    let err = setar_threshold_ci(&y, 2, &[1, 2], 0.15, false, &opts).expect_err("refused");
    match err {
        RegimeError::NonFinite { what } => {
            assert!(
                what.contains("eta^2"),
                "message names the correction: {what}"
            );
            assert!(
                what.contains("het_robust = false"),
                "message names the way out: {what}"
            );
        }
        other => panic!("expected NonFinite, got {other:?}"),
    }
    // The homoskedastic set on the same series is the stored case.
    let opts = ThresholdCiOptions {
        level: 0.80,
        het_robust: false,
        ..ThresholdCiOptions::default()
    };
    let r = setar_threshold_ci(&y, 2, &[1, 2], 0.15, false, &opts).expect("runs");
    assert_eq!(r.eta2, 1.0);
}
