//! Golden-value tests for the STAR family against `fixtures/star.json`
//! (generated by `fixtures/generate_star_fixtures.py`).
//!
//! The reference is a documented-ALGORITHM transcription: an independent
//! dense NumPy/SciPy implementation of the Luukkonen-Saikkonen-Terasvirta
//! (1988) / Terasvirta (1994) auxiliary regressions, the concentrated STAR
//! OLS with Gauss-Newton standard errors, and the `(gamma, c)` grid — not
//! a third-party library (no STAR reference is reachable from this
//! environment; the generator header states the grading honestly).
//! Tolerances: statistics, p-values, coefficients, SEs, SSRs, and grid
//! surfaces at 1e-10 relative (normal equations/QR here vs. LAPACK lstsq
//! there); counts and verdicts exact. The Nelder-Mead refinement of
//! `(gamma, c)` is deliberately NOT pinned — see `star_properties.rs`.

use serde_json::Value;
use tsecon_regime::{star, star_eval, star_test, StarModel};

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/star.json");
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

fn model_of(name: &str) -> StarModel {
    match name {
        "lstar" => StarModel::Lstar,
        "estar" => StarModel::Estar,
        other => panic!("unknown model {other}"),
    }
}

/// Relative comparison with an absolute floor of `rtol`. The floor
/// matters for near-zero F statistics: `F = (SSR_r - SSR_f)/...` is a
/// difference of two O(100) SSRs, so when the difference is O(1e-13) its
/// *relative* accuracy is limited by cancellation even though both SSRs
/// match at 1e-10 — the absolute agreement (here far below 1e-10) is the
/// honest pin.
fn assert_close(actual: f64, expected: f64, rtol: f64, ctx: &str) {
    let abs = (actual - expected).abs();
    if abs <= rtol {
        return;
    }
    let rel = if expected == 0.0 {
        f64::INFINITY
    } else {
        (abs / expected).abs()
    };
    assert!(
        rel <= rtol,
        "{ctx}: actual {actual}, expected {expected}, rel err {rel:e} > {rtol:e}"
    );
}

fn assert_vec_close(actual: &[f64], expected: &[f64], rtol: f64, ctx: &str) {
    assert_eq!(actual.len(), expected.len(), "{ctx} length");
    for (i, (&a, &e)) in actual.iter().zip(expected).enumerate() {
        assert_close(a, e, rtol, &format!("{ctx}[{i}]"));
    }
}

#[test]
fn star_test_battery_matches_numpy_transcription() {
    let fx = fixture();
    let series = &fx["series"];
    for case in fx["test"].as_array().expect("test cases") {
        let name = case["series"].as_str().expect("series");
        let p = case["p"].as_u64().expect("p") as usize;
        let delays: Vec<usize> = case["delays"]
            .as_array()
            .expect("delays")
            .iter()
            .map(|v| v.as_u64().expect("delay") as usize)
            .collect();
        let ctx = format!("test[{name}/p={p}/delays={delays:?}]");

        let y = f64s(&series[name]);
        let r = star_test(&y, p, &delays).expect("star_test runs");

        assert_eq!(
            r.best,
            case["best"].as_u64().expect("best") as usize,
            "{ctx} best"
        );
        let expected = case["tests"].as_array().expect("tests");
        assert_eq!(r.tests.len(), expected.len(), "{ctx} batteries");
        for (t, e) in r.tests.iter().zip(expected) {
            let dctx = format!("{ctx}/d={}", t.delay);
            assert_eq!(t.delay, e["delay"].as_u64().expect("delay") as usize);
            assert_eq!(
                t.nobs,
                e["nobs"].as_u64().expect("nobs") as usize,
                "{dctx} nobs"
            );
            assert_eq!(t.q, e["q"].as_u64().expect("q") as usize, "{dctx} q");
            assert_eq!(t.k0, e["k0"].as_u64().expect("k0") as usize, "{dctx} k0");
            for (label, actual, key) in [
                ("lm3_stat", t.lm3_stat, "lm3_stat"),
                ("lm3_p_value", t.lm3_p_value, "lm3_p_value"),
                ("lm3_f_stat", t.lm3_f_stat, "lm3_f_stat"),
                ("lm3_f_p_value", t.lm3_f_p_value, "lm3_f_p_value"),
                ("h3_f_stat", t.h3_f_stat, "h3_f_stat"),
                ("h3_p_value", t.h3_p_value, "h3_p_value"),
                ("h2_f_stat", t.h2_f_stat, "h2_f_stat"),
                ("h2_p_value", t.h2_p_value, "h2_p_value"),
                ("h1_f_stat", t.h1_f_stat, "h1_f_stat"),
                ("h1_p_value", t.h1_p_value, "h1_p_value"),
                ("ssr0", t.ssr0, "ssr0"),
                ("ssr1", t.ssr1, "ssr1"),
                ("ssr2", t.ssr2, "ssr2"),
                ("ssr3", t.ssr3, "ssr3"),
            ] {
                assert_close(
                    actual,
                    e[key].as_f64().expect(key),
                    1e-10,
                    &format!("{dctx} {label}"),
                );
            }
            assert_eq!(
                t.suggested.name(),
                e["suggested"].as_str().expect("suggested"),
                "{dctx} suggested"
            );
        }
    }
}

#[test]
fn star_eval_matches_numpy_transcription() {
    let fx = fixture();
    let series = &fx["series"];
    for case in fx["eval"].as_array().expect("eval cases") {
        let name = case["series"].as_str().expect("series");
        let p = case["p"].as_u64().expect("p") as usize;
        let delay = case["delay"].as_u64().expect("delay") as usize;
        let model = model_of(case["model"].as_str().expect("model"));
        let gamma = case["gamma"].as_f64().expect("gamma");
        let c = case["c"].as_f64().expect("c");
        let constant = case["constant"].as_bool().expect("constant");
        let ctx = format!(
            "eval[{name}/p={p}/d={delay}/{}/g={gamma}/c={c}]",
            model.name()
        );

        let y = f64s(&series[name]);
        let r = star_eval(&y, p, delay, model, gamma, c, constant).expect("star_eval runs");

        assert_vec_close(
            &r.coefs_linear,
            &f64s(&case["coefs_linear"]),
            1e-10,
            &format!("{ctx} coefs_linear"),
        );
        assert_vec_close(
            &r.coefs_nonlinear,
            &f64s(&case["coefs_nonlinear"]),
            1e-10,
            &format!("{ctx} coefs_nonlinear"),
        );
        assert!(r.se_valid, "{ctx} se_valid");
        assert_vec_close(
            &r.se_linear,
            &f64s(&case["se_linear"]),
            1e-10,
            &format!("{ctx} se_linear"),
        );
        assert_vec_close(
            &r.se_nonlinear,
            &f64s(&case["se_nonlinear"]),
            1e-10,
            &format!("{ctx} se_nonlinear"),
        );
        assert_close(
            r.se_gamma,
            case["se_gamma"].as_f64().expect("se_gamma"),
            1e-10,
            &format!("{ctx} se_gamma"),
        );
        assert_close(
            r.se_c,
            case["se_c"].as_f64().expect("se_c"),
            1e-10,
            &format!("{ctx} se_c"),
        );
        for (label, actual, key) in [
            ("ssr", r.ssr, "ssr"),
            ("sigma2", r.sigma2, "sigma2"),
            ("loglik", r.loglik, "loglik"),
            ("aic", r.aic, "aic"),
            ("bic", r.bic, "bic"),
        ] {
            assert_close(
                actual,
                case[key].as_f64().expect(key),
                1e-10,
                &format!("{ctx} {label}"),
            );
        }
        assert_eq!(
            r.nobs,
            case["nobs"].as_u64().expect("nobs") as usize,
            "{ctx} nobs"
        );
        assert_eq!(r.k, case["k"].as_u64().expect("k") as usize, "{ctx} k");
        assert_vec_close(
            &r.transition[..8],
            &f64s(&case["transition_head"]),
            1e-10,
            &format!("{ctx} transition_head"),
        );
        assert_close(
            r.transition.iter().sum::<f64>(),
            case["transition_sum"].as_f64().expect("transition_sum"),
            1e-10,
            &format!("{ctx} transition_sum"),
        );
    }
}

#[test]
fn star_grid_matches_numpy_transcription() {
    let fx = fixture();
    let series = &fx["series"];
    for case in fx["grid"].as_array().expect("grid cases") {
        let name = case["series"].as_str().expect("series");
        let p = case["p"].as_u64().expect("p") as usize;
        let delay = case["delay"].as_u64().expect("delay") as usize;
        let model = model_of(case["model"].as_str().expect("model"));
        let trim = case["trim"].as_f64().expect("trim");
        let n_gamma = case["n_gamma"].as_u64().expect("n_gamma") as usize;
        let n_c = case["n_c"].as_u64().expect("n_c") as usize;
        let ctx = format!("grid[{name}/{}/d={delay}]", model.name());

        let y = f64s(&series[name]);
        let r = star(&y, p, &[delay], model, trim, true, n_gamma, n_c).expect("star runs");

        assert_close(
            r.s_sd,
            case["s_sd"].as_f64().expect("s_sd"),
            1e-12,
            &format!("{ctx} s_sd"),
        );
        assert_vec_close(
            &r.grid_gamma,
            &f64s(&case["grid_gamma"]),
            1e-12,
            &format!("{ctx} grid_gamma"),
        );
        assert_vec_close(
            &r.grid_c,
            &f64s(&case["grid_c"]),
            1e-12,
            &format!("{ctx} grid_c"),
        );
        let expected_grid = case["ssr_grid"].as_array().expect("ssr_grid");
        assert_eq!(r.ssr_grid.len(), expected_grid.len(), "{ctx} ssr_grid len");
        for (i, (a, e)) in r.ssr_grid.iter().zip(expected_grid).enumerate() {
            match e.as_f64() {
                Some(v) => assert_close(*a, v, 1e-10, &format!("{ctx} ssr_grid[{i}]")),
                // null marks a singular cell in the transcription; the
                // Rust side marks it NaN.
                None => assert!(a.is_nan(), "{ctx} ssr_grid[{i}] should be NaN"),
            }
        }
        let bc = case["best_cell"].as_array().expect("best_cell");
        assert_eq!(
            r.best_cell,
            (
                bc[0].as_u64().expect("i") as usize,
                bc[1].as_u64().expect("j") as usize
            ),
            "{ctx} best_cell"
        );
        // The refinement can only improve on (or match) the best cell.
        let best_ssr = case["best_ssr"].as_f64().expect("best_ssr");
        assert!(
            r.eval.ssr <= best_ssr * (1.0 + 1e-12),
            "{ctx} refined SSR {} above grid best {best_ssr}",
            r.eval.ssr
        );
    }
}
