//! Golden-value tests for the threshold-VAR concentrated fit and the
//! robust sup-Wald linearity statistic against `fixtures/tvar.json`
//! (generated by `fixtures/generate_tvar_fixtures.py`).
//!
//! The reference is a documented-ALGORITHM transcription: an independent
//! dense NumPy implementation of the concentrated `ln det` scan and the
//! Eicker-White score-form statistic, not a third-party library (no TVAR
//! reference runs in this container — the generator header states the
//! grading honestly). Tolerances: thresholds (order statistics of the
//! data) at 1e-12 relative; coefficients, SEs, covariances, criteria, and
//! the statistic at 1e-10 relative; counts exact. The bootstrap p-value
//! is a Monte Carlo quantity and is deliberately NOT pinned — see
//! `tvar_properties.rs`.

use serde_json::Value;
use tsecon_regime::{threshold_var, threshold_var_test};

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/tvar.json");
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

fn f64mat(v: &Value) -> Vec<Vec<f64>> {
    v.as_array().expect("matrix").iter().map(f64s).collect()
}

/// Relative comparison; falls back to absolute when the reference is 0.
fn assert_close(actual: f64, expected: f64, rtol: f64, ctx: &str) {
    if expected == 0.0 {
        assert!(
            actual.abs() <= rtol,
            "{ctx}: actual {actual}, expected 0 (atol {rtol})"
        );
    } else {
        let rel = ((actual - expected) / expected).abs();
        assert!(
            rel <= rtol,
            "{ctx}: actual {actual}, expected {expected}, rel err {rel:e} > {rtol:e}"
        );
    }
}

fn assert_vec_close(actual: &[f64], expected: &[f64], rtol: f64, ctx: &str) {
    assert_eq!(actual.len(), expected.len(), "{ctx} length");
    for (i, (&a, &e)) in actual.iter().zip(expected).enumerate() {
        assert_close(a, e, rtol, &format!("{ctx}[{i}]"));
    }
}

fn assert_mat_close(actual: &[Vec<f64>], expected: &[Vec<f64>], rtol: f64, ctx: &str) {
    assert_eq!(actual.len(), expected.len(), "{ctx} rows");
    for (i, (a, e)) in actual.iter().zip(expected).enumerate() {
        assert_vec_close(a, e, rtol, &format!("{ctx}[{i}]"));
    }
}

#[test]
fn tvar_fit_matches_numpy_transcription() {
    let fx = fixture();
    let series = &fx["series"];
    for case in fx["fit"].as_array().expect("fit cases") {
        let name = case["series"].as_str().expect("series");
        let p = case["p"].as_u64().expect("p") as usize;
        let tv = case["threshold_index"].as_u64().expect("threshold_index") as usize;
        let delays: Vec<usize> = case["delays"]
            .as_array()
            .expect("delays")
            .iter()
            .map(|v| v.as_u64().expect("delay") as usize)
            .collect();
        let trim = case["trim"].as_f64().expect("trim");
        let constant = case["constant"].as_bool().expect("constant");
        let ctx = format!("fit[{name}/p={p}/tv={tv}/delays={delays:?}/trim={trim}]");

        let y = f64mat(&series[name]);
        let r = threshold_var(&y, p, tv, &delays, trim, constant).expect("threshold_var runs");

        assert_close(
            r.threshold,
            case["threshold"].as_f64().expect("threshold"),
            1e-12,
            &format!("{ctx} threshold"),
        );
        assert_eq!(
            r.delay,
            case["delay"].as_u64().expect("delay") as usize,
            "{ctx} delay"
        );
        assert_eq!(r.threshold_index, tv, "{ctx} threshold_index");
        assert_mat_close(
            &r.coefs_low,
            &f64mat(&case["coefs_low"]),
            1e-10,
            &format!("{ctx} coefs_low"),
        );
        assert_mat_close(
            &r.coefs_high,
            &f64mat(&case["coefs_high"]),
            1e-10,
            &format!("{ctx} coefs_high"),
        );
        assert_mat_close(
            &r.se_low,
            &f64mat(&case["se_low"]),
            1e-10,
            &format!("{ctx} se_low"),
        );
        assert_mat_close(
            &r.se_high,
            &f64mat(&case["se_high"]),
            1e-10,
            &format!("{ctx} se_high"),
        );
        assert_eq!(
            r.n_low,
            case["n_low"].as_u64().expect("n_low") as usize,
            "{ctx} n_low"
        );
        assert_eq!(
            r.n_high,
            case["n_high"].as_u64().expect("n_high") as usize,
            "{ctx} n_high"
        );
        assert_eq!(
            r.nobs,
            case["nobs"].as_u64().expect("nobs") as usize,
            "{ctx} nobs"
        );
        assert_mat_close(
            &r.sigma,
            &f64mat(&case["sigma"]),
            1e-10,
            &format!("{ctx} sigma"),
        );
        assert_mat_close(
            &r.sigma_low,
            &f64mat(&case["sigma_low"]),
            1e-10,
            &format!("{ctx} sigma_low"),
        );
        assert_mat_close(
            &r.sigma_high,
            &f64mat(&case["sigma_high"]),
            1e-10,
            &format!("{ctx} sigma_high"),
        );
        assert_close(
            r.log_det_sigma,
            case["log_det_sigma"].as_f64().expect("log_det_sigma"),
            1e-10,
            &format!("{ctx} log_det_sigma"),
        );
        assert_close(
            r.llf,
            case["llf"].as_f64().expect("llf"),
            1e-10,
            &format!("{ctx} llf"),
        );
        assert_close(
            r.aic,
            case["aic"].as_f64().expect("aic"),
            1e-10,
            &format!("{ctx} aic"),
        );
        assert_close(
            r.bic,
            case["bic"].as_f64().expect("bic"),
            1e-10,
            &format!("{ctx} bic"),
        );
        assert_vec_close(
            &r.thresholds,
            &f64s(&case["thresholds"]),
            1e-12,
            &format!("{ctx} thresholds"),
        );
        assert_vec_close(
            &r.logdet_path,
            &f64s(&case["logdet_path"]),
            1e-10,
            &format!("{ctx} logdet_path"),
        );
        assert_eq!(
            r.min_regime,
            case["min_regime"].as_u64().expect("min_regime") as usize,
            "{ctx} min_regime"
        );
        assert_eq!(
            r.n_regressors,
            case["n_regressors"].as_u64().expect("n_regressors") as usize,
            "{ctx} n_regressors"
        );
    }
}

#[test]
fn tvar_supwald_statistic_matches_numpy_transcription() {
    let fx = fixture();
    let series = &fx["series"];
    for case in fx["test"].as_array().expect("test cases") {
        let name = case["series"].as_str().expect("series");
        let p = case["p"].as_u64().expect("p") as usize;
        let tv = case["threshold_index"].as_u64().expect("threshold_index") as usize;
        let delay = case["delay"].as_u64().expect("delay") as usize;
        let trim = case["trim"].as_f64().expect("trim");
        let n_grid = case["n_grid"].as_u64().expect("n_grid") as usize;
        let constant = case["constant"].as_bool().expect("constant");
        let ctx = format!("supW[{name}/p={p}/d={delay}/trim={trim}/grid={n_grid}]");

        let y = f64mat(&series[name]);
        // A tiny n_boot: only the observed statistic is pinned here.
        let r = threshold_var_test(&y, p, tv, delay, trim, constant, n_grid, 9, 0)
            .expect("threshold_var_test runs");

        assert_close(
            r.stat,
            case["stat"].as_f64().expect("stat"),
            1e-10,
            &format!("{ctx} stat"),
        );
        assert_close(
            r.threshold,
            case["threshold"].as_f64().expect("threshold"),
            1e-12,
            &format!("{ctx} threshold"),
        );
        assert_eq!(
            r.nobs,
            case["nobs"].as_u64().expect("nobs") as usize,
            "{ctx} nobs"
        );
        assert_eq!(
            r.min_regime,
            case["min_regime"].as_u64().expect("min_regime") as usize,
            "{ctx} min_regime"
        );
        assert_eq!(
            r.n_regressors,
            case["n_regressors"].as_u64().expect("n_regressors") as usize,
            "{ctx} n_regressors"
        );
        assert_vec_close(
            &r.thresholds,
            &f64s(&case["thresholds"]),
            1e-12,
            &format!("{ctx} thresholds"),
        );
        assert_vec_close(
            &r.wald_path,
            &f64s(&case["wald_path"]),
            1e-10,
            &format!("{ctx} wald_path"),
        );
        assert_eq!(r.boot_stats.len(), 9, "{ctx} boot draws");
        assert!(
            r.p_value > 0.0 && r.p_value <= 1.0,
            "{ctx} p_value in (0, 1]"
        );
    }
}
