//! Golden-value tests for the threshold-VAR generalized impulse responses
//! against `fixtures/girf.json` (generated by
//! `fixtures/generate_girf_fixtures.py`).
//!
//! The reference is an independent NumPy transcription of the DOCUMENTED
//! engine (history selection, Philox substream tree, Box-Muller normals,
//! regime-by-regime innovation scaling, common random numbers, antithetic
//! pairs, and every summary) that reproduces the engine's random streams
//! exactly through NumPy's own SeedSequence / Philox / Generator — so the
//! pinned numbers are the simulation itself, not just its expectation. No
//! third-party TVAR GIRF runs in this container (no tsDyn). The TVAR fit
//! underneath is the transcription already pinned by `tvar.json`.
//!
//! Tolerance: 1e-10 relative (absolute floor 1e-10) on every path array
//! and scalar; regimes, times and counts exact.

use serde_json::Value;
use tsecon_regime::{threshold_var, tvar_girf, GirfRegime, TvarGirfOptions};
use tsecon_var::GirfShock;

const TOL: f64 = 1e-10;

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/girf.json");
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn rows(v: &Value) -> Vec<Vec<f64>> {
    v.as_array()
        .expect("rows")
        .iter()
        .map(|r| {
            r.as_array()
                .expect("row")
                .iter()
                .map(|x| x.as_f64().expect("number"))
                .collect()
        })
        .collect()
}

fn close(a: f64, e: f64, ctx: &str) {
    let scale = e.abs().max(1.0);
    assert!(
        (a - e).abs() <= TOL * scale,
        "{ctx}: {a} vs {e} (scaled diff {:e} > {TOL:e})",
        (a - e).abs() / scale
    );
}

fn assert_path(actual: &[Vec<f64>], expected: &Value, ctx: &str) {
    let e = rows(expected);
    assert_eq!(actual.len(), e.len(), "{ctx}: horizon count");
    for (h, (ar, er)) in actual.iter().zip(&e).enumerate() {
        assert_eq!(ar.len(), er.len(), "{ctx}[{h}]: width");
        for (j, (&a, &ev)) in ar.iter().zip(er).enumerate() {
            close(a, ev, &format!("{ctx}[h={h}][{j}]"));
        }
    }
}

fn usizes(v: &Value) -> Vec<usize> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_u64().expect("integer") as usize)
        .collect()
}

#[test]
fn tvar_girf_matches_the_numpy_engine_transcription() {
    let fx = fixture();
    let tv = &fx["tvar"];
    let y = rows(&tv["series"]);
    let p = tv["p"].as_u64().expect("p") as usize;
    let tvi = tv["threshold_index"].as_u64().expect("tv") as usize;
    let delays = usizes(&tv["delays"]);
    let trim = tv["trim"].as_f64().expect("trim");
    let constant = tv["constant"].as_bool().expect("constant");
    let fit = threshold_var(&y, p, tvi, &delays, trim, constant).expect("fit");
    close(
        fit.threshold,
        tv["fit"]["threshold"].as_f64().expect("threshold"),
        "fit threshold",
    );
    assert_eq!(
        fit.delay,
        tv["fit"]["delay"].as_u64().expect("delay") as usize
    );

    for case in tv["cases"].as_array().expect("cases") {
        let var = case["shock_var"].as_u64().expect("shock_var") as usize;
        let size = case["size"].as_f64().expect("size");
        let shock = match case["shock"].as_str().expect("shock") {
            "orthogonal" => GirfShock::Orthogonal { var, size },
            "generalized" => GirfShock::Generalized { var, size },
            other => panic!("unknown shock {other}"),
        };
        let bands = case["bands"].as_array().expect("bands");
        let regime = match case["regime"].as_str().expect("regime") {
            "all" => GirfRegime::All,
            "low" => GirfRegime::Low,
            "high" => GirfRegime::High,
            other => panic!("unknown regime {other}"),
        };
        let opts = TvarGirfOptions {
            shock,
            horizon: case["horizon"].as_u64().expect("horizon") as usize,
            n_draws: case["n_draws"].as_u64().expect("n_draws") as usize,
            seed: case["seed"].as_u64().expect("seed"),
            antithetic: case["antithetic"].as_bool().expect("antithetic"),
            bands: (
                bands[0].as_f64().expect("lower"),
                bands[1].as_f64().expect("upper"),
            ),
            regime,
            histories: case["histories"].as_u64().map(|m| m as usize),
        };
        let g = tvar_girf(&fit, &y, &opts).expect("girf");
        let ctx = format!(
            "{} j={var} size={size} regime={}",
            case["shock"], case["regime"]
        );
        assert_eq!(
            g.n_histories,
            case["n_histories"].as_u64().unwrap() as usize,
            "{ctx}"
        );
        assert_eq!(
            g.n_low_histories,
            case["n_low_histories"].as_u64().unwrap() as usize
        );
        assert_eq!(
            g.n_high_histories,
            case["n_high_histories"].as_u64().unwrap() as usize
        );
        assert_eq!(
            g.history_regimes,
            usizes(&case["history_regimes"]),
            "{ctx} regimes"
        );
        assert_eq!(
            g.history_times,
            usizes(&case["history_times"]),
            "{ctx} times"
        );
        assert_path(&g.girf, &case["girf"], &format!("{ctx} girf"));
        assert_path(&g.lower, &case["lower"], &format!("{ctx} lower"));
        assert_path(&g.upper, &case["upper"], &format!("{ctx} upper"));
        assert_path(&g.mc_se, &case["mc_se"], &format!("{ctx} mc_se"));
        assert_path(&g.draw_sd, &case["draw_sd"], &format!("{ctx} draw_sd"));
        assert_path(
            &g.draw_lower,
            &case["draw_lower"],
            &format!("{ctx} draw_lower"),
        );
        assert_path(
            &g.draw_upper,
            &case["draw_upper"],
            &format!("{ctx} draw_upper"),
        );
        let per = case["per_history"].as_array().expect("per_history");
        assert_eq!(g.per_history.len(), per.len(), "{ctx} per_history count");
        for (i, (a, e)) in g.per_history.iter().zip(per).enumerate() {
            assert_path(a, e, &format!("{ctx} per_history[{i}]"));
        }
        for (name, actual, expected) in [
            (
                "girf_low_regime",
                &g.girf_low_regime,
                &case["girf_low_regime"],
            ),
            (
                "girf_high_regime",
                &g.girf_high_regime,
                &case["girf_high_regime"],
            ),
        ] {
            match (actual, expected.is_null()) {
                (None, true) => {}
                (Some(a), false) => assert_path(a, expected, &format!("{ctx} {name}")),
                (a, _) => panic!("{ctx} {name}: presence mismatch ({a:?} vs {expected})"),
            }
        }
        let shocks = rows(&case["shock_by_regime"]);
        for (s, (a, e)) in g.shock_by_regime.iter().zip(&shocks).enumerate() {
            for (j, (&av, &ev)) in a.iter().zip(e).enumerate() {
                close(av, ev, &format!("{ctx} shock_by_regime[{s}][{j}]"));
            }
        }
    }
}
