//! Golden-value tests for the Model Confidence Set against
//! `fixtures/mcs.json` (generated by `fixtures/generate_mcs_fixtures.py`
//! with arch 8.0.0).
//!
//! * INDEPENDENT-PACKAGE golden, EXACT — `model_confidence_set_with_indices`
//!   fed the resample indices arch's `MCS` drew: the mean losses, the
//!   elimination order, the included / excluded sets and the per-model MCS
//!   p-values are asserted exactly (bit-identical where they are doubles),
//!   and for the range method the pairwise bootstrap variance matrix at
//!   1e-13. The generator verified its transcription bit for bit against
//!   arch and certified a > 1e-9 gap around every comparison and every
//!   elimination argmax, so the exact match is guaranteed by construction.
//! * CROSS-IMPLEMENTATION — the per-step raw p-values and the observed
//!   `T_R` / `T_max` statistics, which arch does not expose, against the
//!   same transcription (p-values exact, statistics at 1e-12).
//! * Monte Carlo leg — the public seeded `model_confidence_set` at 4000
//!   replications reproduces arch's included set at 4000 replications and
//!   lands within 0.05 of every MCS p-value.

use serde_json::Value;
use tsecon_forecast::{
    model_confidence_set, model_confidence_set_with_indices, McsMethod, McsOptions, ResampleScheme,
};

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/mcs.json");
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

fn usizes(v: &Value) -> Vec<usize> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_u64().expect("integer") as usize)
        .collect()
}

fn assert_bits(actual: &[f64], expected: &[f64], ctx: &str) {
    assert_eq!(actual.len(), expected.len(), "{ctx}: length");
    for (i, (a, e)) in actual.iter().zip(expected).enumerate() {
        assert_eq!(a.to_bits(), e.to_bits(), "{ctx}[{i}]: {a:e} vs {e:e}");
    }
}

fn assert_all_close(actual: &[f64], expected: &[f64], rtol: f64, ctx: &str) {
    assert_eq!(actual.len(), expected.len(), "{ctx}: length");
    for (i, (a, e)) in actual.iter().zip(expected).enumerate() {
        let scale = e.abs().max(1.0);
        assert!(
            (a - e).abs() <= rtol * scale,
            "{ctx}[{i}]: actual {a:e}, expected {e:e} (rtol {rtol:e})"
        );
    }
}

struct Case {
    name: String,
    n: usize,
    m: usize,
    block_size: usize,
    size: f64,
    method: McsMethod,
    scheme: ResampleScheme,
    losses: Vec<Vec<f64>>,
    resamples: Vec<Vec<usize>>,
    case: Value,
}

fn cases() -> Vec<Case> {
    fixture()["cases"]
        .as_array()
        .expect("cases")
        .iter()
        .map(|c| Case {
            name: c["name"].as_str().unwrap().to_string(),
            n: c["n"].as_u64().unwrap() as usize,
            m: c["m"].as_u64().unwrap() as usize,
            block_size: c["block_size"].as_u64().unwrap() as usize,
            size: c["size"].as_f64().unwrap(),
            method: match c["method"].as_str().unwrap() {
                "R" => McsMethod::Range,
                "max" => McsMethod::Max,
                other => panic!("unknown method {other}"),
            },
            scheme: match c["bootstrap"].as_str().unwrap() {
                "stationary" => ResampleScheme::Stationary,
                "circular" => ResampleScheme::CircularBlock,
                "moving_block" => ResampleScheme::MovingBlock,
                other => panic!("unknown scheme {other}"),
            },
            losses: c["losses"].as_array().unwrap().iter().map(f64s).collect(),
            resamples: c["resamples"]
                .as_array()
                .unwrap()
                .iter()
                .map(usizes)
                .collect(),
            case: c.clone(),
        })
        .collect()
}

fn opts(c: &Case) -> McsOptions {
    McsOptions {
        size: c.size,
        method: c.method,
        block_size: Some(c.block_size),
        reps: 0,
        scheme: c.scheme,
        seed: 0,
    }
}

#[test]
fn fixture_certifies_its_gaps() {
    let fx = fixture();
    assert_eq!(fx["_meta"]["arch"].as_str().unwrap(), "8.0.0");
    let cs = cases();
    assert!(cs.len() >= 7);
    for c in &cs {
        assert!(c.case["min_gap"].as_f64().unwrap() > 1e-9, "{}", c.name);
        assert!(c.case["min_margin"].as_f64().unwrap() > 1e-9, "{}", c.name);
        assert_eq!(c.resamples.len(), 200);
        assert!(c.resamples.iter().all(|r| r.len() == c.n));
    }
    assert!(cs.iter().any(|c| c.method == McsMethod::Range));
    assert!(cs.iter().any(|c| c.method == McsMethod::Max));
}

/// A duplicated loss column is degenerate for `T_R` and NOT for `T_max`, and
/// the docs say so; this test pins both halves, plus the measurement that
/// justifies preferring either to the reference. The generator MEASURES what
/// `arch 8.0.0` does with the same input (`_meta.duplicate_columns`) rather
/// than asserting it in prose: `method="R"` warns about the 0/0 division and
/// then raises `IndexError`, `method="max"` returns nothing inside a stated
/// wall-clock and memory budget.
#[test]
fn duplicate_loss_columns_are_refused_under_t_r_and_tied_under_t_max() {
    let fx = fixture();
    let dup = &fx["_meta"]["duplicate_columns"];
    assert_eq!(dup["R"]["raises"].as_str(), Some("IndexError"));
    assert!(
        dup["R"]["warnings"]
            .as_array()
            .is_some_and(|w| w.iter().any(|x| x.as_str() == Some("RuntimeWarning"))),
        "the generator must record arch's 0/0 divide warning"
    );
    assert_eq!(dup["max"]["completed"].as_bool(), Some(false));
    assert!(dup["max"]["budget_seconds"].as_u64().unwrap() >= 30);

    // Four columns, two of them identical, so T_max's per-model standard
    // deviations stay positive and only T_R is 0/0.
    let mut s = tsecon_rng::Stream::new(4242);
    let mut col = || -> Vec<f64> { (0..120).map(|_| s.uniform_f64() + 0.25).collect() };
    let (a, b, c) = (col(), col(), col());
    let losses = vec![a, b.clone(), b, c];
    let opts = |method| McsOptions {
        size: 0.10,
        method,
        block_size: Some(4),
        reps: 200,
        scheme: ResampleScheme::Stationary,
        seed: 1,
    };

    let msg = model_confidence_set(&losses, &opts(McsMethod::Range))
        .expect_err("T_R between identical columns is 0/0 and must be refused")
        .to_string();
    assert!(
        msg.contains("model_confidence_set(method=\"R\")")
            && msg.contains("models 1 and 2")
            && msg.contains("identical"),
        "{msg}"
    );

    // T_max: well defined, and the duplicates must leave together, sharing
    // one step p-value and therefore one MCS p-value.
    let r = model_confidence_set(&losses, &opts(McsMethod::Max))
        .expect("T_max standardizes against the cross-sectional mean, so duplicates are fine");
    assert_eq!(
        r.mcs_p_values[1], r.mcs_p_values[2],
        "identical columns must get identical MCS p-values"
    );
    let (p1, p2) = (
        r.elimination_order.iter().position(|&k| k == 1).unwrap(),
        r.elimination_order.iter().position(|&k| k == 2).unwrap(),
    );
    assert_eq!(
        p1.abs_diff(p2),
        1,
        "identical columns must be eliminated in the same step: {:?}",
        r.elimination_order
    );
    assert_eq!(r.step_p_values[p1], r.step_p_values[p2]);
    assert_eq!(r.n_steps, r.statistics.len());
    assert!(r.n_steps < r.m - 1, "a tied pair must cost only one step");
}

#[test]
fn mcs_reproduces_arch_exactly_on_its_resamples() {
    for c in cases() {
        let r = model_confidence_set_with_indices(&c.losses, &c.resamples, &opts(&c))
            .unwrap_or_else(|e| panic!("{}: {e}", c.name));
        assert_eq!(r.n, c.n);
        assert_eq!(r.m, c.m);
        assert_eq!(r.reps, 200);
        assert_eq!(r.size, c.size);
        assert_eq!(r.method, c.method);
        assert_eq!(r.block_size, c.block_size);
        assert!(!r.block_size_auto);
        assert_bits(
            &r.mean_losses,
            &f64s(&c.case["mean_losses"]),
            &format!("{}: mean losses", c.name),
        );
        assert_eq!(
            r.included,
            usizes(&c.case["included"]),
            "{}: included",
            c.name
        );
        assert_eq!(
            r.excluded,
            usizes(&c.case["excluded"]),
            "{}: excluded",
            c.name
        );
        assert_eq!(
            r.elimination_order,
            usizes(&c.case["elimination_order"]),
            "{}: order",
            c.name
        );
        assert_bits(
            &r.mcs_p_values,
            &f64s(&c.case["mcs_p_values"]),
            &format!("{}: MCS p-values", c.name),
        );
        assert_bits(
            &r.step_p_values,
            &f64s(&c.case["step_p_values"]),
            &format!("{}: step p-values", c.name),
        );
        assert_all_close(
            &r.statistics,
            &f64s(&c.case["statistics"]),
            1e-12,
            &format!("{}: statistics", c.name),
        );
        assert_eq!(r.n_steps, c.case["n_steps"].as_u64().unwrap() as usize);
        assert_eq!(r.elimination_order.len(), c.m);
        assert_eq!(r.step_p_values.len(), c.m);
        // Structural identities: the MCS p-values are the running maximum
        // along the path, the sets partition the models, survivors are 1.0.
        let mut running = f64::NEG_INFINITY;
        for (&k, &p) in r.elimination_order.iter().zip(&r.step_p_values) {
            running = running.max(p);
            assert_eq!(r.mcs_p_values[k], running);
        }
        let mut all = r.included.clone();
        all.extend(&r.excluded);
        all.sort_unstable();
        assert_eq!(all, (0..c.m).collect::<Vec<_>>());
        assert!(r.step_p_values.last().copied() == Some(1.0));
        assert!(!r.included.is_empty(), "{}: the set is never empty", c.name);
        if c.name.contains("all_equal") {
            assert_eq!(
                r.included.len(),
                c.m,
                "{}: equal models all survive",
                c.name
            );
        }
    }
}

#[test]
fn seeded_mcs_matches_arch_at_monte_carlo_tolerance() {
    let tol = fixture()["_meta"]["mc_tolerance"].as_f64().unwrap();
    for c in cases() {
        let mc = &c.case["mc"];
        let reps = mc["reps"].as_u64().unwrap() as usize;
        let o = McsOptions {
            reps,
            seed: 20260911,
            ..opts(&c)
        };
        let r = model_confidence_set(&c.losses, &o).unwrap_or_else(|e| panic!("{}: {e}", c.name));
        assert_eq!(r.reps, reps);
        assert_eq!(
            r.included,
            usizes(&mc["included"]),
            "{}: MC included set",
            c.name
        );
        assert_eq!(
            r.excluded,
            usizes(&mc["excluded"]),
            "{}: MC excluded set",
            c.name
        );
        let want = f64s(&mc["mcs_p_values"]);
        for (k, (mine, theirs)) in r.mcs_p_values.iter().zip(&want).enumerate() {
            assert!(
                (mine - theirs).abs() <= tol,
                "{}: model {k} MCS p {mine} vs arch {theirs} (tol {tol})",
                c.name
            );
        }
    }
}
