//! Golden-value tests for the Reality Check / SPA test and StepM against
//! `fixtures/spa.json` (generated by `fixtures/generate_spa_fixtures.py`
//! with arch 8.0.0).
//!
//! Two legs, graded as the generator header states:
//!
//! * INDEPENDENT-PACKAGE golden, EXACT — `spa_test_with_indices` fed the
//!   resample indices arch drew, with `studentize = false` (arch's own
//!   `studentize` flag is inert, measured): the mean loss differentials, the
//!   replicate statistics, the observed statistic and the critical values
//!   are asserted BIT-identical for every case with two or more models (the
//!   generator verified the summation orders against arch bit for bit and
//!   certified a > 1e-9 gap around every comparison; the single-model case,
//!   which NumPy sums pairwise, is pinned at 1e-13), the three p-values
//!   exactly, and Hansen's kernel variances
//!   at 1e-13 (a libm `pow` inside the kernel weights is the one operation
//!   that may differ by an ulp across platforms; the nested-bootstrap
//!   variances are pure sums and are asserted bit-identical).
//!   `stepm_test_with_indices` reproduces `arch.bootstrap.StepM`'s superior
//!   set, including the cases where arch itself raises (documented in the
//!   generator).
//! * DOCUMENTED-FORMULA golden — the studentized path (Hansen 2005) against
//!   the generator's NumPy transcription on the same resamples: statistics,
//!   replicates and critical values at 1e-12 relative, p-values exact.
//!
//! Plus the Monte Carlo leg for the public seeded path: `spa_test` at 4000
//! replications lands within 0.05 of arch's p-values at 4000 replications
//! (two independent bootstraps; ~4.5 sd at p = 0.5).

use serde_json::Value;
use tsecon_forecast::{
    spa_test, spa_test_with_indices, stepm_test, stepm_test_with_indices, ResampleScheme,
    SpaOptions, StepmOptions,
};

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/spa.json");
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

fn usizes(v: &Value) -> Vec<usize> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_u64().expect("integer") as usize)
        .collect()
}

fn bools(v: &Value) -> Vec<bool> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_bool().expect("bool"))
        .collect()
}

fn columns(v: &Value) -> Vec<Vec<f64>> {
    v.as_array().expect("array").iter().map(f64s).collect()
}

fn resamples(v: &Value) -> Vec<Vec<usize>> {
    v.as_array().expect("array").iter().map(usizes).collect()
}

fn scheme(name: &str) -> ResampleScheme {
    match name {
        "stationary" => ResampleScheme::Stationary,
        "circular" => ResampleScheme::CircularBlock,
        "moving_block" => ResampleScheme::MovingBlock,
        other => panic!("unknown scheme {other}"),
    }
}

fn assert_bits(actual: &[f64], expected: &[f64], ctx: &str) {
    assert_eq!(actual.len(), expected.len(), "{ctx}: length");
    for (i, (a, e)) in actual.iter().zip(expected).enumerate() {
        assert_eq!(
            a.to_bits(),
            e.to_bits(),
            "{ctx}[{i}]: {a:e} is not bit-identical to {e:e} (diff {:e})",
            a - e
        );
    }
}

fn assert_close(actual: f64, expected: f64, rtol: f64, ctx: &str) {
    let scale = expected.abs().max(1.0);
    assert!(
        (actual - expected).abs() <= rtol * scale,
        "{ctx}: actual {actual:e}, expected {expected:e} (rtol {rtol:e})"
    );
}

fn assert_all_close(actual: &[f64], expected: &[f64], rtol: f64, ctx: &str) {
    assert_eq!(actual.len(), expected.len(), "{ctx}: length");
    for (i, (a, e)) in actual.iter().zip(expected).enumerate() {
        assert_close(*a, *e, rtol, &format!("{ctx}[{i}]"));
    }
}

/// Bit-identical where the fixture certifies NumPy's summation order is the
/// sequential one (`bit_exact`, every case with m >= 2), else 1e-13 (the
/// single-model case, which NumPy sums pairwise).
fn pin(exact: bool, actual: &[f64], expected: &[f64], ctx: &str) {
    if exact {
        assert_bits(actual, expected, ctx);
    } else {
        assert_all_close(actual, expected, 1e-13, ctx);
    }
}

struct Case {
    name: String,
    n: usize,
    m: usize,
    block_size: usize,
    nested: bool,
    scheme: ResampleScheme,
    benchmark: Vec<f64>,
    models: Vec<Vec<f64>>,
    resamples: Vec<Vec<usize>>,
    case: Value,
}

fn cases() -> Vec<Case> {
    fixture()["cases"]
        .as_array()
        .expect("cases")
        .iter()
        .map(|c| Case {
            name: c["name"].as_str().expect("name").to_string(),
            n: c["n"].as_u64().unwrap() as usize,
            m: c["m"].as_u64().unwrap() as usize,
            block_size: c["block_size"].as_u64().unwrap() as usize,
            nested: c["nested"].as_bool().unwrap(),
            scheme: scheme(c["bootstrap"].as_str().unwrap()),
            benchmark: f64s(&c["benchmark"]),
            models: columns(&c["models"]),
            resamples: resamples(&c["resamples"]),
            case: c.clone(),
        })
        .collect()
}

fn opts(c: &Case, studentize: bool) -> SpaOptions {
    SpaOptions {
        block_size: Some(c.block_size),
        reps: 0,
        scheme: c.scheme,
        studentize,
        nested: c.nested,
        seed: 0,
    }
}

#[test]
fn fixture_records_the_arch_findings_and_certifies_its_gaps() {
    let fx = fixture();
    assert_eq!(fx["_meta"]["arch"].as_str().unwrap(), "8.0.0");
    assert!(fx["_meta"]["studentize_inert"].as_bool().unwrap());
    for c in cases() {
        assert!(
            c.case["arch"]["min_gap"].as_f64().unwrap() > 1e-9,
            "{}",
            c.name
        );
        assert!(
            c.case["arch"]["recentre_margin"].as_f64().unwrap() > 1e-9,
            "{}",
            c.name
        );
        assert!(
            c.case["studentized"]["min_gap"].as_f64().unwrap() > 1e-9,
            "{}",
            c.name
        );
        assert_eq!(c.resamples.len(), 200);
        assert!(c.resamples.iter().all(|r| r.len() == c.n));
    }
    assert!(cases().len() >= 7);
}

#[test]
fn unstudentized_spa_reproduces_arch_bit_for_bit_on_its_resamples() {
    for c in cases() {
        let a = &c.case["arch"];
        let exact = a["bit_exact"].as_bool().unwrap();
        let r = spa_test_with_indices(&c.benchmark, &c.models, &c.resamples, &opts(&c, false))
            .unwrap_or_else(|e| panic!("{}: {e}", c.name));
        assert_eq!(r.n, c.n);
        assert_eq!(r.m, c.m);
        assert_eq!(r.reps, 200);
        assert_eq!(r.block_size, c.block_size);
        assert!(!r.block_size_auto);
        assert!(!r.studentize);
        assert_eq!(r.nested, c.nested);
        pin(
            exact,
            &r.mean_loss_diff,
            &f64s(&a["mean_loss_diff"]),
            &format!("{}: dbar", c.name),
        );
        let var = f64s(&a["loss_diff_var"]);
        if c.nested && exact {
            assert_bits(
                &r.loss_diff_var,
                &var,
                &format!("{}: nested variances", c.name),
            );
        } else {
            assert_all_close(
                &r.loss_diff_var,
                &var,
                1e-13,
                &format!("{}: kernel variances", c.name),
            );
        }
        assert_eq!(
            r.recentered,
            bools(&a["recentered"]),
            "{}: recentring",
            c.name
        );
        pin(
            exact,
            &[r.statistic],
            &[a["statistic"].as_f64().unwrap()],
            &format!("{}: statistic", c.name),
        );
        assert_eq!(r.best_model, a["best_model"].as_u64().unwrap() as usize);
        pin(
            exact,
            &r.boot_lower,
            &f64s(&a["boot_lower"]),
            &format!("{}: boot lower", c.name),
        );
        pin(
            exact,
            &r.boot_consistent,
            &f64s(&a["boot_consistent"]),
            &format!("{}: boot consistent", c.name),
        );
        pin(
            exact,
            &r.boot_upper,
            &f64s(&a["boot_upper"]),
            &format!("{}: boot upper", c.name),
        );
        assert_eq!(
            r.p_value_lower,
            a["p_lower"].as_f64().unwrap(),
            "{}: p lower",
            c.name
        );
        assert_eq!(
            r.p_value_consistent,
            a["p_consistent"].as_f64().unwrap(),
            "{}: p consistent",
            c.name
        );
        assert_eq!(
            r.p_value_upper,
            a["p_upper"].as_f64().unwrap(),
            "{}: p upper",
            c.name
        );
        pin(
            exact,
            &r.crit_lower,
            &f64s(&a["crit_lower"]),
            &format!("{}: crit lower", c.name),
        );
        pin(
            exact,
            &r.crit_consistent,
            &f64s(&a["crit_consistent"]),
            &format!("{}: crit consistent", c.name),
        );
        pin(
            exact,
            &r.crit_upper,
            &f64s(&a["crit_upper"]),
            &format!("{}: crit upper", c.name),
        );
        // arch's own critical values are on the mean scale: divide by sqrt(n).
        let sq = (c.n as f64).sqrt();
        for (i, alpha) in ["0.1", "0.05", "0.01"].iter().enumerate() {
            let arch_cv = f64s(&a["crit_mean_scale"][*alpha]);
            assert_close(
                r.crit_lower[i] / sq,
                arch_cv[0],
                1e-12,
                &format!("{}: arch crit lower {alpha}", c.name),
            );
            assert_close(
                r.crit_consistent[i] / sq,
                arch_cv[1],
                1e-12,
                &format!("{}: arch crit consistent {alpha}", c.name),
            );
            assert_close(
                r.crit_upper[i] / sq,
                arch_cv[2],
                1e-12,
                &format!("{}: arch crit upper {alpha}", c.name),
            );
        }
        // The replicate statistics on arch's mean scale, one sqrt(n) apart.
        let arch_boot = f64s(&a["boot_mean_scale_consistent"]);
        for (b, (mine, theirs)) in r.boot_consistent.iter().zip(&arch_boot).enumerate() {
            assert_close(
                mine / sq,
                *theirs,
                1e-14,
                &format!("{}: mean-scale replicate {b}", c.name),
            );
        }
    }
}

#[test]
fn studentized_spa_reproduces_the_hansen_transcription() {
    for c in cases() {
        let s = &c.case["studentized"];
        let r = spa_test_with_indices(&c.benchmark, &c.models, &c.resamples, &opts(&c, true))
            .unwrap_or_else(|e| panic!("{}: {e}", c.name));
        assert!(r.studentize);
        assert_all_close(
            &r.mean_loss_diff,
            &f64s(&s["mean_loss_diff"]),
            1e-13,
            &format!("{}: dbar", c.name),
        );
        assert_all_close(
            &r.loss_diff_var,
            &f64s(&s["loss_diff_var"]),
            1e-13,
            &format!("{}: variances", c.name),
        );
        assert_eq!(
            r.recentered,
            bools(&s["recentered"]),
            "{}: recentring",
            c.name
        );
        assert_close(
            r.statistic,
            s["statistic"].as_f64().unwrap(),
            1e-12,
            &format!("{}: statistic", c.name),
        );
        assert_eq!(
            r.best_model,
            s["best_model"].as_u64().unwrap() as usize,
            "{}: best",
            c.name
        );
        assert_all_close(
            &r.boot_lower,
            &f64s(&s["boot_lower"]),
            1e-12,
            &format!("{}: boot lower", c.name),
        );
        assert_all_close(
            &r.boot_consistent,
            &f64s(&s["boot_consistent"]),
            1e-12,
            &format!("{}: boot consistent", c.name),
        );
        assert_all_close(
            &r.boot_upper,
            &f64s(&s["boot_upper"]),
            1e-12,
            &format!("{}: boot upper", c.name),
        );
        assert_eq!(
            r.p_value_lower,
            s["p_lower"].as_f64().unwrap(),
            "{}: p lower",
            c.name
        );
        assert_eq!(
            r.p_value_consistent,
            s["p_consistent"].as_f64().unwrap(),
            "{}: p consistent",
            c.name
        );
        assert_eq!(
            r.p_value_upper,
            s["p_upper"].as_f64().unwrap(),
            "{}: p upper",
            c.name
        );
        assert_all_close(
            &r.crit_lower,
            &f64s(&s["crit_lower"]),
            1e-12,
            &format!("{}: crit lower", c.name),
        );
        assert_all_close(
            &r.crit_consistent,
            &f64s(&s["crit_consistent"]),
            1e-12,
            &format!("{}: crit consistent", c.name),
        );
        assert_all_close(
            &r.crit_upper,
            &f64s(&s["crit_upper"]),
            1e-12,
            &format!("{}: crit upper", c.name),
        );
        // The bounds bracket: lower <= consistent <= upper p-values.
        assert!(r.p_value_lower <= r.p_value_consistent + 1e-15);
        assert!(r.p_value_consistent <= r.p_value_upper + 1e-15);
    }
}

#[test]
fn stepm_reproduces_arch_superior_sets_and_the_transcription() {
    let mut arch_raised = 0;
    for c in cases() {
        for (studentize, block) in [(false, "stepm"), (true, "studentized")] {
            let table = if studentize {
                &c.case["studentized"]["stepm"]
            } else {
                &c.case[block]
            };
            for (key, size) in [("0.05", 0.05), ("0.1", 0.10)] {
                let want = &table[key];
                let o = StepmOptions {
                    size,
                    spa: opts(&c, studentize),
                };
                let r = stepm_test_with_indices(&c.benchmark, &c.models, &c.resamples, &o)
                    .unwrap_or_else(|e| panic!("{}: {e}", c.name));
                assert_eq!(
                    r.superior_models,
                    usizes(&want["superior_models"]),
                    "{}: superior set (studentize {studentize}, size {size})",
                    c.name
                );
                let steps: Vec<Vec<usize>> = want["steps"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(usizes)
                    .collect();
                assert_eq!(
                    r.steps, steps,
                    "{}: steps (studentize {studentize}, size {size})",
                    c.name
                );
                assert_all_close(
                    &r.step_crit_values,
                    &f64s(&want["step_crit_values"]),
                    1e-12,
                    &format!(
                        "{}: step crit (studentize {studentize}, size {size})",
                        c.name
                    ),
                );
                assert_eq!(r.size, size);
                // The full-set SPA carried inside is the SPA itself.
                let spa = spa_test_with_indices(
                    &c.benchmark,
                    &c.models,
                    &c.resamples,
                    &opts(&c, studentize),
                )
                .unwrap();
                assert_eq!(r.spa, spa, "{}: embedded SPA", c.name);
                if !studentize && want["arch_raises"].as_bool().unwrap() {
                    arch_raised += 1;
                    assert_eq!(r.superior_models.len(), c.m);
                    assert!(r.steps.len() >= 2);
                }
                // Every superior model beats the benchmark on average.
                for &k in &r.superior_models {
                    assert!(r.spa.mean_loss_diff[k] > 0.0);
                }
            }
        }
    }
    // The fixture exercises the divergence at least once.
    assert!(arch_raised >= 1, "no case exercised arch's StepM crash");
}

#[test]
fn seeded_spa_matches_arch_at_monte_carlo_tolerance() {
    let tol = fixture()["_meta"]["mc_tolerance"].as_f64().unwrap();
    for c in cases() {
        let mc = &c.case["mc"];
        let reps = mc["reps"].as_u64().unwrap() as usize;
        for (studentize, block) in [(false, "unstudentized"), (true, "studentized")] {
            let mut o = opts(&c, studentize);
            o.reps = reps;
            o.seed = 20260911;
            let r =
                spa_test(&c.benchmark, &c.models, &o).unwrap_or_else(|e| panic!("{}: {e}", c.name));
            assert_eq!(r.reps, reps);
            let want = &mc[block];
            for (mine, key) in [
                (r.p_value_lower, "p_lower"),
                (r.p_value_consistent, "p_consistent"),
                (r.p_value_upper, "p_upper"),
            ] {
                let theirs = want[key].as_f64().unwrap();
                assert!(
                    (mine - theirs).abs() <= tol,
                    "{}: {key} (studentize {studentize}) {mine} vs arch {theirs} (tol {tol})",
                    c.name
                );
            }
        }
        // StepM on the seeded path agrees with the 200-rep exact set on the
        // clear-cut cases (dominated / no-model-better).
        if c.name == "dominated_benchmark" || c.name == "no_model_better" {
            let o = StepmOptions {
                size: 0.05,
                spa: SpaOptions {
                    reps,
                    seed: 20260911,
                    ..opts(&c, false)
                },
            };
            let r = stepm_test(&c.benchmark, &c.models, &o).unwrap();
            assert_eq!(
                r.superior_models,
                usizes(&c.case["stepm"]["0.05"]["superior_models"]),
                "{}",
                c.name
            );
        }
    }
}
