//! Golden-value tests for the copula estimators against
//! `fixtures/tsecon-copula.json` (generated by
//! `fixtures/generate_tsecon-copula_fixtures.py` with statsmodels 0.14.6
//! and scipy 1.17.1).
//!
//! Tolerances per the generator header:
//!
//! * pdf/logpdf/cdf grids at 1e-10 (statsmodels analytic densities;
//!   Gaussian CDF = exact Owen's-T closed form; t CDF = scipy `quad` on
//!   the conditional representation);
//! * pseudo-observations exact (`rankdata(method="average")/(n+1)`,
//!   ties included) and Kendall tau at 1e-15 relative (same tau-b
//!   estimand and float evaluation order as scipy);
//! * tau-inversion params: closed maps at 1e-12 relative; Frank at 1e-8
//!   relative (two root-finders on two exact Debye evaluations); the t
//!   profile `nu` at 1e-6 (two polished optimizers, same 1-D maximum);
//! * MLE params at 1e-6 (absolute + relative) against the polished
//!   scipy optimum of the statsmodels log-density; our log-likelihood
//!   at *our* optimum against theirs at *their* optimum at 1e-10
//!   absolute (the honest optimizer comparison), plus one-sided
//!   never-worse; AIC/BIC at 1e-8;
//! * observed-information SEs at 1e-4 relative (same central-4 stencil
//!   with the same unit-safe steps on both sides);
//! * tau maps and tail-dependence closed forms at 1e-10 (Frank tau at
//!   1e-11 absolute — our Bernoulli-series Debye vs the generator's
//!   quad Debye).

use serde_json::Value;
use tsecon_copula::{
    copula_cdf, copula_fit, copula_logpdf, copula_pdf, copula_select, kendall_tau, param_to_tau,
    pseudo_obs, tail_dependence, tau_to_param, Family, FitMethod,
};

fn fixture() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/tsecon-copula.json"
    );
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

/// Combined absolute+relative comparison (numpy `allclose` semantics).
fn assert_close(actual: f64, expected: f64, atol: f64, rtol: f64, ctx: &str) {
    let tol = atol + rtol * expected.abs();
    assert!(
        (actual - expected).abs() <= tol,
        "{ctx}: actual {actual}, expected {expected}, |diff| {:e} > {tol:e}",
        (actual - expected).abs()
    );
}

fn family(name: &str) -> Family {
    Family::parse(name).expect("family parses")
}

#[test]
fn pseudo_obs_matches_scipy_rankdata_with_ties() {
    let fx = fixture();
    let po = &fx["pseudo_obs"];
    let x1 = f64s(&po["x1"]);
    let x2 = f64s(&po["x2"]);
    let u = pseudo_obs(&[x1, x2]).expect("pseudo_obs");
    let u1_ref = f64s(&po["u1"]);
    let u2_ref = f64s(&po["u2"]);
    for i in 0..u1_ref.len() {
        assert_close(u[0][i], u1_ref[i], 0.0, 1e-15, &format!("u1[{i}]"));
        assert_close(u[1][i], u2_ref[i], 0.0, 1e-15, &format!("u2[{i}]"));
    }
}

#[test]
fn density_and_cdf_grids_match_statsmodels() {
    let fx = fixture();
    for (fam_name, entries) in fx["grids"].as_object().expect("grids") {
        let fam = family(fam_name);
        for entry in entries.as_array().expect("entries") {
            let params = f64s(&entry["params"]);
            let u1 = f64s(&entry["u1"]);
            let u2 = f64s(&entry["u2"]);
            let ctx = format!("{fam_name} params={params:?}");
            let lp = copula_logpdf(&u1, &u2, fam, &params).expect("logpdf");
            let p = copula_pdf(&u1, &u2, fam, &params).expect("pdf");
            let c = copula_cdf(&u1, &u2, fam, &params).expect("cdf");
            let lp_ref = f64s(&entry["logpdf"]);
            let p_ref = f64s(&entry["pdf"]);
            let c_ref = f64s(&entry["cdf"]);
            for i in 0..u1.len() {
                assert_close(
                    lp[i],
                    lp_ref[i],
                    1e-10,
                    1e-10,
                    &format!("{ctx}: logpdf[{i}]"),
                );
                assert_close(p[i], p_ref[i], 1e-10, 1e-10, &format!("{ctx}: pdf[{i}]"));
                assert_close(c[i], c_ref[i], 1e-10, 0.0, &format!("{ctx}: cdf[{i}]"));
            }
        }
    }
}

#[test]
fn tau_param_maps_match_closed_forms() {
    let fx = fixture();
    for (fam_name, maps) in fx["maps"].as_object().expect("maps") {
        let fam = family(fam_name);
        for pair in maps["tau_to_param"].as_array().expect("t2p") {
            let row = f64s(pair);
            let (tau, param_ref) = (row[0], row[1]);
            let param = tau_to_param(fam, tau).expect("tau_to_param");
            let rtol = if fam == Family::Frank { 1e-8 } else { 1e-12 };
            assert_close(
                param,
                param_ref,
                0.0,
                rtol,
                &format!("{fam_name}: tau_to_param({tau})"),
            );
        }
        for pair in maps["param_to_tau"].as_array().expect("p2t") {
            let row = f64s(pair);
            let (param, tau_ref) = (row[0], row[1]);
            let params: Vec<f64> = if fam == Family::StudentT {
                vec![param, 5.0]
            } else {
                vec![param]
            };
            let tau = param_to_tau(fam, &params).expect("param_to_tau");
            assert_close(
                tau,
                tau_ref,
                1e-11,
                1e-11,
                &format!("{fam_name}: param_to_tau({param})"),
            );
            // Frank rows also record statsmodels' own tau_frank value —
            // the reference package agrees with the exact Debye value
            // (and with us) at its measured 5e-12.
            if fam == Family::Frank && row.len() > 2 {
                assert_close(
                    tau,
                    row[2],
                    5e-12,
                    0.0,
                    &format!("frank: statsmodels tau_frank({param})"),
                );
            }
        }
    }
}

#[test]
fn tail_dependence_matches_closed_forms() {
    let fx = fixture();
    for (fam_name, entries) in fx["tails"].as_object().expect("tails") {
        let fam = family(fam_name);
        for entry in entries.as_array().expect("entries") {
            let params = f64s(&entry["params"]);
            let t_ref = f64s(&entry["tail"]);
            let (lo, up) = tail_dependence(fam, &params).expect("tails");
            let ctx = format!("{fam_name} params={params:?}");
            assert_close(lo, t_ref[0], 1e-10, 1e-10, &format!("{ctx}: lower"));
            assert_close(up, t_ref[1], 1e-10, 1e-10, &format!("{ctx}: upper"));
        }
    }
}

#[test]
fn t_tail_dependence_pins_the_correct_form_not_statsmodels_bug() {
    // statsmodels 0.14.6 StudentTCopula.dependence_tail has an
    // operator-precedence bug; the generator verified the correct
    // Demarta-McNeil form by the numeric copula limit and recorded both
    // values. Pin ours to the correct one and assert it is far from the
    // buggy one, so this documented defect stays visible.
    let fx = fixture();
    let bug = &fx["_meta"]["statsmodels_t_tail_bug"];
    let rho = bug["rho"].as_f64().expect("rho");
    let nu = bug["nu"].as_f64().expect("nu");
    let correct = bug["correct_value"].as_f64().expect("correct");
    let buggy = bug["statsmodels_value"].as_f64().expect("buggy");
    let (lo, up) = tail_dependence(Family::StudentT, &[rho, nu]).expect("tails");
    assert_close(lo, correct, 0.0, 1e-12, "t tail (lower)");
    assert_close(up, correct, 0.0, 1e-12, "t tail (upper)");
    assert!(
        (lo - buggy).abs() > 0.1,
        "ours {lo} should be far from statsmodels' buggy {buggy}"
    );
}

#[test]
fn fits_match_statsmodels_and_polished_scipy_mle() {
    let fx = fixture();
    for ds in fx["fits"].as_array().expect("fits") {
        let name = ds["name"].as_str().expect("name");
        let u1 = f64s(&ds["u1"]);
        let u2 = f64s(&ds["u2"]);

        // The real-data case stores the raw margins too: our pseudo_obs
        // must reproduce the stored u exactly (ties included).
        if !ds["x1"].is_null() {
            let x1 = f64s(&ds["x1"]);
            let x2 = f64s(&ds["x2"]);
            let u = pseudo_obs(&[x1, x2]).expect("pseudo_obs");
            for i in 0..u1.len() {
                assert_close(u[0][i], u1[i], 0.0, 1e-15, &format!("{name}: po u1[{i}]"));
                assert_close(u[1][i], u2[i], 0.0, 1e-15, &format!("{name}: po u2[{i}]"));
            }
        }

        let tau_ref = ds["tau"].as_f64().expect("tau");
        let tau = kendall_tau(&u1, &u2).expect("tau");
        assert_close(tau, tau_ref, 0.0, 1e-15, &format!("{name}: kendall tau"));

        for case in ds["cases"].as_array().expect("cases") {
            let fam = family(case["family"].as_str().expect("family"));
            let method =
                FitMethod::parse(case["method"].as_str().expect("method")).expect("method parses");
            let ctx = format!("{name}/{}/{}", fam.name(), method.name());
            let fit = copula_fit(&u1, &u2, fam, method).expect("copula_fit");
            let params_ref = f64s(&case["params"]);
            assert_eq!(fit.params.len(), params_ref.len(), "{ctx}: k");

            match method {
                FitMethod::Tau => {
                    // Closed-map params exactly; Frank via root-finders;
                    // the t profile nu as two polished optimizers.
                    for (i, (&p, &r)) in fit.params.iter().zip(&params_ref).enumerate() {
                        let rtol = match (fam, i) {
                            (Family::Frank, _) => 1e-8,
                            (Family::StudentT, 1) => 1e-6,
                            _ => 1e-12,
                        };
                        assert_close(p, r, 0.0, rtol, &format!("{ctx}: params[{i}]"));
                    }
                    assert!(
                        fit.se.iter().all(|s| s.is_nan()) && !fit.se_valid,
                        "{ctx}: tau method must report NaN, uncertified SEs"
                    );
                    // Same params => same likelihood (evaluation only).
                    let ll_ref = case["loglik"].as_f64().expect("ll");
                    let atol = if fam == Family::StudentT || fam == Family::Frank {
                        1e-5 // first-order in the tiny param gap
                    } else {
                        1e-8
                    };
                    assert_close(fit.loglik, ll_ref, atol, 0.0, &format!("{ctx}: loglik"));
                }
                FitMethod::Mle => {
                    for (i, (&p, &r)) in fit.params.iter().zip(&params_ref).enumerate() {
                        assert_close(p, r, 1e-6, 1e-6, &format!("{ctx}: params[{i}]"));
                    }
                    let ll_ref = case["loglik"].as_f64().expect("ll");
                    assert!(
                        fit.loglik >= ll_ref - 1e-10,
                        "{ctx}: our optimum is worse: {} < {ll_ref}",
                        fit.loglik
                    );
                    assert_close(fit.loglik, ll_ref, 1e-10, 0.0, &format!("{ctx}: loglik"));
                    assert!(fit.converged, "{ctx}: did not converge");
                    let se_ref = f64s(&case["se"]);
                    assert!(fit.se_valid, "{ctx}: SEs should be certified here");
                    for (i, (&s, &r)) in fit.se.iter().zip(&se_ref).enumerate() {
                        assert_close(s, r, 0.0, 1e-4, &format!("{ctx}: se[{i}]"));
                    }
                }
            }

            assert_close(
                fit.aic,
                case["aic"].as_f64().expect("aic"),
                1e-5,
                1e-8,
                &format!("{ctx}: aic"),
            );
            assert_close(
                fit.bic,
                case["bic"].as_f64().expect("bic"),
                1e-5,
                1e-8,
                &format!("{ctx}: bic"),
            );
            assert_close(
                fit.tau_implied,
                case["tau_implied"].as_f64().expect("tau_implied"),
                1e-6,
                1e-6,
                &format!("{ctx}: tau_implied"),
            );
            let tail_ref = f64s(&case["tail"]);
            assert_close(
                fit.tail_lower,
                tail_ref[0],
                1e-6,
                1e-4,
                &format!("{ctx}: tail_lower"),
            );
            assert_close(
                fit.tail_upper,
                tail_ref[1],
                1e-6,
                1e-4,
                &format!("{ctx}: tail_upper"),
            );
        }

        // Selection: the same family list, ranked by AIC, must crown the
        // winner the generator asserted (the simulated family).
        let fams: Vec<Family> = ds["cases"]
            .as_array()
            .expect("cases")
            .iter()
            .filter(|c| c["method"].as_str() == Some("mle"))
            .map(|c| family(c["family"].as_str().expect("family")))
            .collect();
        let sel = copula_select(&u1, &u2, &fams, FitMethod::Mle).expect("select");
        let best = sel.fits[sel.best_aic].family.name();
        assert_eq!(
            best,
            ds["best_aic"].as_str().expect("best_aic"),
            "{name}: AIC winner"
        );
        assert!(!sel.verdict.is_empty(), "{name}: verdict text");
        assert!(
            sel.verdict.contains(best),
            "{name}: verdict names the winner"
        );
    }
}
