//! # tsecon-quantile — quantile regression, quantile LPs, growth-at-risk
//!
//! Estimators for *conditional quantiles* of a time series: the linear
//! quantile regression minimizing the check loss
//!
//! ```text
//! rho_tau(u) = u * (tau - 1{u < 0}),
//! ```
//!
//! its per-horizon local-projection form (the check-loss analogue of the
//! Jordà LP), and the Adrian-Boyarchenko-Giannone (2019 AER) growth-at-risk
//! workflow — conditional quantiles of `h`-ahead growth given current
//! financial conditions, with the Chernozhukov-Fernandez-Val-Galichon (2010)
//! monotone rearrangement to repair quantile crossings.
//!
//! ## Method
//!
//! Point estimates use the Schnabel-Koenker iteratively reweighted least
//! squares that statsmodels' `QuantReg` uses (a `1e-6` residual smoothing
//! floor, convergence on a `1e-6` maximum coefficient change, 1000-iteration
//! cap), with every weighted least-squares step delegated to
//! [`tsecon_hac::ols`] — the library's single OLS owner. Standard errors are
//! the Powell (1991) kernel sandwich `(X'X)^{-1} X'DX (X'X)^{-1}` whose
//! density-at-zero estimate uses an Epanechnikov kernel with the
//! Hall-Sheather (1988) bandwidth (statsmodels' `vcov="robust"` defaults).
//!
//! ## Module map
//!
//! - [`quantile_regression`] / [`QuantileFit`]: linear quantile regression
//!   at one or many taus — coefficients, Powell-sandwich `bse`, `tvalues`,
//!   covariance, bandwidth, and sparsity `1/f(0)`.
//! - [`quantile_lp`] / [`QuantileLp`]: per-horizon quantile local
//!   projections of `y` on a shock with lagged `y` and shock controls,
//!   in `tsecon-lp`'s design column order
//!   `[shock_t, const, y_{t-1..t-p}, shock_{t-1..t-p}]`; returns
//!   `irf[tau][h]` and `se[tau][h]`.
//! - [`growth_at_risk`] / [`GrowthAtRisk`]: conditional quantiles of the
//!   `h`-ahead outcome on `[const, conditions, y_t]`, fitted at every
//!   observation (the last is the current risk read), with optional
//!   rearrangement and a `crossing` report.
//! - [`QuantileError`]: the shared "errors that teach" enum.
//!
//! ## Validation
//!
//! `fixtures/tsecon-quantile.json` (generated by
//! `fixtures/generate_tsecon-quantile_fixtures.py`, statsmodels 0.14.6) pins:
//!
//! - quantile-regression coefficients to 1e-6 (the shared IRLS `p_tol`
//!   stopping tolerance) and robust `bse`, `bandwidth`, `sparsity` to 1e-6
//!   relative, across heteroskedastic-normal, Student-t(3), and skewed
//!   chi-square DGPs at taus from 0.05 to 0.95;
//! - quantile-LP `irf` and `se` per (tau, horizon) against statsmodels
//!   `QuantReg` on the identical numpy-assembled design;
//! - growth-at-risk coefficients, `bse`, raw and rearranged fitted quantile
//!   paths, the crossing flag, and the current risk read — one case where
//!   raw quantiles genuinely cross, so the rearrangement is pinned doing
//!   real work.
//!
//! Seeded Monte-Carlo property tests establish the statistical claims:
//! perturbing the coefficients raises the in-sample check loss, the fitted
//! tau = 0.5 line is the LAD/median fit, quantile-LP at the median tracks
//! the least-squares LP under symmetric errors, rearranged quantile curves
//! are monotone, and in a location-scale DGP the lower quantiles respond
//! more to a variance-shifting condition than the median (the ABG stylized
//! fact, by construction).
//!
//! ```
//! use tsecon_quantile::{growth_at_risk, quantile_regression};
//!
//! let x: Vec<f64> = (0..80).map(|t| (t as f64 * 0.7).sin()).collect();
//! let y: Vec<f64> = x.iter().enumerate().map(|(t, &v)| 0.5 * v + (t % 7) as f64 * 0.1).collect();
//! let cols = vec![vec![1.0; 80], x.clone()];
//!
//! let fits = quantile_regression(&y, &cols, &[0.25, 0.5, 0.75]).unwrap();
//! assert_eq!(fits.len(), 3);
//!
//! let gar = growth_at_risk(&y, &[x], 1, &[0.05, 0.5, 0.95], true).unwrap();
//! assert!(gar.current[0] <= gar.current[2]); // rearranged: never crossing
//! ```

#![warn(missing_docs)]
#![warn(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod error;
mod gar;
mod lp;
mod qreg;

pub use error::QuantileError;
pub use gar::{growth_at_risk, GrowthAtRisk};
pub use lp::{quantile_lp, QuantileLp};
pub use qreg::{quantile_regression, QuantileFit};
