//! Golden-value tests for the Hansen-Seo threshold VECM fit and the
//! sup-LM statistic against `fixtures/tvecm.json` (generated by
//! `fixtures/generate_tvecm_fixtures.py`).
//!
//! The reference is a documented-ALGORITHM transcription: an independent
//! dense NumPy implementation of the Hansen-Seo (2002) grid estimator and
//! sup-LM statistic, not a third-party library (no reference runs in this
//! container — the generator header states the grading honestly).
//! Tolerances: fixed-`beta` cases at 1e-10 relative (the concentrated
//! scan is deterministic algebra); estimated-`beta` cases at 1e-8 (the
//! Johansen eigensolver — scipy there, faer here — enters the anchor).
//! Counts exact. The bootstrap p-value is a Monte Carlo quantity and is
//! deliberately NOT pinned — see `tvecm_properties.rs`.

use serde_json::Value;
use tsecon_coint::tsecon_linalg::faer::Mat;
use tsecon_coint::{hansen_seo_test, threshold_vecm};

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/tvecm.json");
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

fn f64mat(v: &Value) -> Vec<Vec<f64>> {
    v.as_array().expect("matrix").iter().map(f64s).collect()
}

fn series_mat(v: &Value) -> Mat<f64> {
    let rows = f64mat(v);
    Mat::from_fn(rows.len(), rows[0].len(), |i, j| rows[i][j])
}

/// Relative comparison; falls back to absolute when the reference is 0.
fn assert_close(actual: f64, expected: f64, rtol: f64, ctx: &str) {
    if expected == 0.0 {
        assert!(
            actual.abs() <= rtol,
            "{ctx}: actual {actual}, expected 0 (atol {rtol})"
        );
    } else {
        let rel = ((actual - expected) / expected).abs();
        assert!(
            rel <= rtol,
            "{ctx}: actual {actual}, expected {expected}, rel err {rel:e} > {rtol:e}"
        );
    }
}

fn assert_vec_close(actual: &[f64], expected: &[f64], rtol: f64, ctx: &str) {
    assert_eq!(actual.len(), expected.len(), "{ctx} length");
    for (i, (&a, &e)) in actual.iter().zip(expected).enumerate() {
        assert_close(a, e, rtol, &format!("{ctx}[{i}]"));
    }
}

fn assert_mat_close(actual: &[Vec<f64>], expected: &[Vec<f64>], rtol: f64, ctx: &str) {
    assert_eq!(actual.len(), expected.len(), "{ctx} rows");
    for (i, (a, e)) in actual.iter().zip(expected).enumerate() {
        assert_vec_close(a, e, rtol, &format!("{ctx}[{i}]"));
    }
}

#[test]
fn tvecm_fit_matches_numpy_transcription() {
    let fx = fixture();
    let series = &fx["series"];
    for case in fx["fit"].as_array().expect("fit cases") {
        let name = case["series"].as_str().expect("series");
        let l = case["k_ar_diff"].as_u64().expect("k_ar_diff") as usize;
        let trim = case["trim"].as_f64().expect("trim");
        let ngg = case["n_grid_gamma"].as_u64().expect("n_grid_gamma") as usize;
        let ngb = case["n_grid_beta"].as_u64().expect("n_grid_beta") as usize;
        let span = case["beta_span"].as_f64().expect("beta_span");
        let beta_fixed: Option<Vec<f64>> = if case["beta_fixed"].is_null() {
            None
        } else {
            Some(f64s(&case["beta_fixed"]))
        };
        let tol = case["tol"].as_f64().expect("tol");
        let ctx = format!(
            "fit[{name}/l={l}/trim={trim}/fixed={}]",
            beta_fixed.is_some()
        );

        let y = series_mat(&series[name]);
        let r = threshold_vecm(y.as_ref(), l, trim, ngg, ngb, span, beta_fixed.as_deref())
            .expect("threshold_vecm runs");

        assert_vec_close(&r.beta, &f64s(&case["beta"]), tol, &format!("{ctx} beta"));
        assert_close(
            r.threshold,
            case["threshold"].as_f64().expect("threshold"),
            tol,
            &format!("{ctx} threshold"),
        );
        assert_mat_close(
            &r.coefs_low,
            &f64mat(&case["coefs_low"]),
            tol,
            &format!("{ctx} coefs_low"),
        );
        assert_mat_close(
            &r.coefs_high,
            &f64mat(&case["coefs_high"]),
            tol,
            &format!("{ctx} coefs_high"),
        );
        assert_mat_close(
            &r.se_low,
            &f64mat(&case["se_low"]),
            tol,
            &format!("{ctx} se_low"),
        );
        assert_mat_close(
            &r.se_high,
            &f64mat(&case["se_high"]),
            tol,
            &format!("{ctx} se_high"),
        );
        assert_eq!(
            r.n_low,
            case["n_low"].as_u64().expect("n_low") as usize,
            "{ctx} n_low"
        );
        assert_eq!(
            r.n_high,
            case["n_high"].as_u64().expect("n_high") as usize,
            "{ctx} n_high"
        );
        assert_eq!(
            r.nobs,
            case["nobs"].as_u64().expect("nobs") as usize,
            "{ctx} nobs"
        );
        assert_close(
            r.frac_low,
            case["frac_low"].as_f64().expect("frac_low"),
            tol,
            &format!("{ctx} frac_low"),
        );
        assert_mat_close(
            &r.sigma,
            &f64mat(&case["sigma"]),
            tol,
            &format!("{ctx} sigma"),
        );
        assert_close(
            r.log_det_sigma,
            case["log_det_sigma"].as_f64().expect("log_det_sigma"),
            tol,
            &format!("{ctx} log_det_sigma"),
        );
        assert_close(
            r.llf,
            case["llf"].as_f64().expect("llf"),
            tol,
            &format!("{ctx} llf"),
        );
        assert_close(
            r.llf_linear,
            case["llf_linear"].as_f64().expect("llf_linear"),
            1e-8, // eigen-based here vs OLS-based there: analytically equal
            &format!("{ctx} llf_linear"),
        );
        assert_vec_close(
            &r.beta_linear,
            &f64s(&case["beta_linear"]),
            tol,
            &format!("{ctx} beta_linear"),
        );
        assert_vec_close(
            &r.beta_grid,
            &f64s(&case["beta_grid"]),
            tol,
            &format!("{ctx} beta_grid"),
        );
        assert_eq!(
            r.min_regime,
            case["min_regime"].as_u64().expect("min_regime") as usize,
            "{ctx} min_regime"
        );
        assert_eq!(
            r.n_regressors,
            case["n_regressors"].as_u64().expect("n_regressors") as usize,
            "{ctx} n_regressors"
        );
    }
}

#[test]
fn hansen_seo_statistic_matches_numpy_transcription() {
    let fx = fixture();
    let series = &fx["series"];
    for case in fx["test"].as_array().expect("test cases") {
        let name = case["series"].as_str().expect("series");
        let l = case["k_ar_diff"].as_u64().expect("k_ar_diff") as usize;
        let trim = case["trim"].as_f64().expect("trim");
        let ng = case["n_grid"].as_u64().expect("n_grid") as usize;
        let beta_fixed: Option<Vec<f64>> = if case["beta_fixed"].is_null() {
            None
        } else {
            Some(f64s(&case["beta_fixed"]))
        };
        let tol = case["tol"].as_f64().expect("tol");
        let ctx = format!(
            "supLM[{name}/l={l}/trim={trim}/fixed={}]",
            beta_fixed.is_some()
        );

        let y = series_mat(&series[name]);
        // A tiny n_boot: only the observed statistic is pinned here.
        let r = hansen_seo_test(y.as_ref(), l, trim, ng, 9, 0, beta_fixed.as_deref())
            .expect("hansen_seo_test runs");

        assert_close(
            r.stat,
            case["stat"].as_f64().expect("stat"),
            tol,
            &format!("{ctx} stat"),
        );
        assert_close(
            r.threshold,
            case["threshold"].as_f64().expect("threshold"),
            tol,
            &format!("{ctx} threshold"),
        );
        assert_vec_close(&r.beta, &f64s(&case["beta"]), tol, &format!("{ctx} beta"));
        assert_eq!(
            r.nobs,
            case["nobs"].as_u64().expect("nobs") as usize,
            "{ctx} nobs"
        );
        assert_eq!(
            r.min_regime,
            case["min_regime"].as_u64().expect("min_regime") as usize,
            "{ctx} min_regime"
        );
        assert_eq!(
            r.n_regressors,
            case["n_regressors"].as_u64().expect("n_regressors") as usize,
            "{ctx} n_regressors"
        );
        assert_vec_close(
            &r.thresholds,
            &f64s(&case["thresholds"]),
            tol,
            &format!("{ctx} thresholds"),
        );
        assert_vec_close(
            &r.lm_path,
            &f64s(&case["lm_path"]),
            tol,
            &format!("{ctx} lm_path"),
        );
        assert_eq!(r.boot_stats.len(), 9, "{ctx} boot draws");
        assert!(
            r.p_value > 0.0 && r.p_value <= 1.0,
            "{ctx} p_value in (0, 1]"
        );
    }
}
