//! Golden-value tests for the preprocessing advisors against
//! `fixtures/advisors.json` (generated by
//! `fixtures/generate_advisors_fixtures.py`).
//!
//! What each block is graded against, and the tolerance actually achieved:
//!
//! * `ndiffs` per-order evidence -> statsmodels 0.14.6 `kpss` / `adfuller`
//!   and arch 8.0.0 `PhillipsPerron`. Third-party golden. `d`, the stop
//!   reason, the number of steps, the lag/bandwidth and the per-step
//!   decision are **exact**; statistics agree to `3.2e-13` relative and
//!   p-values to `7.4e-14` (asserted at `1e-11`).
//! * `ndiffs` sequential rule -> transcribed from Hyndman & Khandakar
//!   (2008) / `forecast::ndiffs`; no third-party implementation exists in
//!   the reference venv, so the *rule* is a documented-rule golden while
//!   the numbers it consumes are third-party.
//! * `box_cox_llf` -> `scipy.stats.boxcox_llf` on a lambda grid. Strong
//!   third-party golden: `6.8e-16` relative (asserted at `1e-13`).
//! * `box_cox_lambda(Mle)` -> `scipy.optimize.minimize_scalar(-boxcox_llf,
//!   method="bounded", xatol=1e-12)` and `scipy.stats.boxcox_normmax`.
//!   Lambda agrees to `1.2e-7` absolute (asserted at `1e-6`) — that is the
//!   `sqrt(eps)` resolution limit for locating a smooth maximum in f64,
//!   not a disagreement about the answer: the log-likelihood *at* the two
//!   lambdas agrees to `5e-11` relative (asserted at `1e-9`), and
//!   `l(0)` / `l(1)` agree to `4e-16`.
//! * `guerrero_cv` and `box_cox_lambda(Guerrero)` -> an independent NumPy
//!   transcription of Guerrero (1993) in the generator (no third-party
//!   implementation is available in the reference venv, so this is a
//!   **documented-formula** golden, graded as such). The criterion agrees
//!   to `6.6e-16` relative on the grid, the optimising lambda to `5.6e-8`.

use serde_json::Value;
use tsecon_diag::{box_cox_lambda, box_cox_llf, guerrero_cv, ndiffs, BoxCoxMethod, NdiffsTest};

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/advisors.json");
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

fn usize_of(v: &Value) -> usize {
    v.as_u64().expect("unsigned integer") as usize
}

/// Relative comparison; falls back to absolute when the reference is 0.
fn assert_close(actual: f64, expected: f64, rtol: f64, ctx: &str) {
    if expected == 0.0 {
        assert!(
            actual.abs() <= rtol,
            "{ctx}: actual {actual}, expected 0 (atol {rtol})"
        );
    } else {
        let rel = ((actual - expected) / expected).abs();
        assert!(
            rel <= rtol,
            "{ctx}: actual {actual}, expected {expected}, rel err {rel:e} > {rtol:e}"
        );
    }
}

/// Combined absolute+relative comparison (numpy `allclose` semantics).
fn assert_pclose(actual: f64, expected: f64, atol: f64, rtol: f64, ctx: &str) {
    let tol = atol + rtol * expected.abs();
    assert!(
        (actual - expected).abs() <= tol,
        "{ctx}: actual {actual}, expected {expected}, |diff| {:e} > {tol:e}",
        (actual - expected).abs()
    );
}

fn ndiffs_test(code: &str) -> NdiffsTest {
    match code {
        "kpss" => NdiffsTest::Kpss,
        "adf" => NdiffsTest::Adf,
        "pp" => NdiffsTest::Pp,
        other => panic!("unknown ndiffs test {other:?}"),
    }
}

// ------------------------------------------------------------------ ndiffs

#[test]
fn ndiffs_matches_the_reference_sequence_and_evidence() {
    let fx = fixture();
    let cases = fx["ndiffs"].as_array().expect("ndiffs cases");
    assert!(!cases.is_empty(), "fixture has ndiffs cases");

    for case in cases {
        let name = case["series"].as_str().expect("series name");
        let code = case["test"].as_str().expect("test code");
        let alpha = case["alpha"].as_f64().expect("alpha");
        let max_d = usize_of(&case["max_d"]);
        let ctx = format!("ndiffs[{name}/{code}/alpha={alpha}/max_d={max_d}]");

        let y = f64s(&fx["ndiffs_series"][name]);
        let got = ndiffs(&y, ndiffs_test(code), alpha, max_d).expect("ndiffs succeeds");

        assert_eq!(got.d, usize_of(&case["d"]), "{ctx}: d");
        assert_eq!(
            format!("{:?}", got.stop),
            case["reason"].as_str().expect("reason"),
            "{ctx}: stop reason"
        );

        let steps = case["steps"].as_array().expect("steps");
        assert_eq!(got.steps.len(), steps.len(), "{ctx}: number of steps");
        for (k, (got_step, want)) in got.steps.iter().zip(steps).enumerate() {
            let sctx = format!("{ctx} step {k}");
            assert_eq!(got_step.d, usize_of(&want["d"]), "{sctx}: order");
            assert_eq!(got_step.n, usize_of(&want["n"]), "{sctx}: nobs");
            assert_eq!(got_step.lags, usize_of(&want["lags"]), "{sctx}: lags");
            assert_eq!(
                got_step.needs_differencing,
                want["needs_differencing"].as_bool().expect("decision"),
                "{sctx}: decision"
            );
            assert_close(
                got_step.statistic,
                want["stat"].as_f64().expect("stat"),
                1e-11,
                &format!("{sctx}: statistic"),
            );
            assert_pclose(
                got_step.p_value,
                want["p"].as_f64().expect("p"),
                1e-12,
                1e-11,
                &format!("{sctx}: p-value"),
            );
        }

        // The evidence must cover every order that was tried, in order.
        for (k, s) in got.steps.iter().enumerate() {
            assert_eq!(s.d, k, "{ctx}: steps are ordered 0..=d");
        }
    }
}

// ---------------------------------------------------------------- box-cox

#[test]
fn box_cox_llf_matches_scipy_on_the_lambda_grid() {
    let fx = fixture();
    let grids = fx["boxcox_llf"].as_array().expect("llf grids");
    assert!(!grids.is_empty(), "fixture has llf grids");

    for grid in grids {
        let name = grid["series"].as_str().expect("series name");
        let y = f64s(&fx["boxcox_series"][name]);
        let lambdas = f64s(&grid["lambdas"]);
        let llf = f64s(&grid["llf"]);
        for (lambda, expected) in lambdas.iter().zip(&llf) {
            let got = box_cox_llf(&y, *lambda).expect("llf succeeds");
            assert_close(
                got,
                *expected,
                1e-13,
                &format!("box_cox_llf[{name}, lambda = {lambda}]"),
            );
        }
    }
}

#[test]
fn box_cox_lambda_mle_matches_scipy() {
    let fx = fixture();
    for case in fx["boxcox_mle"].as_array().expect("mle cases") {
        let name = case["series"].as_str().expect("series name");
        let lower = case["lower"].as_f64().expect("lower");
        let upper = case["upper"].as_f64().expect("upper");
        let ctx = format!("box_cox_lambda[mle, {name}, ({lower}, {upper})]");
        let y = f64s(&fx["boxcox_series"][name]);

        let got = box_cox_lambda(&y, BoxCoxMethod::Mle, (lower, upper)).expect("mle succeeds");

        // Lambda: sqrt(eps)-limited, so an absolute tolerance.
        assert_pclose(
            got.lambda,
            case["lambda_bounded"].as_f64().expect("lambda"),
            1e-6,
            0.0,
            &format!("{ctx}: lambda vs SciPy's bounded optimum"),
        );
        // The likelihood at the optimum is what the tolerance really is.
        assert_close(
            got.objective,
            case["llf_at_opt"].as_f64().expect("llf"),
            1e-9,
            &format!("{ctx}: log-likelihood at the optimum"),
        );
        assert_close(
            got.loglik_at_zero.expect("mle reports l(0)"),
            case["llf_at_zero"].as_f64().expect("llf0"),
            1e-13,
            &format!("{ctx}: log-likelihood of the log transform"),
        );
        assert_close(
            got.loglik_at_one.expect("mle reports l(1)"),
            case["llf_at_one"].as_f64().expect("llf1"),
            1e-13,
            &format!("{ctx}: log-likelihood of no transform"),
        );
        assert_eq!(
            got.at_bound,
            case["at_bound"].as_bool().expect("at_bound"),
            "{ctx}: at_bound flag"
        );
        assert_eq!(got.n, f64s(&fx["boxcox_series"][name]).len(), "{ctx}: n");

        // The likelihood-ratio fields are exactly the definition.
        assert_close(
            got.lr_vs_zero.expect("lr0"),
            2.0 * (got.objective - got.loglik_at_zero.expect("l0")),
            1e-15,
            &format!("{ctx}: LR against the log"),
        );
        assert_close(
            got.lr_vs_one.expect("lr1"),
            2.0 * (got.objective - got.loglik_at_one.expect("l1")),
            1e-15,
            &format!("{ctx}: LR against no transform"),
        );

        // SciPy's public entry point (unbounded Brent from brack = (-2, 2))
        // must agree too whenever the optimum is interior.
        if !got.at_bound {
            assert_pclose(
                got.lambda,
                case["lambda_normmax"].as_f64().expect("normmax"),
                1e-6,
                0.0,
                &format!("{ctx}: lambda vs scipy.stats.boxcox_normmax"),
            );
        }
    }
}

// --------------------------------------------------------------- guerrero

#[test]
fn guerrero_criterion_matches_the_transcribed_formula() {
    let fx = fixture();
    let grids = fx["guerrero_cv"].as_array().expect("guerrero grids");
    assert!(!grids.is_empty(), "fixture has guerrero grids");

    for grid in grids {
        let name = grid["series"].as_str().expect("series name");
        let period = usize_of(&grid["period"]);
        let y = f64s(&fx["boxcox_series"][name]);
        for (lambda, expected) in f64s(&grid["lambdas"]).iter().zip(f64s(&grid["cv"])) {
            let got = guerrero_cv(&y, *lambda, period).expect("cv succeeds");
            assert_close(
                got,
                expected,
                1e-13,
                &format!("guerrero_cv[{name}, period = {period}, lambda = {lambda}]"),
            );
        }
    }
}

#[test]
fn box_cox_lambda_guerrero_matches_the_transcribed_optimum() {
    let fx = fixture();
    for case in fx["guerrero_opt"].as_array().expect("guerrero optima") {
        let name = case["series"].as_str().expect("series name");
        let period = usize_of(&case["period"]);
        let lower = case["lower"].as_f64().expect("lower");
        let upper = case["upper"].as_f64().expect("upper");
        let ctx = format!("box_cox_lambda[guerrero, {name}, period = {period}]");
        let y = f64s(&fx["boxcox_series"][name]);

        let got = box_cox_lambda(&y, BoxCoxMethod::Guerrero { period }, (lower, upper))
            .expect("guerrero succeeds");

        assert_pclose(
            got.lambda,
            case["lambda"].as_f64().expect("lambda"),
            1e-6,
            0.0,
            &format!("{ctx}: lambda"),
        );
        assert_close(
            got.objective,
            case["cv"].as_f64().expect("cv"),
            1e-8,
            &format!("{ctx}: criterion at the optimum"),
        );
        // Guerrero has no likelihood, so the MLE-only fields stay empty.
        assert!(got.loglik_at_zero.is_none(), "{ctx}: no l(0)");
        assert!(got.lr_vs_zero.is_none(), "{ctx}: no LR");
    }
}
