//! Golden-value tests for the DF-GLS unit-root test against
//! `fixtures/dfgls.json` (generated by `fixtures/generate_dfgls_fixtures.py`
//! with arch 8.0.0).
//!
//! Tolerances per the generator header: statistics at `1e-10` relative
//! (independent QR vs numpy lstsq/pinv); the selected lag and `nobs`
//! exact; critical values at `1e-12` relative (identical Horner
//! evaluation of the same transcribed doubles); p-values with a combined
//! `atol = 1e-12`, `rtol = 1e-8` (tsecon-stats vs scipy normal-CDF
//! difference in the deep tail).

use serde_json::Value;
use tsecon_diag::{dfgls, AdfLagSelection, DfglsTrend};

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/dfgls.json");
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

/// Relative comparison; falls back to absolute when the reference is 0.
fn assert_close(actual: f64, expected: f64, rtol: f64, ctx: &str) {
    if expected == 0.0 {
        assert!(
            actual.abs() <= rtol,
            "{ctx}: actual {actual}, expected 0 (atol {rtol})"
        );
    } else {
        let rel = ((actual - expected) / expected).abs();
        assert!(
            rel <= rtol,
            "{ctx}: actual {actual}, expected {expected}, rel err {rel:e} > {rtol:e}"
        );
    }
}

/// Combined absolute+relative comparison for p-values (numpy `allclose`
/// semantics): pass if `|a - e| <= atol + rtol |e|`.
fn assert_pclose(actual: f64, expected: f64, ctx: &str) {
    const ATOL: f64 = 1e-12;
    const RTOL: f64 = 1e-8;
    let tol = ATOL + RTOL * expected.abs();
    assert!(
        (actual - expected).abs() <= tol,
        "{ctx}: actual {actual}, expected {expected}, |diff| {:e} > {tol:e}",
        (actual - expected).abs()
    );
}

fn trend(code: &str) -> DfglsTrend {
    match code {
        "c" => DfglsTrend::Constant,
        "ct" => DfglsTrend::ConstantTrend,
        other => panic!("unknown trend {other:?}"),
    }
}

#[test]
fn dfgls_cases_match_arch() {
    let fx = fixture();
    let series = &fx["series"];
    for case in fx["cases"].as_array().expect("cases") {
        let name = case["series"].as_str().expect("series");
        let trend_code = case["trend"].as_str().expect("trend");
        let lags = case["lags"].as_u64().map(|v| v as usize);
        let max_lags = case["max_lags"].as_u64().map(|v| v as usize);
        let method = case["method"].as_str().expect("method");
        let selection = match lags {
            Some(l) => AdfLagSelection::Fixed(l),
            None => match method {
                "aic" => AdfLagSelection::Aic(max_lags),
                "bic" => AdfLagSelection::Bic(max_lags),
                "t-stat" => AdfLagSelection::TStat(max_lags),
                other => panic!("unknown method {other:?}"),
            },
        };
        let ctx = format!(
            "dfgls[{name}/{trend_code}/lags={}/max_lags={}/{method}]",
            lags.map(|l| l.to_string()).unwrap_or_else(|| "auto".into()),
            max_lags
                .map(|l| l.to_string())
                .unwrap_or_else(|| "auto".into()),
        );

        let y = f64s(&series[name]);
        let res = dfgls(&y, trend(trend_code), selection).expect("dfgls runs");

        assert_close(
            res.statistic,
            case["stat"].as_f64().expect("stat"),
            1e-10,
            &format!("{ctx} stat"),
        );
        assert_pclose(
            res.p_value,
            case["pvalue"].as_f64().expect("pvalue"),
            &format!("{ctx} pvalue"),
        );
        assert_eq!(
            res.used_lag,
            case["lags_used"].as_u64().expect("lags_used") as usize,
            "{ctx} used_lag"
        );
        assert_eq!(
            res.nobs,
            case["nobs"].as_u64().expect("nobs") as usize,
            "{ctx} nobs"
        );
        let crit = &case["crit"];
        assert_close(
            res.crit.pct1,
            crit["1%"].as_f64().expect("1%"),
            1e-12,
            &format!("{ctx} crit 1%"),
        );
        assert_close(
            res.crit.pct5,
            crit["5%"].as_f64().expect("5%"),
            1e-12,
            &format!("{ctx} crit 5%"),
        );
        assert_close(
            res.crit.pct10,
            crit["10%"].as_f64().expect("10%"),
            1e-12,
            &format!("{ctx} crit 10%"),
        );
        assert_eq!(res.trend, trend(trend_code), "{ctx} trend echoed");
    }
}
