//! Golden-value tests for the `nsdiffs` seasonal-differencing advisor
//! against `fixtures/stl.json` (generated by
//! `fixtures/generate_stl_fixtures.py` with statsmodels 0.14.6).
//!
//! Grading (per the generator header): the per-step seasonal/trend
//! strengths come from statsmodels STL components combined with the
//! transcribed Wang-Smith-Hyndman formula (ddof = 1), and the sequential
//! 0.64-threshold rule is a documented-rule transcription of
//! `forecast::nsdiffs(test = "seas")` — the same honest grade as the
//! `ndiffs` rule in `generate_advisors_fixtures.py`. Strengths are pinned
//! at 1e-8 relative; `d`, `stop`, and every step's decision exactly.

use serde_json::Value;
use tsecon_diag::{nsdiffs, NsdiffsStop, NSDIFFS_SEAS_THRESHOLD};

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/stl.json");
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

fn assert_close(actual: f64, expected: f64, tol: f64, ctx: &str) {
    let err = (actual - expected).abs() / expected.abs().max(1.0);
    assert!(
        err <= tol,
        "{ctx}: actual {actual}, expected {expected}, err {err:e} > {tol:e}"
    );
}

fn stop_label(s: NsdiffsStop) -> &'static str {
    match s {
        NsdiffsStop::WeakSeasonality => "WeakSeasonality",
        NsdiffsStop::MaxD => "MaxD",
        NsdiffsStop::Constant => "Constant",
        NsdiffsStop::TooShort => "TooShort",
    }
}

#[test]
fn nsdiffs_cases_match_fixture() {
    let fx = fixture();
    let series = &fx["series"];
    assert_close(
        NSDIFFS_SEAS_THRESHOLD,
        fx["_meta"]["seas_threshold"].as_f64().expect("threshold"),
        0.0,
        "threshold",
    );
    for case in fx["nsdiffs"].as_array().expect("nsdiffs cases") {
        let name = case["series"].as_str().expect("series");
        let period = case["period"].as_u64().expect("period") as usize;
        let max_d = case["max_d"].as_u64().expect("max_d") as usize;
        let ctx = format!("nsdiffs[{name}/max_d={max_d}]");
        let y = f64s(&series[name]);

        let r = nsdiffs(&y, period, 0.05, max_d).expect("nsdiffs runs");
        assert_eq!(r.d, case["d"].as_u64().expect("d") as usize, "{ctx} d");
        assert_eq!(
            stop_label(r.stop),
            case["stop"].as_str().expect("stop"),
            "{ctx} stop"
        );
        let steps = case["steps"].as_array().expect("steps");
        assert_eq!(r.steps.len(), steps.len(), "{ctx} step count");
        for (i, (got, want)) in r.steps.iter().zip(steps).enumerate() {
            let sctx = format!("{ctx} step {i}");
            assert_eq!(got.d, want["d"].as_u64().expect("d") as usize, "{sctx} d");
            assert_eq!(got.n, want["n"].as_u64().expect("n") as usize, "{sctx} n");
            assert_close(
                got.seasonal_strength,
                want["seasonal_strength"].as_f64().expect("ss"),
                1e-8,
                &format!("{sctx} seasonal_strength"),
            );
            assert_close(
                got.trend_strength,
                want["trend_strength"].as_f64().expect("ts"),
                1e-8,
                &format!("{sctx} trend_strength"),
            );
            assert_eq!(
                got.needs_differencing,
                want["needs_differencing"].as_bool().expect("needs"),
                "{sctx} needs_differencing"
            );
        }
    }
}
