//! Golden-value tests for the Phillips-Perron and Phillips-Ouliaris tests
//! against `fixtures/phillips.json` (generated by
//! `fixtures/generate_phillips_fixtures.py` with arch 8.0.0 and statsmodels
//! 0.14.6).
//!
//! Tolerances per the spec: statistics and critical values to `1e-8`
//! relative; p-values with a combined `atol = 1e-12`, `rtol = 1e-8` (the
//! MacKinnon polynomial + normal-CDF map is deterministic, but the
//! cointegration p-values reach the deep tail where the absolute floor
//! guards against tsecon-stats vs scipy CDF differences); `lags` / `nobs` /
//! `n_vars` exact. Comparisons are relative, falling back to absolute
//! against zero, as in the crate's other golden tests.

use serde_json::Value;
use tsecon_diag::{
    phillips_ouliaris, phillips_perron, AdfRegression, PoTestType, PoTrend, PpTestType,
};

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/phillips.json");
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

/// Relative comparison; falls back to absolute when the reference is 0.
fn assert_close(actual: f64, expected: f64, rtol: f64, ctx: &str) {
    if expected == 0.0 {
        assert!(
            actual.abs() <= rtol,
            "{ctx}: actual {actual}, expected 0 (atol {rtol})"
        );
    } else {
        let rel = ((actual - expected) / expected).abs();
        assert!(
            rel <= rtol,
            "{ctx}: actual {actual}, expected {expected}, rel err {rel:e} > {rtol:e}"
        );
    }
}

/// Combined absolute+relative comparison for p-values (numpy `allclose`
/// semantics): pass if `|a - e| <= atol + rtol |e|`.
fn assert_pclose(actual: f64, expected: f64, ctx: &str) {
    const ATOL: f64 = 1e-12;
    const RTOL: f64 = 1e-8;
    let tol = ATOL + RTOL * expected.abs();
    assert!(
        (actual - expected).abs() <= tol,
        "{ctx}: actual {actual}, expected {expected}, |diff| {:e} > {tol:e}",
        (actual - expected).abs()
    );
}

fn adf_regression(code: &str) -> AdfRegression {
    match code {
        "n" => AdfRegression::NoConstant,
        "c" => AdfRegression::Constant,
        "ct" => AdfRegression::ConstantTrend,
        other => panic!("unknown regression {other:?}"),
    }
}

fn po_trend(code: &str) -> PoTrend {
    match code {
        "n" => PoTrend::None,
        "c" => PoTrend::Constant,
        "ct" => PoTrend::ConstantTrend,
        other => panic!("unknown trend {other:?}"),
    }
}

#[test]
fn phillips_perron_cases_match_arch() {
    let fx = fixture();
    let series = &fx["series"];
    for case in fx["pp"].as_array().expect("pp cases") {
        let name = case["series"].as_str().expect("series");
        let reg_code = case["regression"].as_str().expect("regression");
        let tt_code = case["test_type"].as_str().expect("test_type");
        let regression = adf_regression(reg_code);
        let test_type = match tt_code {
            "tau" => PpTestType::Tau,
            "rho" => PpTestType::Rho,
            other => panic!("unknown pp test_type {other:?}"),
        };
        let lags = case["lags"].as_u64().map(|v| v as usize);
        let ctx = format!(
            "pp[{name}/{reg_code}/{tt_code}/lags={}]",
            lags.map(|l| l.to_string()).unwrap_or_else(|| "auto".into())
        );
        let y = f64s(&series[name]);
        let res = phillips_perron(&y, regression, test_type, lags).expect("pp runs");

        assert_close(
            res.stat,
            case["stat"].as_f64().expect("stat"),
            1e-8,
            &format!("{ctx} stat"),
        );
        assert_close(
            res.ztau,
            case["ztau"].as_f64().expect("ztau"),
            1e-8,
            &format!("{ctx} ztau"),
        );
        assert_close(
            res.zalpha,
            case["zalpha"].as_f64().expect("zalpha"),
            1e-8,
            &format!("{ctx} zalpha"),
        );
        assert_pclose(
            res.p_value,
            case["pvalue"].as_f64().expect("pvalue"),
            &format!("{ctx} pvalue"),
        );
        assert_eq!(
            res.lags,
            case["lags_used"].as_u64().expect("lags_used") as usize,
            "{ctx} lags"
        );
        assert_eq!(
            res.nobs,
            case["nobs"].as_u64().expect("nobs") as usize,
            "{ctx} nobs"
        );
        let crit = &case["crit"];
        assert_close(
            res.crit.pct1,
            crit["1%"].as_f64().expect("1%"),
            1e-8,
            &format!("{ctx} crit 1%"),
        );
        assert_close(
            res.crit.pct5,
            crit["5%"].as_f64().expect("5%"),
            1e-8,
            &format!("{ctx} crit 5%"),
        );
        assert_close(
            res.crit.pct10,
            crit["10%"].as_f64().expect("10%"),
            1e-8,
            &format!("{ctx} crit 10%"),
        );
        assert_eq!(res.regression, regression, "{ctx} regression echoed");
    }
}

#[test]
fn phillips_ouliaris_cases_match_arch() {
    let fx = fixture();
    let systems = &fx["po_series"];
    for case in fx["po"].as_array().expect("po cases") {
        let sys = case["system"].as_str().expect("system");
        let trend_code = case["trend"].as_str().expect("trend");
        let tt_code = case["test_type"].as_str().expect("test_type");
        let trend = po_trend(trend_code);
        let test_type = match tt_code {
            "Za" => PoTestType::Za,
            "Zt" => PoTestType::Zt,
            other => panic!("unknown po test_type {other:?}"),
        };
        let bandwidth = case["bandwidth"].as_u64().map(|v| v as usize);
        let ctx = format!("po[{sys}/{trend_code}/{tt_code}]");

        let sysdata = &systems[sys];
        let x: Vec<Vec<f64>> = sysdata["x"]
            .as_array()
            .expect("x columns")
            .iter()
            .map(f64s)
            .collect();
        let y = f64s(&sysdata["y"]);
        let res = phillips_ouliaris(&y, &x, trend, test_type, bandwidth).expect("po runs");

        assert_close(
            res.stat,
            case["stat"].as_f64().expect("stat"),
            1e-8,
            &format!("{ctx} stat"),
        );
        assert_eq!(
            res.n_vars,
            case["n_vars"].as_u64().expect("n_vars") as usize,
            "{ctx} n_vars"
        );
        assert_eq!(
            res.lags,
            case["lags"].as_u64().expect("lags") as usize,
            "{ctx} lags"
        );
        assert_eq!(
            res.nobs,
            case["nobs"].as_u64().expect("nobs") as usize,
            "{ctx} nobs"
        );

        match case["pvalue"].as_f64() {
            Some(p) => assert_pclose(res.p_value, p, &format!("{ctx} pvalue")),
            None => assert!(
                res.p_value.is_nan(),
                "{ctx} pvalue: expected NaN, got {}",
                res.p_value
            ),
        }

        match case["crit"].as_object() {
            Some(crit) => {
                let c = res.crit.expect("crit present");
                assert_close(
                    c.pct1,
                    crit["1%"].as_f64().expect("1%"),
                    1e-8,
                    &format!("{ctx} crit 1%"),
                );
                assert_close(
                    c.pct5,
                    crit["5%"].as_f64().expect("5%"),
                    1e-8,
                    &format!("{ctx} crit 5%"),
                );
                assert_close(
                    c.pct10,
                    crit["10%"].as_f64().expect("10%"),
                    1e-8,
                    &format!("{ctx} crit 10%"),
                );
            }
            None => assert!(res.crit.is_none(), "{ctx} crit: expected None"),
        }
        assert_eq!(res.trend, trend, "{ctx} trend echoed");
    }
}
