//! Golden-value tests for the Zivot-Andrews one-break unit-root test
//! against `fixtures/zivot_andrews.json` (generated by
//! `fixtures/generate_zivot_andrews_fixtures.py` with statsmodels 0.14.6
//! as the primary reference and arch 8.0.0 as a same-lineage cross-check).
//!
//! Tolerances: statistic to `1e-10` relative (the OLS t-ratio pipeline is
//! replicated including the reference's normalization, so agreement is at
//! solver-noise level); break index and selected lag exact; critical
//! values to `1e-12` relative (table knots); p-values with a combined
//! `atol = 1e-12`, `rtol = 1e-8` — the interpolation is deterministic, but
//! the underlying table has Monte Carlo resolution, so nothing tighter
//! would be honest about the p-value itself.

use serde_json::Value;
use tsecon_diag::{za_crit, za_p, zivot_andrews, ZaLagSelection, ZaRegression};

fn fixture() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/zivot_andrews.json"
    );
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

/// Relative comparison; falls back to absolute when the reference is 0.
fn assert_close(actual: f64, expected: f64, rtol: f64, ctx: &str) {
    if expected == 0.0 {
        assert!(
            actual.abs() <= rtol,
            "{ctx}: actual {actual}, expected 0 (atol {rtol})"
        );
    } else {
        let rel = ((actual - expected) / expected).abs();
        assert!(
            rel <= rtol,
            "{ctx}: actual {actual}, expected {expected}, rel err {rel:e} > {rtol:e}"
        );
    }
}

/// Combined absolute+relative comparison for p-values (numpy `allclose`
/// semantics): pass if `|a - e| <= atol + rtol |e|`.
fn assert_pclose(actual: f64, expected: f64, ctx: &str) {
    const ATOL: f64 = 1e-12;
    const RTOL: f64 = 1e-8;
    let tol = ATOL + RTOL * expected.abs();
    assert!(
        (actual - expected).abs() <= tol,
        "{ctx}: actual {actual}, expected {expected}, |diff| {:e} > {tol:e}",
        (actual - expected).abs()
    );
}

fn za_regression(code: &str) -> ZaRegression {
    match code {
        "c" => ZaRegression::Constant,
        "t" => ZaRegression::Trend,
        "ct" => ZaRegression::ConstantTrend,
        other => panic!("unknown regression {other:?}"),
    }
}

/// Reconstruct the lag-selection spec from the fixture case fields
/// (mirroring the statsmodels autolag/maxlag encoding the generator used).
fn lag_selection(case: &Value) -> ZaLagSelection {
    let maxlag = case["maxlag"].as_u64().map(|v| v as usize);
    let lags = case["lags"].as_u64().map(|v| v as usize);
    match case["autolag"].as_str() {
        Some("aic") => ZaLagSelection::Aic(maxlag),
        Some("bic") => ZaLagSelection::Bic(maxlag),
        Some("t-stat") => ZaLagSelection::TStat(maxlag),
        Some(other) => panic!("unknown autolag {other:?}"),
        None => match lags {
            Some(l) => ZaLagSelection::Fixed(l),
            None => ZaLagSelection::SchwertTrunc,
        },
    }
}

#[test]
fn zivot_andrews_cases_match_statsmodels() {
    let fx = fixture();
    let series = &fx["series"];
    for case in fx["za"].as_array().expect("za cases") {
        let name = case["series"].as_str().expect("series");
        let reg_code = case["regression"].as_str().expect("regression");
        let trim = case["trim"].as_f64().expect("trim");
        let ctx = format!(
            "za[{name}/{reg_code}/trim={trim}/autolag={:?}/lags={:?}]",
            case["autolag"].as_str(),
            case["lags"].as_u64()
        );
        let y = f64s(&series[name]);
        let res = zivot_andrews(&y, za_regression(reg_code), trim, lag_selection(case))
            .expect("zivot_andrews runs");

        assert_close(
            res.statistic,
            case["stat"].as_f64().expect("stat"),
            1e-10,
            &format!("{ctx} stat"),
        );
        assert_pclose(
            res.p_value,
            case["pvalue"].as_f64().expect("pvalue"),
            &format!("{ctx} pvalue"),
        );
        assert_eq!(
            res.break_index,
            case["bpidx"].as_u64().expect("bpidx") as usize,
            "{ctx} break index"
        );
        assert_eq!(
            res.used_lag,
            case["baselag"].as_u64().expect("baselag") as usize,
            "{ctx} used lag"
        );
        assert_eq!(
            res.nobs,
            case["nobs"].as_u64().expect("nobs") as usize,
            "{ctx} nobs"
        );
        let crit = &case["crit"];
        assert_close(
            res.crit.pct1,
            crit["1%"].as_f64().expect("1%"),
            1e-12,
            &format!("{ctx} crit 1%"),
        );
        assert_close(
            res.crit.pct5,
            crit["5%"].as_f64().expect("5%"),
            1e-12,
            &format!("{ctx} crit 5%"),
        );
        assert_close(
            res.crit.pct10,
            crit["10%"].as_f64().expect("10%"),
            1e-12,
            &format!("{ctx} crit 10%"),
        );
        assert_eq!(
            res.regression,
            za_regression(reg_code),
            "{ctx} regression echoed"
        );
    }
}

#[test]
fn zivot_andrews_p_map_matches_statsmodels_interpolation() {
    // Pins the transcribed simulated-null table and the numpy.interp
    // arithmetic on a grid, independent of any series — a transcription
    // typo in the Rust table cannot hide behind the case statistics.
    let fx = fixture();
    for reg_code in ["c", "t", "ct"] {
        let reg = za_regression(reg_code);
        let map = &fx["p_map"][reg_code];
        let grid = f64s(&map["stat_grid"]);
        let pvals = f64s(&map["pvalues"]);
        for (stat, expected) in grid.iter().zip(&pvals) {
            assert_pclose(
                za_p(*stat, reg),
                *expected,
                &format!("p_map[{reg_code}] at stat={stat}"),
            );
        }
        let crit = za_crit(reg);
        for (key, actual) in [("1%", crit.pct1), ("5%", crit.pct5), ("10%", crit.pct10)] {
            assert_close(
                actual,
                map["crit"][key].as_f64().expect("crit"),
                1e-12,
                &format!("p_map[{reg_code}] crit {key}"),
            );
        }
    }
}
