//! # tsecon-longmemory — fractional integration and long memory
//!
//! Semiparametric long-memory tooling for the `tsecon` time-series
//! econometrics library (ROADMAP E7). Three capabilities, each built on the
//! library's single owner of the underlying primitive rather than a private
//! reimplementation:
//!
//! ## Module map
//!
//! - [`frac_diff_weights`], [`frac_diff`], [`frac_integrate`]
//!   ([`mod@fracdiff`]): the fractional-difference operator `(1 - L)^d` via
//!   the exact binomial recursion `pi_0 = 1`, `pi_k = pi_{k-1} (k-1-d)/k`,
//!   applied as a start-of-sample-truncated finite convolution, and its exact
//!   inverse (fractional integration). **Documented-formula golden**: NumPy
//!   runs the same binomial recursion and convolution, matched to ~1e-12.
//! - [`gph`] / [`GphResult`] ([`mod@gph`]): the Geweke-Porter-Hudak (1983)
//!   log-periodogram regression. The OLS slope of `log I(lambda_j)` on
//!   `R_j = -2 log(2 sin(lambda_j/2))` over the lowest `m` Fourier
//!   frequencies estimates `d`; the reported [`GphResult::se`] is the exact
//!   slope SE `sqrt((pi^2/6) / sum_j (R_j - Rbar)^2)` at the bandwidth
//!   actually used, with the textbook large-`m` limit `pi / sqrt(24 m)`
//!   reported alongside as [`GphResult::se_asymptotic`]. Uses
//!   [`tsecon_spectral`] for the periodogram and [`tsecon_hac`] for the OLS.
//!   **Documented-formula golden**: NumPy builds the periodogram (FFT), the
//!   GPH regressor, and the OLS, matched to ~1e-8 (there is no mainstream
//!   Python GPH package to reference).
//! - [`local_whittle`] / [`WhittleResult`] ([`mod@whittle`]): the Robinson
//!   (1995) Gaussian semiparametric estimator, minimizing the concentrated
//!   objective `R(d) = log((1/m) sum lambda_j^{2d} I_j) - (2d/m) sum log
//!   lambda_j` over `(-1/2, 1)` through [`tsecon_optim`]; the reported
//!   [`WhittleResult::se`] is `1 / (2 sqrt(sum_j nu_j^2))` with
//!   `nu_j = log lambda_j - mean(log lambda)`, whose large-`m` limit
//!   `1 / (2 sqrt(m))` is reported alongside as
//!   [`WhittleResult::se_asymptotic`]. **Documented-formula golden**: NumPy
//!   evaluates `R(d)` on a grid and reports its minimizer, matched to ~1e-6.
//! - [`default_bandwidth`]: the textbook `m = floor(sqrt(n))` rule.
//!
//! ## Standard errors at the default bandwidth
//!
//! Both estimators' textbook standard errors — `pi / sqrt(24 m)` for GPH,
//! `1 / (2 sqrt(m))` for local Whittle — are large-`m` limits of exact
//! expressions, and both replace the same slowly-converging quantity
//! (`(1/m) sum_j nu_j^2 -> 1`) by its limit. At `m = floor(sqrt(n))` that
//! quantity is only `0.65` (`n = 512`) to `0.76` (`n = 2048`), so the textbook
//! constants are 15-25% too narrow — nominal-95% intervals cover 86-91% on
//! exact ARFIMA(0, d, 0) draws. `se` therefore reports the exact
//! bandwidth-dependent expression in both cases and `se_asymptotic` retains
//! the limit; `properties.rs` pins the calibration by Monte Carlo.
//!
//! ## Validation: documented-formula vs property
//!
//! The golden fixtures (`fixtures/longmemory.json`, generated by
//! `fixtures/generate_longmemory_fixtures.py`) are all **documented-formula**
//! goldens: on fixed inputs NumPy computes each published quantity by writing
//! out the closed form — the binomial recursion, the GPH FFT + regressor +
//! OLS, and a grid evaluation of `R(d)` with its minimizer — never calling
//! this crate, so the check is non-circular. Matching them proves the Rust
//! reproduces the documented algebra. Separately, seeded **Monte-Carlo
//! property** tests establish the statistical claim the algebra exists to
//! support: on simulated ARFIMA(0, d, 0) series with known `d in {0.2, 0.4}`,
//! both GPH and local Whittle recover `d` within Monte-Carlo bands.
//!
//! ```
//! use tsecon_longmemory::{frac_diff, frac_integrate, gph, local_whittle, default_bandwidth};
//!
//! // Fractional differencing round-trips exactly.
//! let x: Vec<f64> = (0..600).map(|t| ((t as f64) * 0.03).sin()).collect();
//! let d = 0.3;
//! let rt = frac_integrate(&frac_diff(&x, d).unwrap(), d).unwrap();
//! assert!(rt.iter().zip(&x).all(|(a, b)| (a - b).abs() < 1e-10));
//!
//! // Both memory estimators run on the same low-frequency periodogram.
//! let m = default_bandwidth(x.len());
//! assert!(gph(&x, m).unwrap().d.is_finite());
//! assert!(local_whittle(&x, m).unwrap().d.is_finite());
//! ```

#![warn(missing_docs)]
#![warn(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod error;
mod fracdiff;
mod gph;
mod spectral;
mod whittle;

pub use error::LongMemoryError;
pub use fracdiff::{frac_diff, frac_diff_weights, frac_integrate};
pub use gph::{gph, GphResult};
pub use spectral::default_bandwidth;
pub use whittle::{local_whittle, WhittleResult};
