//! # tsecon-evt — extreme value theory: POT/GPD tails and GEV block maxima
//!
//! The two workhorse EVT routes for tail risk (ROADMAP module 03,
//! "Filtered historical simulation and EVT-POT tails"; module 12 E11):
//!
//! * [`gpd_fit`] — *peaks over threshold*: exceedances of `y` over a high
//!   threshold (default: the empirical 0.90 quantile) are fitted with a
//!   generalized Pareto distribution by MLE (Pickands 1975;
//!   Balkema-de Haan 1974), and tail quantiles/expected shortfall follow
//!   the McNeil-Frey (2000) POT formulas with the empirical exceedance
//!   rate.
//! * [`gev_fit`] — *block maxima*: maxima of consecutive blocks (or
//!   pre-computed maxima) are fitted with the generalized extreme value
//!   distribution by MLE, with return-level quantiles (Coles 2001,
//!   ch. 3).
//!
//! ## Method
//!
//! Both likelihoods are built from the kernel `a = ln(1 + xi x) / xi`,
//! which switches to a second-order expansion below the documented
//! [`XI_CUTOFF`] `= 1e-8` — the Gumbel/exponential-limit branch — so the
//! `xi -> 0` boundary is crossed continuously (property-tested).
//! Optimization runs in the `tsecon-optim` working spaces `(xi, ln beta)`
//! / `(xi, mu, ln sigma)` with the support constraint
//! `1 + xi (x - loc)/scale > 0` enforced as an infinite barrier: BFGS
//! (central-difference gradients — the optimizer crate's documented
//! numerical route) followed by a tight Nelder-Mead polish. Standard
//! errors are observed-information (inverse numerical Hessian, original
//! parameterization).
//!
//! ## Numerical traps, handled and documented
//!
//! * **`xi <= -0.5` irregularity** (Smith 1985): the MLE is non-regular
//!   and observed-information SEs are not backed by asymptotics. They are
//!   still *reported* when computable, but `se_valid = false`.
//! * **`xi <= -1` non-existence**: the GPD/GEV likelihood supremum is
//!   `+inf` at the boundary (`scale -> -xi * max`), so no MLE exists —
//!   e.g. exceedances of a *uniform* variable (`xi = -1`). The fit
//!   returns the best point found; the interior local maximum reported
//!   for regular data is the same one every reference implementation
//!   reports.
//! * **`xi -> 0`**: the limit branch below [`XI_CUTOFF`], continuous
//!   across the seam by construction (truncation error `O(xi^3 x^4)`).
//!
//! ## Sign conventions
//!
//! `xi` is always the *tail index* (positive = heavy tail). scipy's
//! `genpareto` shape `c` **is** this `xi`; scipy's `genextreme` shape is
//! `c = -xi`. Both equivalences are verified numerically in the fixture
//! generator. VaR/ES are quantiles of `y` itself — fit *losses* (e.g.
//! `-returns` or `|returns|`) to read them as risk numbers.
//!
//! ## Validation
//!
//! `fixtures/tsecon-evt.json` (generated by
//! `fixtures/generate_tsecon-evt_fixtures.py`, scipy 1.17.1) pins, on
//! heavy-tailed t(3), exponential (`xi = 0` boundary), bounded-tail
//! (negative `xi`) and real (term-spread absolute log-return) data:
//!
//! * fitted `(xi, beta)` / `(xi, mu, sigma)` against
//!   `scipy.stats.genpareto.fit(z, floc=0)` /
//!   `scipy.stats.genextreme.fit(m)` (each polished to a tight optimum in
//!   the generator) at 1e-6, with the log-likelihood at the respective
//!   optima agreeing at 1e-10 — the honest way to compare two optimizers;
//! * observed-information SEs against a scipy-side numerical Hessian at
//!   1e-4 relative;
//! * VaR/ES against `genpareto.ppf` plus the documented closed form, and
//!   return levels against `genextreme.ppf`, at 1e-5 relative (the
//!   propagation of the 1e-6 parameter pin through the tail formulas).
//!
//! Property tests establish: near-zero fitted `xi` on exponential data,
//! default-vs-explicit threshold equivalence, scale equivariance
//! (`beta`, VaR, ES scale; `xi` invariant), `ES >= VaR` always,
//! continuity across [`XI_CUTOFF`], and teaching errors on degenerate
//! input (fewer than [`MIN_EXCEEDANCES`] exceedances / [`MIN_MAXIMA`]
//! maxima, constants, NaNs).
//!
//! ```
//! use tsecon_evt::gpd_fit;
//!
//! // A deterministic heavy-tailed sample (Pareto alpha = 3 quantile grid).
//! let y: Vec<f64> = (0..500)
//!     .map(|i| ((i as f64 + 0.5) / 500.0, ))
//!     .map(|(u,)| (1.0 - u).powf(-1.0 / 3.0))
//!     .collect();
//! let fit = gpd_fit(&y, None, 0.90, &[0.99]).unwrap();
//! assert!(fit.xi > 0.0); // heavy tail detected
//! assert!(fit.es[0] >= fit.var[0]);
//! ```
//!
//! References: Pickands (1975), Ann. Statist. 3(1); Balkema & de Haan
//! (1974), Ann. Prob. 2(5); Smith (1985), Biometrika 72(1); McNeil & Frey
//! (2000), J. Empirical Finance 7; Coles (2001), *An Introduction to
//! Statistical Modeling of Extreme Values*, Springer.

#![warn(missing_docs)]
#![warn(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod common;
mod error;
mod gev;
mod gpd;

pub use common::XI_CUTOFF;
pub use error::EvtError;
pub use gev::{gev_fit, gev_loglik, GevFit, MIN_MAXIMA};
pub use gpd::{gpd_fit, gpd_loglik, GpdFit, MIN_EXCEEDANCES};
