//! Golden-value tests for MSTL against `fixtures/mstl.json` (generated by
//! `fixtures/generate_mstl_fixtures.py` with statsmodels 0.14.6).
//!
//! The trend, every per-period seasonal, resid (and robustness weights
//! where the outer loop runs) are pinned ELEMENTWISE at 1e-8
//! (absolute-or-relative, `|a - e| <= tol * max(1, |e|)`, as in the
//! crate's other golden tests) — MSTL is a deterministic driver over the
//! already-pinned STL port, so the observed agreement is ~1e-12 and the
//! tolerance is pure headroom. Grade: strong third-party golden
//! (statsmodels MSTL, elementwise).
//!
//! The degenerate single-period case is *additionally* required to equal
//! this crate's own [`stl`] bitwise — internal consistency between the two
//! entry points, graded separately from the third-party golden (see
//! `single_period_mstl_equals_own_stl_bitwise`).

use serde_json::Value;
use tsecon_filters::{mstl, stl, MstlParams, StlParams};

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/mstl.json");
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

fn usizes(v: &Value) -> Vec<usize> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_u64().expect("integer") as usize)
        .collect()
}

/// Absolute-or-relative comparison: |a - e| <= tol * max(1, |e|).
fn assert_close(actual: f64, expected: f64, tol: f64, ctx: &str) {
    let err = (actual - expected).abs() / expected.abs().max(1.0);
    assert!(
        err <= tol,
        "{ctx}: actual {actual}, expected {expected}, err {err:e} > {tol:e}"
    );
}

fn assert_all_close(actual: &[f64], expected: &[f64], tol: f64, ctx: &str) {
    assert_eq!(actual.len(), expected.len(), "{ctx}: length mismatch");
    for (i, (&a, &e)) in actual.iter().zip(expected).enumerate() {
        assert_close(a, e, tol, &format!("{ctx}[{i}]"));
    }
}

/// Build [`MstlParams`] + the periods argument from a fixture case.
fn params_from_case(case: &Value) -> (Vec<usize>, MstlParams) {
    let periods: Vec<usize> = match &case["periods_arg"] {
        Value::Number(p) => vec![p.as_u64().expect("period") as usize],
        other => usizes(other),
    };
    let windows = case
        .get("windows_arg")
        .filter(|v| !v.is_null())
        .map(usizes);
    let iterate = case["iterate"].as_u64().expect("iterate") as usize;
    let kw = &case["stl_kwargs"];
    let get = |key: &str| kw.get(key).and_then(Value::as_u64).map(|x| x as usize);
    let mut stl_params = StlParams {
        robust: kw.get("robust").and_then(Value::as_bool).unwrap_or(false),
        ..Default::default()
    };
    stl_params.trend = get("trend");
    stl_params.low_pass = get("low_pass");
    if let Some(v) = get("seasonal_deg") {
        stl_params.seasonal_deg = v;
    }
    if let Some(v) = get("trend_deg") {
        stl_params.trend_deg = v;
    }
    if let Some(v) = get("low_pass_deg") {
        stl_params.low_pass_deg = v;
    }
    if let Some(v) = get("seasonal_jump") {
        stl_params.seasonal_jump = v;
    }
    if let Some(v) = get("trend_jump") {
        stl_params.trend_jump = v;
    }
    if let Some(v) = get("low_pass_jump") {
        stl_params.low_pass_jump = v;
    }
    stl_params.inner_iter = get("inner_iter");
    stl_params.outer_iter = get("outer_iter");
    (
        periods,
        MstlParams {
            windows,
            iterate,
            stl: stl_params,
        },
    )
}

#[test]
fn mstl_components_match_statsmodels() {
    let fx = fixture();
    let series = &fx["series"];
    let cases = fx["cases"].as_array().expect("mstl cases");
    assert!(cases.len() >= 10, "expected the full case grid");
    for case in cases {
        let name = case["series"].as_str().expect("series");
        let cfg = case["config_name"].as_str().expect("config_name");
        let ctx = format!("mstl[{name}/{cfg}]");
        let y = f64s(&series[name]);
        let (periods, params) = params_from_case(case);
        let r = mstl(&y, &periods, &params).expect("mstl runs");

        // The resolved (sorted, post-drop) periods and windows must match
        // statsmodels' MSTL(...).periods / .windows exactly.
        assert_eq!(
            r.periods,
            usizes(&case["resolved_periods"]),
            "{ctx} resolved periods"
        );
        assert_eq!(
            r.windows,
            usizes(&case["resolved_windows"]),
            "{ctx} resolved windows"
        );
        assert_eq!(
            r.dropped_periods,
            usizes(&case["dropped_periods"]),
            "{ctx} dropped periods"
        );

        let expected_seasonal = case["seasonal"].as_array().expect("seasonal");
        assert_eq!(
            r.seasonal.len(),
            expected_seasonal.len(),
            "{ctx}: seasonal component count"
        );
        for (k, exp) in expected_seasonal.iter().enumerate() {
            assert_all_close(
                &r.seasonal[k],
                &f64s(exp),
                1e-8,
                &format!("{ctx} seasonal[{}]", r.periods[k]),
            );
        }
        assert_all_close(&r.trend, &f64s(&case["trend"]), 1e-8, &format!("{ctx} trend"));
        assert_all_close(&r.resid, &f64s(&case["resid"]), 1e-8, &format!("{ctx} resid"));
        if let Some(w) = case.get("weights").filter(|v| !v.is_null()) {
            assert_all_close(&r.weights, &f64s(w), 1e-8, &format!("{ctx} weights"));
        } else {
            assert!(
                r.weights.iter().all(|&w| w == 1.0),
                "{ctx}: no outer iterations must leave all weights at 1"
            );
        }
    }
}

/// Internal consistency, graded separately from the statsmodels golden: a
/// single-period MSTL is one STL pass with seasonal window 11 (the MSTL
/// default rule 7 + 4*1) and must reproduce this crate's own [`stl`]
/// BITWISE — the two entry points share the identical code path and float
/// stream, so any difference at all is a wiring bug.
#[test]
fn single_period_mstl_equals_own_stl_bitwise() {
    let fx = fixture();
    let y = f64s(&fx["series"]["single"]);
    let m = mstl(&y, &[12], &MstlParams::default()).expect("mstl runs");
    let s = stl(
        &y,
        12,
        &StlParams {
            seasonal: 11,
            ..Default::default()
        },
    )
    .expect("stl runs");
    assert_eq!(m.periods, vec![12]);
    assert_eq!(m.windows, vec![11]);
    assert_eq!(m.iterate, 1, "a single period must force one round");
    assert_eq!(m.seasonal[0], s.seasonal, "seasonal must match bitwise");
    assert_eq!(m.trend, s.trend, "trend must match bitwise");
    assert_eq!(m.resid, s.resid, "resid must match bitwise");
    assert_eq!(m.weights, s.weights, "weights must match bitwise");
}
