//! Golden-value tests for STL decomposition against `fixtures/stl.json`
//! (generated by `fixtures/generate_stl_fixtures.py` with statsmodels
//! 0.14.6).
//!
//! The seasonal/trend/resid arrays (and robustness weights where the outer
//! loop runs) are pinned ELEMENTWISE at 1e-8 (absolute-or-relative,
//! `|a - e| <= tol * max(1, |e|)`, as in the crate's other golden tests) —
//! the algorithm is deterministic, so the observed agreement is ~1e-12 (worst ~1.2e-11 on the co2 robust case, where 15 outer iterations amplify ulp noise) and
//! the tolerance is pure headroom. The strength cases pin the
//! Wang-Smith-Hyndman measures computed from statsmodels components with
//! the documented formula (see the generator header for the honest
//! grading: components are a third-party golden; the formula is a
//! documented-formula transcription).

use serde_json::Value;
use tsecon_filters::{seasonal_strength, stl, StlParams};

fn fixture() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../fixtures/stl.json");
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

/// Absolute-or-relative comparison: |a - e| <= tol * max(1, |e|).
fn assert_close(actual: f64, expected: f64, tol: f64, ctx: &str) {
    let err = (actual - expected).abs() / expected.abs().max(1.0);
    assert!(
        err <= tol,
        "{ctx}: actual {actual}, expected {expected}, err {err:e} > {tol:e}"
    );
}

fn assert_all_close(actual: &[f64], expected: &[f64], tol: f64, ctx: &str) {
    assert_eq!(actual.len(), expected.len(), "{ctx}: length mismatch");
    for (i, (&a, &e)) in actual.iter().zip(expected).enumerate() {
        assert_close(a, e, tol, &format!("{ctx}[{i}]"));
    }
}

/// Build [`StlParams`] from a fixture case's `kwargs` + `fit_kwargs`.
fn params_from_case(case: &Value) -> StlParams {
    let kw = &case["kwargs"];
    let fkw = &case["fit_kwargs"];
    let get = |v: &Value, key: &str| v.get(key).and_then(Value::as_u64).map(|x| x as usize);
    let mut p = StlParams {
        robust: kw.get("robust").and_then(Value::as_bool).unwrap_or(false),
        ..Default::default()
    };
    if let Some(v) = get(kw, "seasonal") {
        p.seasonal = v;
    }
    p.trend = get(kw, "trend");
    p.low_pass = get(kw, "low_pass");
    if let Some(v) = get(kw, "seasonal_deg") {
        p.seasonal_deg = v;
    }
    if let Some(v) = get(kw, "trend_deg") {
        p.trend_deg = v;
    }
    if let Some(v) = get(kw, "low_pass_deg") {
        p.low_pass_deg = v;
    }
    if let Some(v) = get(kw, "seasonal_jump") {
        p.seasonal_jump = v;
    }
    if let Some(v) = get(kw, "trend_jump") {
        p.trend_jump = v;
    }
    if let Some(v) = get(kw, "low_pass_jump") {
        p.low_pass_jump = v;
    }
    p.inner_iter = get(fkw, "inner_iter");
    p.outer_iter = get(fkw, "outer_iter");
    p
}

#[test]
fn stl_components_match_statsmodels() {
    let fx = fixture();
    let series = &fx["series"];
    let cases = fx["stl"].as_array().expect("stl cases");
    assert!(cases.len() >= 15, "expected the full case grid");
    for case in cases {
        let name = case["series"].as_str().expect("series");
        let cfg = case["config_name"].as_str().expect("config_name");
        let period = case["period"].as_u64().expect("period") as usize;
        let ctx = format!("stl[{name}/{cfg}]");
        let y = f64s(&series[name]);
        let params = params_from_case(case);
        let r = stl(&y, period, &params).expect("stl runs");

        assert_all_close(
            &r.seasonal,
            &f64s(&case["seasonal"]),
            1e-8,
            &format!("{ctx} seasonal"),
        );
        assert_all_close(
            &r.trend,
            &f64s(&case["trend"]),
            1e-8,
            &format!("{ctx} trend"),
        );
        assert_all_close(
            &r.resid,
            &f64s(&case["resid"]),
            1e-8,
            &format!("{ctx} resid"),
        );
        if let Some(w) = case.get("weights").filter(|v| !v.is_null()) {
            assert_all_close(&r.weights, &f64s(w), 1e-8, &format!("{ctx} weights"));
        } else {
            assert!(
                r.weights.iter().all(|&w| w == 1.0),
                "{ctx}: outer_iter = 0 must leave all weights at 1"
            );
        }

        // The resolved configuration must match statsmodels' `config`
        // (default trend/low_pass window rules) exactly.
        let resolved = &case["resolved"];
        let ri = |key: &str| resolved[key].as_u64().expect(key) as usize;
        assert_eq!(r.config.period, ri("period"), "{ctx} period");
        assert_eq!(r.config.seasonal, ri("seasonal"), "{ctx} seasonal window");
        assert_eq!(r.config.trend, ri("trend"), "{ctx} trend window");
        assert_eq!(r.config.low_pass, ri("low_pass"), "{ctx} low_pass window");
        assert_eq!(
            r.config.seasonal_deg,
            ri("seasonal_deg"),
            "{ctx} seasonal_deg"
        );
        assert_eq!(r.config.trend_deg, ri("trend_deg"), "{ctx} trend_deg");
        assert_eq!(
            r.config.low_pass_deg,
            ri("low_pass_deg"),
            "{ctx} low_pass_deg"
        );
    }
}

#[test]
fn strength_measures_match_documented_formula() {
    let fx = fixture();
    let series = &fx["series"];
    for case in fx["strength"].as_array().expect("strength cases") {
        let name = case["series"].as_str().expect("series");
        let period = case["period"].as_u64().expect("period") as usize;
        let ctx = format!("strength[{name}]");
        let y = f64s(&series[name]);
        let r = seasonal_strength(&y, period).expect("strength runs");
        assert_close(
            r.seasonal_strength,
            case["seasonal_strength"].as_f64().expect("seasonal"),
            1e-8,
            &format!("{ctx} seasonal_strength"),
        );
        assert_close(
            r.trend_strength,
            case["trend_strength"].as_f64().expect("trend"),
            1e-8,
            &format!("{ctx} trend_strength"),
        );
        assert_eq!(r.period, period, "{ctx} period");
    }
}
