//! Golden-value tests for the Koop-Pesaran-Potter GIRF engine on the
//! linear VAR against `fixtures/girf.json` (generated by
//! `fixtures/generate_girf_fixtures.py`).
//!
//! With common random numbers the paired with/without difference of a
//! linear model is `Psi_h delta` for every draw and every history, so the
//! simulation must reproduce two closed forms with zero Monte Carlo noise:
//!
//! * `GirfShock::Orthogonal` — statsmodels `VARResults.irf(orth=True)`
//!   (independent package), column `shock_var`, times `size`;
//! * `GirfShock::Generalized` — the Pesaran-Shin (1998) closed form
//!   `Phi_h Sigma e_j / sqrt(sigma_jj) * size` transcribed in NumPy in the
//!   generator (documented formula golden).
//!
//! Both are pinned at 1e-12 absolute with a single draw, with antithetic
//! pairs, and on a seeded subsample of histories; the across-history and
//! across-draw spreads must vanish.

mod common;

use common::{as_mat, load_fixture};
use serde_json::Value;
use tsecon_var::{var_girf, GirfOptions, GirfShock, Trend, VarSpec};

const TOL: f64 = 1e-12;

fn assert_path_close(actual: &[Vec<f64>], expected: &Value, ctx: &str) {
    let e = expected.as_array().expect("path rows");
    assert_eq!(actual.len(), e.len(), "{ctx}: horizon count");
    for (h, (a_row, e_row)) in actual.iter().zip(e).enumerate() {
        let e_row = e_row.as_array().expect("row");
        assert_eq!(a_row.len(), e_row.len(), "{ctx}[{h}]: width");
        for (j, (&a, ev)) in a_row.iter().zip(e_row).enumerate() {
            let ev = ev.as_f64().expect("number");
            assert!(
                (a - ev).abs() <= TOL,
                "{ctx}[h={h}][{j}]: {a} vs {ev} (abs diff {:e} > {TOL:e})",
                (a - ev).abs()
            );
        }
    }
}

fn cases() -> (Value, tsecon_var::tsecon_linalg::faer::Mat<f64>) {
    let fx = load_fixture("girf.json");
    let data = as_mat(&fx["linear"]["series"]);
    (fx, data)
}

fn options(case: &Value, generalized: bool, n_draws: usize, antithetic: bool) -> GirfOptions {
    let var = case["shock_var"].as_u64().expect("shock_var") as usize;
    let size = case["size"].as_f64().expect("size");
    GirfOptions {
        shock: if generalized {
            GirfShock::Generalized { var, size }
        } else {
            GirfShock::Orthogonal { var, size }
        },
        horizon: case["horizon"].as_u64().expect("horizon") as usize,
        n_draws,
        seed: 20260910,
        antithetic,
        bands: (0.16, 0.84),
    }
}

fn fit(case: &Value, data: &tsecon_var::tsecon_linalg::faer::Mat<f64>) -> tsecon_var::VarResults {
    let lags = case["p"].as_u64().expect("p") as usize;
    let trend = match case["trend"].as_str().expect("trend") {
        "c" => Trend::Constant,
        "n" => Trend::None,
        other => panic!("unknown trend {other}"),
    };
    VarSpec { lags, trend }.fit(data.as_ref()).expect("fit")
}

#[test]
fn orthogonal_shock_reproduces_statsmodels_cholesky_irf_with_one_draw() {
    let (fx, data) = cases();
    for case in fx["linear"]["cases"].as_array().expect("cases") {
        let res = fit(case, &data);
        let g = var_girf(&res, &options(case, false, 1, false), None).expect("girf");
        let ctx = format!("orthogonal p={} trend={}", case["p"], case["trend"]);
        assert_path_close(&g.girf, &case["girf_orthogonal"], &ctx);
        assert_eq!(
            g.n_histories,
            case["n_histories_all"].as_u64().expect("n") as usize,
            "{ctx}: every lag window is a history"
        );
        // History invariance: every history-conditional path is the same
        // closed form, so the across-history band has zero width.
        for h in 0..=g.horizon {
            for j in 0..g.girf[0].len() {
                assert!(
                    (g.upper[h][j] - g.lower[h][j]).abs() <= TOL,
                    "{ctx}: band width"
                );
                assert!(g.mc_se[h][j].is_nan(), "{ctx}: one draw has no MC se");
                assert!(g.draw_sd[h][j].is_nan(), "{ctx}: one draw has no draw sd");
            }
        }
        for path in &g.per_history {
            assert_path_close(
                path,
                &case["girf_orthogonal"],
                &format!("{ctx} per-history"),
            );
        }
        let expected_shock: Vec<f64> = case["shock_vector_orthogonal"]
            .as_array()
            .expect("shock")
            .iter()
            .map(|v| v.as_f64().expect("number"))
            .collect();
        for (a, e) in g.shock_by_state[0].iter().zip(&expected_shock) {
            assert!((a - e).abs() <= TOL, "{ctx}: shock vector {a} vs {e}");
        }
    }
}

#[test]
fn generalized_shock_reproduces_the_pesaran_shin_closed_form() {
    let (fx, data) = cases();
    for case in fx["linear"]["cases"].as_array().expect("cases") {
        let res = fit(case, &data);
        let g = var_girf(&res, &options(case, true, 1, false), None).expect("girf");
        let ctx = format!("generalized p={} trend={}", case["p"], case["trend"]);
        assert_path_close(&g.girf, &case["girf_generalized"], &ctx);
        let expected_shock: Vec<f64> = case["shock_vector_generalized"]
            .as_array()
            .expect("shock")
            .iter()
            .map(|v| v.as_f64().expect("number"))
            .collect();
        for (a, e) in g.shock_by_state[0].iter().zip(&expected_shock) {
            assert!((a - e).abs() <= TOL, "{ctx}: shock vector {a} vs {e}");
        }
    }
}

#[test]
fn more_draws_antithetic_pairs_and_a_subsample_change_nothing_for_a_linear_model() {
    let (fx, data) = cases();
    for case in fx["linear"]["cases"].as_array().expect("cases") {
        let res = fit(case, &data);
        for (generalized, key) in [(false, "girf_orthogonal"), (true, "girf_generalized")] {
            let g = var_girf(&res, &options(case, generalized, 8, true), Some(10)).expect("girf");
            let ctx = format!("{key} p={} 8 antithetic draws, 10 histories", case["p"]);
            assert_path_close(&g.girf, &case[key], &ctx);
            assert_eq!(g.n_histories, 10, "{ctx}: subsample size");
            assert_eq!(g.n_draws, 8);
            assert_eq!(g.n_effective_draws, 4);
            for h in 0..=g.horizon {
                for j in 0..g.girf[0].len() {
                    // Every draw gives the identical path: the across-draw
                    // spread and the MC standard error are zero, not NaN.
                    assert!(
                        g.draw_sd[h][j].abs() <= TOL,
                        "{ctx}: draw sd {}",
                        g.draw_sd[h][j]
                    );
                    assert!(g.mc_se[h][j].abs() <= TOL, "{ctx}: mc se {}", g.mc_se[h][j]);
                    assert!((g.draw_upper[h][j] - g.draw_lower[h][j]).abs() <= TOL);
                }
            }
        }
    }
}
