//! # tsecon-breaks — multiple structural breaks (Bai–Perron)
//!
//! Estimation and testing of the pure-structural-change regression
//!
//! ```text
//! y_t = x_t' beta_j + u_t,        t in regime j = 1, ..., m + 1,
//! ```
//!
//! where every coefficient switches at each of `m` unknown break dates
//! (include the constant in `x` explicitly). The break suite that no
//! mainstream Python package ships with full inference:
//!
//! - **Global partitions by dynamic programming** (Bai & Perron 1998
//!   *Econometrica*; 2003 *J. Applied Econometrics*): segment SSRs from
//!   recursive normal-equation updates, then the break-point recursion
//!   yields the exact SSR-minimizing partition for every `m = 1..=max_breaks`
//!   with minimal regime length `h = ceil(trim * T)`.
//! - **Sequential selection**: `supF(l+1|l)` statistics (classical
//!   homoskedastic Wald form) tested at the 5% level against the published
//!   Bai–Perron critical values (1998 Table II / 2003b *Econometrics
//!   Journal*), transcribed in [`tables`] with full citations. Selection
//!   stops at the first non-rejection.
//! - **Break-date confidence intervals** (Bai 1997 *REStat*): the
//!   closed-form cdf of `argmax_s {W(s) - |s|/2}` is inverted for 90%/95%
//!   intervals under the *homogeneous* shrinking-break asymptotics —
//!   common regressor second moment `Q = X'X/T` and common error variance
//!   across adjacent regimes. Heterogeneity-robust intervals (regime-
//!   specific `Q_i`, `sigma_i`) are out of scope and NOT approximated.
//! - **Andrews (1993) sup-F** single-unknown-break test with Hansen (1997)
//!   approximate asymptotic p-values from his published response surfaces.
//!
//! ## Module map
//!
//! - [`bai_perron`] / [`BaiPerronConfig`] / [`BaiPerron`]: the full
//!   procedure — `n_breaks`, `break_dates`, `sup_f_seq`, the global
//!   `ssr_path` over `m`, per-regime [`RegimeFit`]s, and [`BreakCi`]s.
//! - [`sup_f_test`] / [`SupFTest`]: sup-F over the trimmed candidate range
//!   with the full Chow-style `f_path`.
//! - [`hansen_supf_pvalue`]: the response-surface p-value on its own.
//! - [`bai_argmax_cdf`] / [`bai_argmax_two_sided_crit`]: the Bai (1997)
//!   argmax distribution used by the intervals.
//! - `tables` (internal): the transcribed published tables, with sources
//!   and layout documented in the module.
//!
//! ## Validation
//!
//! Golden fixtures (`fixtures/tsecon-breaks.json`, generated by
//! `fixtures/generate_tsecon-breaks_fixtures.py` with numpy/scipy only):
//! the dynamic program is pinned to EXACT brute-force enumeration of all
//! admissible partitions (same minimal SSR to 1e-8 relative, same break
//! dates) on small-T cases up to `m = 3`; the full `bai_perron` output —
//! `ssr_path`, dates for every `m`, `supF(l+1|l)`, selection, per-regime
//! coefficients/standard errors (1e-8), and CIs (exact integers) — is
//! pinned on a two-break and a no-break DGP; `sup_f_test` statistics,
//! paths, and Hansen p-values are pinned to 1e-8 (p-values 1e-10); the
//! argmax cdf and its 90%/95% inversions are pinned to 1e-10/1e-8 after
//! the generator verifies the published anchors `P(|xi|<=7.7)~0.90`,
//! `P(|xi|<=11.03)~0.95`. Seeded Monte-Carlo property tests additionally
//! establish: DP == an independent per-segment-OLS brute force on random
//! DGPs; a two-break DGP is recovered with dates within ±2 periods; the
//! sequential procedure keeps its ~5% false-break rate on no-break data;
//! and the sup-F equals the maximum of an independently computed Chow
//! path.
//!
//! ```
//! use tsecon_breaks::{bai_perron, sup_f_test, BaiPerronConfig};
//!
//! // A mean-shift series: regime 1 near 0, regime 2 near 4.
//! let y: Vec<f64> = (0..80)
//!     .map(|t| if t < 40 { 0.0 } else { 4.0 } + 0.1 * ((t * 37 % 11) as f64 - 5.0))
//!     .collect();
//! let x = vec![vec![1.0; 80]];
//!
//! let bp = bai_perron(&y, &x, BaiPerronConfig { max_breaks: 3, trim: 0.15 }).unwrap();
//! assert_eq!(bp.n_breaks, 1);
//! assert_eq!(bp.break_dates, vec![39]);
//!
//! let sf = sup_f_test(&y, &x, 0.15).unwrap();
//! assert!(sf.stat > 0.0 && sf.p_value < 0.05);
//! ```

#![warn(missing_docs)]
#![warn(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod bai;
mod cdf;
mod check;
mod dp;
mod error;
mod segments;
mod supf;
mod tables;

pub use bai::{bai_perron, BaiPerron, BaiPerronConfig, BreakCi, RegimeFit};
pub use cdf::{bai_argmax_cdf, bai_argmax_two_sided_crit};
pub use error::BreaksError;
pub use supf::{hansen_supf_pvalue, sup_f_test, SupFTest};
