//! Fixed-interval state smoothing: the Durbin-Koopman backward recursion
//! in its univariate form, including the exact-diffuse variant through the
//! diffuse period.
//!
//! # Standard univariate smoother
//!
//! After a forward pass of the univariate filter, the backward recursion
//! (Durbin & Koopman 2012, §6.4.4; Koopman & Durbin 2000) runs over
//! elements `i = p..1` within each period and then across periods:
//!
//! ```text
//! L_{t,i} = I - K_{t,i} Z_i,        K_{t,i} = M_{t,i} / F_{t,i}
//! r_{t,i-1} = Z_i' v_{t,i} / F_{t,i} + L_{t,i}' r_{t,i}
//! N_{t,i-1} = Z_i' Z_i / F_{t,i} + L_{t,i}' N_{t,i} L_{t,i}
//! r_{t-1,p} = T' r_{t,0},           N_{t-1,p} = T' N_{t,0} T
//! ```
//!
//! starting from `r_{n,0} = 0`, `N_{n,0} = 0`, with smoothed moments
//!
//! ```text
//! alpha_hat_t = a_t + P_t r_{t,0}
//! V_t         = P_t - P_t N_{t,0} P_t
//! ```
//!
//! where `(a_t, P_t)` are the predicted moments. Missing or numerically
//! singular elements pass through unchanged (`L = I`, no `Z` term).
//!
//! # Exact-diffuse univariate smoother
//!
//! During the diffuse period (Koopman & Durbin 2003; Durbin & Koopman
//! 2012, §5.3) the recursion carries a second vector `r1` and matrices
//! `N1`, `N2` alongside `r0`, `N0`. For an element with `F_inf > 0`, with
//! `K0 = M_inf / F_inf`, `K1 = M_* / F_inf - M_inf F_* / F_inf^2`,
//! `L0 = I - K0 Z_i`, `L1 = -K1 Z_i`, `F1 = 1/F_inf`,
//! `F2 = -F_* / F_inf^2`:
//!
//! ```text
//! r1 <- Z_i' v F1 + L0' r1 + L1' r0
//! r0 <- L0' r0
//! N2 <- Z_i' Z_i F2 + L0' N2 L0 + L0' N1 L1 + L1' N1' L0 + L1' N0 L1
//! N1 <- Z_i' Z_i F1 + L0' N1 L0 + L1' N0 L0
//! N0 <- L0' N0 L0
//! ```
//!
//! an element with `F_inf = 0` takes the standard update for `(r0, N0)`
//! plus `N1 <- N1 L0`, and all five quantities transition across periods
//! by `T'` (and `T' . T` for the matrices). Smoothed moments during the
//! diffuse period:
//!
//! ```text
//! alpha_hat_t = a_t + P_t r0 + P_inf_t r1
//! V_t = P_t - P_t N0 P_t - P_inf_t N1 P_t - (P_inf_t N1 P_t)'
//!           - P_inf_t N2 P_inf_t
//! ```
//!
//! The `N1` recursion follows the convention of the statsmodels
//! implementation (which is consistent with the Durbin & Koopman book
//! rather than the Koopman-Durbin 2003 paper — the two differ in where a
//! cross term is booked); the fixtures this crate is validated against
//! are generated by statsmodels, and the smoothed moments agree.

use tsecon_linalg::faer::{Mat, MatRef};

use crate::dense::{axpy, mat_t_vec, mat_vec, outer_scaled, sandwich_t, symmetrize_in_place};
use crate::error::SsmError;
use crate::filter::{filter_univariate, FilterOutput, TOLERANCE_DIFFUSE};
use crate::model::LinearGaussianSSM;

/// Output of the univariate state smoother: smoothed moments plus the
/// forward filter output they were derived from.
#[derive(Debug, Clone)]
pub struct SmootherOutput {
    /// The forward univariate filter pass (log-likelihood, predicted and
    /// filtered moments, diffuse-period length).
    pub filter: FilterOutput,
    /// Smoothed state means `E[alpha_t | y_1..y_n]`, indexed `0..n`.
    pub smoothed_state: Vec<Vec<f64>>,
    /// Smoothed state covariances `Var[alpha_t | y_1..y_n]`, indexed
    /// `0..n`; exact through the diffuse period.
    pub smoothed_state_cov: Vec<Mat<f64>>,
}

/// `A' N B` for square factors of matching dimension.
fn quad(a: MatRef<'_, f64>, n: MatRef<'_, f64>, b: MatRef<'_, f64>) -> Mat<f64> {
    let an = a.transpose() * n;
    an.as_ref() * b
}

/// Runs the univariate Kalman filter forward and the Durbin-Koopman
/// univariate smoother backward (exact-diffuse variant through the
/// diffuse period); see the module docs for the recursions.
///
/// # Errors
///
/// Everything [`filter_univariate`] can return; the backward pass itself
/// is division-free given the filter's stored per-element quantities.
pub fn smooth_univariate(
    model: &LinearGaussianSSM,
    y: MatRef<'_, f64>,
) -> Result<SmootherOutput, SsmError> {
    let fo = filter_univariate(model, y)?;
    let n = fo.filtered_state.len();
    let p = model.obs_dim();
    let m = model.state_dim();

    let mut r0 = vec![0.0; m];
    let mut r1 = vec![0.0; m];
    let mut n0 = Mat::<f64>::zeros(m, m);
    let mut n1 = Mat::<f64>::zeros(m, m);
    let mut n2 = Mat::<f64>::zeros(m, m);

    let mut smoothed_state = vec![Vec::new(); n];
    let mut smoothed_state_cov = vec![Mat::<f64>::zeros(0, 0); n];

    for t in (0..n).rev() {
        let z = model.z().at(t);
        let diffuse_t = t < fo.d_diffuse;

        for i in (0..p).rev() {
            let step = &fo.steps[t * p + i];
            if !step.observed {
                continue; // L = I: everything passes through unchanged.
            }
            let zi: Vec<f64> = (0..m).map(|j| z[(i, j)]).collect();

            if step.f_inf > TOLERANCE_DIFFUSE {
                // Exact-diffuse element (only occurs while t < d_diffuse).
                let f1 = 1.0 / step.f_inf;
                let f2 = -step.f_star * f1 * f1;
                let k0: Vec<f64> = step.m_inf.iter().map(|x| x * f1).collect();
                let k1: Vec<f64> = step
                    .m_star
                    .iter()
                    .zip(&step.m_inf)
                    .map(|(ms, mi)| ms * f1 + mi * f2)
                    .collect();
                let l0 = Mat::from_fn(m, m, |r, c| {
                    let eye = if r == c { 1.0 } else { 0.0 };
                    eye - k0[r] * zi[c]
                });
                let l1 = Mat::from_fn(m, m, |r, c| -k1[r] * zi[c]);

                // r1 first (it consumes the old r0), then r0.
                let mut r1_new = mat_t_vec(l0.as_ref(), &r1);
                axpy(&mut r1_new, 1.0, &mat_t_vec(l1.as_ref(), &r0));
                axpy(&mut r1_new, step.v * f1, &zi);
                r1 = r1_new;
                r0 = mat_t_vec(l0.as_ref(), &r0);

                // All matrix updates read the pre-update N's; N0 last.
                let mut n2_new = outer_scaled(&zi, &zi, f2);
                n2_new += &quad(l0.as_ref(), n2.as_ref(), l0.as_ref());
                n2_new += &quad(l0.as_ref(), n1.as_ref(), l1.as_ref());
                n2_new += &quad(l1.as_ref(), n1.as_ref().transpose(), l0.as_ref());
                n2_new += &quad(l1.as_ref(), n0.as_ref(), l1.as_ref());
                let mut n1_new = outer_scaled(&zi, &zi, f1);
                n1_new += &quad(l0.as_ref(), n1.as_ref(), l0.as_ref());
                n1_new += &quad(l1.as_ref(), n0.as_ref(), l0.as_ref());
                let n0_new = quad(l0.as_ref(), n0.as_ref(), l0.as_ref());
                n2 = n2_new;
                n1 = n1_new;
                n0 = n0_new;
            } else {
                // Standard element (f_star > 0 is guaranteed by `observed`).
                let f_inv = 1.0 / step.f_star;
                let k0: Vec<f64> = step.m_star.iter().map(|x| x * f_inv).collect();
                let l0 = Mat::from_fn(m, m, |r, c| {
                    let eye = if r == c { 1.0 } else { 0.0 };
                    eye - k0[r] * zi[c]
                });
                let mut r0_new = mat_t_vec(l0.as_ref(), &r0);
                axpy(&mut r0_new, step.v * f_inv, &zi);
                r0 = r0_new;
                let mut n0_new = outer_scaled(&zi, &zi, f_inv);
                n0_new += &quad(l0.as_ref(), n0.as_ref(), l0.as_ref());
                n0 = n0_new;
                if diffuse_t {
                    // Diffuse-period bookkeeping for a non-diffuse element.
                    n1 = n1.as_ref() * l0.as_ref();
                }
            }
        }

        // Smoothed moments from the predicted moments and (r_{t,0}, N_{t,0}).
        let a_pred = &fo.predicted_state[t];
        let p_pred = &fo.predicted_state_cov[t];
        let mut alpha = a_pred.clone();
        axpy(&mut alpha, 1.0, &mat_vec(p_pred.as_ref(), &r0));
        let pn0 = p_pred.as_ref() * n0.as_ref();
        let pn0p = pn0.as_ref() * p_pred.as_ref();
        let mut v_t = p_pred.clone();
        v_t -= &pn0p;
        if diffuse_t {
            let p_inf = &fo.predicted_diffuse_state_cov[t];
            axpy(&mut alpha, 1.0, &mat_vec(p_inf.as_ref(), &r1));
            let pinf_n1 = p_inf.as_ref() * n1.as_ref();
            let pinf_n1_p = pinf_n1.as_ref() * p_pred.as_ref();
            v_t -= &pinf_n1_p;
            v_t -= &pinf_n1_p.as_ref().transpose().to_owned();
            let pinf_n2 = p_inf.as_ref() * n2.as_ref();
            let pinf_n2_pinf = pinf_n2.as_ref() * p_inf.as_ref();
            v_t -= &pinf_n2_pinf;
        }
        symmetrize_in_place(&mut v_t);
        smoothed_state[t] = alpha;
        smoothed_state_cov[t] = v_t;

        // Period transition r <- T' r, N <- T' N T (applied uniformly;
        // the diffuse quantities are zero outside the diffuse period).
        if t > 0 {
            let tr = model.t().at(t);
            r0 = mat_t_vec(tr, &r0);
            r1 = mat_t_vec(tr, &r1);
            n0 = sandwich_t(tr, n0.as_ref());
            n1 = sandwich_t(tr, n1.as_ref());
            n2 = sandwich_t(tr, n2.as_ref());
        }
    }

    Ok(SmootherOutput {
        filter: fo,
        smoothed_state,
        smoothed_state_cov,
    })
}

impl LinearGaussianSSM {
    /// Kalman filter plus Durbin-Koopman univariate state smoother
    /// (exact-diffuse variant through the diffuse period); see
    /// [`smooth_univariate`].
    pub fn smooth(&self, y: MatRef<'_, f64>) -> Result<SmootherOutput, SsmError> {
        smooth_univariate(self, y)
    }
}
