//! Golden-value tests for the EVT estimators against
//! `fixtures/tsecon-evt.json` (generated by
//! `fixtures/generate_tsecon-evt_fixtures.py` with scipy 1.17.1).
//!
//! Tolerances per the generator header:
//!
//! * threshold at 1e-12 relative (numpy `method="linear"` quantile,
//!   reimplemented bit-compatibly); `n_exceed` / `n_maxima` exact;
//! * fitted `(xi, beta)` / `(xi, mu, sigma)` at 1e-6 (absolute +
//!   relative) against the polished scipy optimum — two independent
//!   optimizers meeting at the same maximum;
//! * our log-likelihood at *our* optimum against scipy's summed `logpdf`
//!   at *its* optimum at 1e-10 absolute (the honest optimizer
//!   comparison: near a shared maximum the likelihood difference is
//!   second-order in the 1e-6 parameter gap), plus a one-sided check
//!   that our optimum is never worse;
//! * observed-information SEs at 1e-4 relative (both sides use the same
//!   central-4 stencil with unit-safe steps, so they converge to the
//!   same observed information);
//! * VaR/ES and return levels at 1e-5 relative — the 1e-6 parameter pin
//!   propagated through the tail formulas (the `p = 0.999` VaR has
//!   O(10) sensitivity to `xi`).

use serde_json::Value;
use tsecon_evt::{gev_fit, gpd_fit};

fn fixture() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/tsecon-evt.json"
    );
    let text = std::fs::read_to_string(path).expect("fixture file readable");
    serde_json::from_str(&text).expect("fixture is valid JSON")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_f64().expect("number"))
        .collect()
}

/// Combined absolute+relative comparison (numpy `allclose` semantics).
fn assert_close(actual: f64, expected: f64, atol: f64, rtol: f64, ctx: &str) {
    let tol = atol + rtol * expected.abs();
    assert!(
        (actual - expected).abs() <= tol,
        "{ctx}: actual {actual}, expected {expected}, |diff| {:e} > {tol:e}",
        (actual - expected).abs()
    );
}

#[test]
fn gpd_matches_polished_scipy() {
    let fx = fixture();
    for case in fx["gpd"].as_array().expect("gpd cases") {
        let name = case["name"].as_str().expect("name");
        let y = f64s(&case["y"]);
        let p_tail = f64s(&case["p_tail"]);
        let fit = match case["threshold_arg"].as_f64() {
            Some(u) => gpd_fit(&y, Some(u), 0.90, &p_tail),
            None => gpd_fit(
                &y,
                None,
                case["quantile_arg"].as_f64().expect("quantile"),
                &p_tail,
            ),
        }
        .expect("gpd_fit succeeds on fixture data");

        // Threshold selection and bookkeeping.
        let u_ref = case["threshold"].as_f64().expect("threshold");
        assert_close(
            fit.threshold,
            u_ref,
            0.0,
            1e-12,
            &format!("{name}: threshold"),
        );
        assert_eq!(
            fit.n_exceed,
            case["n_exceed"].as_u64().expect("n_exceed") as usize,
            "{name}: n_exceed"
        );
        assert_close(
            fit.exceed_rate,
            case["exceed_rate"].as_f64().expect("rate"),
            0.0,
            1e-14,
            &format!("{name}: exceed_rate"),
        );
        assert_close(
            fit.threshold_quantile,
            case["threshold_quantile"].as_f64().expect("q"),
            0.0,
            1e-14,
            &format!("{name}: threshold_quantile"),
        );

        // Parameters: two optimizers, same maximum.
        let xi_ref = case["xi"].as_f64().expect("xi");
        let beta_ref = case["beta"].as_f64().expect("beta");
        assert_close(fit.xi, xi_ref, 1e-6, 1e-6, &format!("{name}: xi"));
        assert_close(fit.beta, beta_ref, 1e-6, 1e-6, &format!("{name}: beta"));

        // The honest optimizer comparison: our loglik at our params vs
        // scipy's summed logpdf at its params.
        let ll_ref = case["loglik"].as_f64().expect("loglik");
        assert!(
            fit.loglik >= ll_ref - 1e-10,
            "{name}: our optimum is worse: {} < {ll_ref}",
            fit.loglik
        );
        assert_close(fit.loglik, ll_ref, 1e-10, 0.0, &format!("{name}: loglik"));
        assert!(fit.converged, "{name}: fit did not converge");

        // Observed-information standard errors.
        assert!(fit.se_valid, "{name}: SEs should be certified here");
        assert_close(
            fit.se_xi,
            case["se_xi"].as_f64().expect("se_xi"),
            0.0,
            1e-4,
            &format!("{name}: se_xi"),
        );
        assert_close(
            fit.se_beta,
            case["se_beta"].as_f64().expect("se_beta"),
            0.0,
            1e-4,
            &format!("{name}: se_beta"),
        );

        // McNeil-Frey tail VaR/ES.
        let var_ref = f64s(&case["var"]);
        let es_ref = f64s(&case["es"]);
        for (i, (&v, &e)) in var_ref.iter().zip(&es_ref).enumerate() {
            assert_close(
                fit.var[i],
                v,
                0.0,
                1e-5,
                &format!("{name}: var[{i}] (p={})", p_tail[i]),
            );
            assert_close(
                fit.es[i],
                e,
                0.0,
                1e-5,
                &format!("{name}: es[{i}] (p={})", p_tail[i]),
            );
        }
    }
}

#[test]
fn gev_matches_polished_scipy() {
    let fx = fixture();
    for case in fx["gev"].as_array().expect("gev cases") {
        let name = case["name"].as_str().expect("name");
        let y = f64s(&case["y"]);
        let block_size = case["block_size"].as_u64().map(|b| b as usize);
        let periods = f64s(&case["return_periods"]);
        let fit = gev_fit(&y, block_size, &periods).expect("gev_fit succeeds on fixture data");

        assert_eq!(
            fit.n_maxima,
            case["n_maxima"].as_u64().expect("n_maxima") as usize,
            "{name}: n_maxima"
        );

        let xi_ref = case["xi"].as_f64().expect("xi");
        let mu_ref = case["mu"].as_f64().expect("mu");
        let sigma_ref = case["sigma"].as_f64().expect("sigma");
        assert_close(fit.xi, xi_ref, 1e-6, 1e-6, &format!("{name}: xi"));
        assert_close(fit.mu, mu_ref, 1e-6, 1e-6, &format!("{name}: mu"));
        assert_close(fit.sigma, sigma_ref, 1e-6, 1e-6, &format!("{name}: sigma"));

        let ll_ref = case["loglik"].as_f64().expect("loglik");
        assert!(
            fit.loglik >= ll_ref - 1e-10,
            "{name}: our optimum is worse: {} < {ll_ref}",
            fit.loglik
        );
        assert_close(fit.loglik, ll_ref, 1e-10, 0.0, &format!("{name}: loglik"));
        assert!(fit.converged, "{name}: fit did not converge");

        assert!(fit.se_valid, "{name}: SEs should be certified here");
        assert_close(
            fit.se_xi,
            case["se_xi"].as_f64().expect("se_xi"),
            0.0,
            1e-4,
            &format!("{name}: se_xi"),
        );
        assert_close(
            fit.se_mu,
            case["se_mu"].as_f64().expect("se_mu"),
            0.0,
            1e-4,
            &format!("{name}: se_mu"),
        );
        assert_close(
            fit.se_sigma,
            case["se_sigma"].as_f64().expect("se_sigma"),
            0.0,
            1e-4,
            &format!("{name}: se_sigma"),
        );

        let rl_ref = f64s(&case["return_levels"]);
        for (i, &r) in rl_ref.iter().enumerate() {
            assert_close(
                fit.return_levels[i],
                r,
                0.0,
                1e-5,
                &format!("{name}: return_level[{i}] (T={})", periods[i]),
            );
        }
    }
}
