"""End-to-end smoke tests: the Rust core called from Python.

Golden values come from fixtures/*.json (generated by NumPy/SciPy/statsmodels)
and from the live NumPy in this environment (Philox bit-compatibility).
"""
import json
from pathlib import Path

import numpy as np
import pytest
import tsecon

FIXTURES = Path(__file__).parents[3] / "fixtures"
DIAG = json.loads((FIXTURES / "diagnostics.json").read_text())
NILE = np.array(DIAG["nile"])


def test_version():
    assert tsecon.__version__ == "0.0.1"


def test_philox_bit_compatible_with_numpy():
    for seed in (0, 42, 20260716):
        ours = tsecon.philox_uniforms(seed, 1000)
        theirs = np.random.Generator(np.random.Philox(seed)).random(1000)
        assert ours.tobytes() == theirs.tobytes()  # bit-exact, not approx


def test_acf_matches_statsmodels_fixture():
    r = tsecon.acf(NILE, nlags=20, adjusted=False)
    np.testing.assert_allclose(r["acf"], DIAG["acf_20_unadjusted"], rtol=1e-12)
    r = tsecon.acf(NILE, nlags=20, adjusted=True)
    np.testing.assert_allclose(r["acf"], DIAG["acf_20_adjusted"], rtol=1e-12)


def test_pacf_matches_statsmodels_fixture():
    np.testing.assert_allclose(
        tsecon.pacf(NILE, nlags=20, method="yw"), DIAG["pacf_20_ywm"], rtol=1e-10
    )
    np.testing.assert_allclose(
        tsecon.pacf(NILE, nlags=20, method="ols"), DIAG["pacf_20_ols"], rtol=1e-8
    )


def test_ljung_box_matches_statsmodels_fixture():
    r = tsecon.ljung_box(NILE - NILE.mean(), nlags=10)
    fx = DIAG["ljung_box_lags_1_10"]
    np.testing.assert_allclose(r["lb_stat"], fx["lb_stat"], rtol=1e-10)
    np.testing.assert_allclose(r["lb_pvalue"], fx["lb_pvalue"], rtol=1e-10)
    np.testing.assert_allclose(r["bp_stat"], fx["bp_stat"], rtol=1e-10)


def test_jarque_bera_matches_statsmodels_fixture():
    r = tsecon.jarque_bera(np.diff(NILE))
    fx = DIAG["jarque_bera_on_diff"]
    assert r["statistic"] == pytest.approx(fx["stat"], rel=1e-10)
    assert r["p_value"] == pytest.approx(fx["pvalue"], rel=1e-10)


def test_arch_lm_matches_statsmodels_fixture():
    r = tsecon.arch_lm(NILE - NILE.mean(), nlags=4)
    fx = DIAG["arch_lm_4"]
    assert r["statistic"] == pytest.approx(fx["lm_stat"], rel=1e-10)
    assert r["p_value"] == pytest.approx(fx["lm_pvalue"], rel=1e-10)


def test_bootstrap_indices_deterministic_and_in_range():
    a = tsecon.bootstrap_indices(500, scheme="stationary", seed=7, p=0.1)
    b = tsecon.bootstrap_indices(500, scheme="stationary", seed=7, p=0.1)
    c = tsecon.bootstrap_indices(500, scheme="stationary", seed=8, p=0.1)
    assert (a == b).all() and not (a == c).all()
    assert len(a) == 500 and a.max() < 500
    m = tsecon.bootstrap_indices(500, scheme="moving", seed=7, block_length=25)
    assert len(m) == 500 and m.max() < 500
    with pytest.raises(ValueError, match="requires block_length"):
        tsecon.bootstrap_indices(500, scheme="moving", seed=7)


def test_optimal_block_length_on_nile():
    r = tsecon.optimal_block_length(NILE)
    assert 1.0 <= r["stationary"] <= 30.0
    assert 1.0 <= r["circular"] <= 30.0


def test_error_messages_teach():
    with pytest.raises(ValueError, match="yw"):
        tsecon.pacf(NILE, method="nope")


SSM = json.loads((FIXTURES / "ssm.json").read_text())


def test_local_level_matches_statsmodels_exact_diffuse():
    p = SSM["local_level_params"]
    fx = SSM["local_level_exact_diffuse"]
    r = tsecon.local_level_smooth(np.array(SSM["nile"]), p["sigma2_eps"], p["sigma2_eta"])
    assert r["loglik"] == pytest.approx(fx["loglike"], rel=1e-9)
    np.testing.assert_allclose(r["filtered_state"], fx["filtered_state"], rtol=1e-8)
    np.testing.assert_allclose(r["smoothed_state"], fx["smoothed_state"], rtol=1e-8)
    np.testing.assert_allclose(r["smoothed_state_var"], fx["smoothed_state_cov"], rtol=1e-8)


def test_local_level_with_missing_data():
    p = SSM["local_level_params"]
    fx = SSM["local_level_missing_20_40_exact_diffuse"]
    y = np.array(SSM["nile"])
    y[20:40] = np.nan
    r = tsecon.local_level_smooth(y, p["sigma2_eps"], p["sigma2_eta"])
    assert r["loglik"] == pytest.approx(fx["loglike"], rel=1e-9)
    np.testing.assert_allclose(r["smoothed_state"], fx["smoothed_state"], rtol=1e-8)


def test_ar_loglik_matches_sarimax():
    fx = SSM["ar2_sarimax"]
    c, a1, a2, s2 = fx["params_const_ar1_ar2_sigma2"]
    ll = tsecon.ar_loglik(np.array(fx["y"]), [a1, a2], s2, intercept=c)
    assert ll == pytest.approx(fx["loglike"], rel=1e-9)


UR = json.loads((FIXTURES / "unitroot.json").read_text())
HAC = json.loads((FIXTURES / "hac.json").read_text())


def test_adf_matches_statsmodels():
    for case in UR["adf"]:
        y = np.array(UR[case["series"]])
        r = tsecon.adf(y, regression=case["regression"],
                       autolag=case["autolag"].lower() if case["autolag"] not in (None, "t-stat") else case["autolag"],
                       maxlag=case["maxlag"])
        assert r["statistic"] == pytest.approx(case["stat"], rel=1e-8), case
        assert r["p_value"] == pytest.approx(case["pvalue"], rel=1e-6), case
        assert r["used_lag"] == case["usedlag"], case


def test_kpss_matches_statsmodels():
    for case in UR["kpss"]:
        y = np.array(UR[case["series"]])
        r = tsecon.kpss(y, regression=case["regression"], nlags=case["nlags"])
        assert r["statistic"] == pytest.approx(case["stat"], rel=1e-8), case
        assert r["lags"] == case["lags"], case


def test_check_stationarity_quadrants():
    rw = np.array(UR["rw"])
    rep = tsecon.check_stationarity(rw)
    assert rep["quadrant"] == "UnitRoot"
    assert rep["recommendation"] == "Difference"
    assert "unit root" in rep["interpretation"].lower()
    wn = np.random.default_rng(0).standard_normal(300)
    rep2 = tsecon.check_stationarity(wn)
    assert rep2["quadrant"] == "Stationary"
    assert rep2["recommendation"] == "Proceed"


def test_ols_hac_matches_statsmodels():
    reg = HAC["regression"]
    y = np.array(reg["y"])
    X = np.column_stack([np.ones(len(y)), reg["x1"], reg["x2"]])
    for case in reg["hac_cases"]:
        r = tsecon.ols(y, X, se_type="hac", maxlags=case["maxlags"],
                       use_correction=case["use_correction"])
        np.testing.assert_allclose(r["params"], reg["ols_params"], rtol=1e-10)
        np.testing.assert_allclose(r["bse"], case["bse"], rtol=1e-10)
        np.testing.assert_allclose(r["tvalues"], case["tvalues"], rtol=1e-10)
    rn = tsecon.ols(y, X, se_type="nonrobust")
    np.testing.assert_allclose(rn["bse"], reg["ols_bse_nonrobust"], rtol=1e-10)


def test_long_run_variance_matches_fixture():
    lrv_fx = HAC["lrv_nile_demeaned"]["bartlett"]
    for bw, val in lrv_fx.items():
        assert tsecon.long_run_variance(NILE, kernel="bartlett", bandwidth=float(bw)) == pytest.approx(val, rel=1e-10)
