"""End-to-end smoke tests: the Rust core called from Python.

Golden values come from fixtures/*.json (generated by NumPy/SciPy/statsmodels)
and from the live NumPy in this environment (Philox bit-compatibility).
"""
import json
from pathlib import Path

import numpy as np
import pytest
import tsecon

FIXTURES = Path(__file__).parents[3] / "fixtures"
DIAG = json.loads((FIXTURES / "diagnostics.json").read_text())
NILE = np.array(DIAG["nile"])


def test_version():
    assert tsecon.__version__ == "0.0.1"


def test_philox_bit_compatible_with_numpy():
    for seed in (0, 42, 20260716):
        ours = tsecon.philox_uniforms(seed, 1000)
        theirs = np.random.Generator(np.random.Philox(seed)).random(1000)
        assert ours.tobytes() == theirs.tobytes()  # bit-exact, not approx


def test_acf_matches_statsmodels_fixture():
    r = tsecon.acf(NILE, nlags=20, adjusted=False)
    np.testing.assert_allclose(r["acf"], DIAG["acf_20_unadjusted"], rtol=1e-12)
    r = tsecon.acf(NILE, nlags=20, adjusted=True)
    np.testing.assert_allclose(r["acf"], DIAG["acf_20_adjusted"], rtol=1e-12)


def test_pacf_matches_statsmodels_fixture():
    np.testing.assert_allclose(
        tsecon.pacf(NILE, nlags=20, method="yw"), DIAG["pacf_20_ywm"], rtol=1e-10
    )
    np.testing.assert_allclose(
        tsecon.pacf(NILE, nlags=20, method="ols"), DIAG["pacf_20_ols"], rtol=1e-8
    )


def test_ljung_box_matches_statsmodels_fixture():
    r = tsecon.ljung_box(NILE - NILE.mean(), nlags=10)
    fx = DIAG["ljung_box_lags_1_10"]
    np.testing.assert_allclose(r["lb_stat"], fx["lb_stat"], rtol=1e-10)
    np.testing.assert_allclose(r["lb_pvalue"], fx["lb_pvalue"], rtol=1e-10)
    np.testing.assert_allclose(r["bp_stat"], fx["bp_stat"], rtol=1e-10)


def test_jarque_bera_matches_statsmodels_fixture():
    r = tsecon.jarque_bera(np.diff(NILE))
    fx = DIAG["jarque_bera_on_diff"]
    assert r["statistic"] == pytest.approx(fx["stat"], rel=1e-10)
    assert r["p_value"] == pytest.approx(fx["pvalue"], rel=1e-10)


def test_arch_lm_matches_statsmodels_fixture():
    r = tsecon.arch_lm(NILE - NILE.mean(), nlags=4)
    fx = DIAG["arch_lm_4"]
    assert r["statistic"] == pytest.approx(fx["lm_stat"], rel=1e-10)
    assert r["p_value"] == pytest.approx(fx["lm_pvalue"], rel=1e-10)


def test_bootstrap_indices_deterministic_and_in_range():
    a = tsecon.bootstrap_indices(500, scheme="stationary", seed=7, p=0.1)
    b = tsecon.bootstrap_indices(500, scheme="stationary", seed=7, p=0.1)
    c = tsecon.bootstrap_indices(500, scheme="stationary", seed=8, p=0.1)
    assert (a == b).all() and not (a == c).all()
    assert len(a) == 500 and a.max() < 500
    m = tsecon.bootstrap_indices(500, scheme="moving", seed=7, block_length=25)
    assert len(m) == 500 and m.max() < 500
    with pytest.raises(ValueError, match="requires block_length"):
        tsecon.bootstrap_indices(500, scheme="moving", seed=7)


def test_optimal_block_length_on_nile():
    r = tsecon.optimal_block_length(NILE)
    assert 1.0 <= r["stationary"] <= 30.0
    assert 1.0 <= r["circular"] <= 30.0


def test_error_messages_teach():
    with pytest.raises(ValueError, match="yw"):
        tsecon.pacf(NILE, method="nope")


SSM = json.loads((FIXTURES / "ssm.json").read_text())


def test_local_level_matches_statsmodels_exact_diffuse():
    p = SSM["local_level_params"]
    fx = SSM["local_level_exact_diffuse"]
    r = tsecon.local_level_smooth(np.array(SSM["nile"]), p["sigma2_eps"], p["sigma2_eta"])
    assert r["loglik"] == pytest.approx(fx["loglike"], rel=1e-9)
    np.testing.assert_allclose(r["filtered_state"], fx["filtered_state"], rtol=1e-8)
    np.testing.assert_allclose(r["smoothed_state"], fx["smoothed_state"], rtol=1e-8)
    np.testing.assert_allclose(r["smoothed_state_var"], fx["smoothed_state_cov"], rtol=1e-8)


def test_local_level_with_missing_data():
    p = SSM["local_level_params"]
    fx = SSM["local_level_missing_20_40_exact_diffuse"]
    y = np.array(SSM["nile"])
    y[20:40] = np.nan
    r = tsecon.local_level_smooth(y, p["sigma2_eps"], p["sigma2_eta"])
    assert r["loglik"] == pytest.approx(fx["loglike"], rel=1e-9)
    np.testing.assert_allclose(r["smoothed_state"], fx["smoothed_state"], rtol=1e-8)


def test_ar_loglik_matches_sarimax():
    fx = SSM["ar2_sarimax"]
    c, a1, a2, s2 = fx["params_const_ar1_ar2_sigma2"]
    ll = tsecon.ar_loglik(np.array(fx["y"]), [a1, a2], s2, intercept=c)
    assert ll == pytest.approx(fx["loglike"], rel=1e-9)


UR = json.loads((FIXTURES / "unitroot.json").read_text())
HAC = json.loads((FIXTURES / "hac.json").read_text())


def test_adf_matches_statsmodels():
    for case in UR["adf"]:
        y = np.array(UR[case["series"]])
        r = tsecon.adf(y, regression=case["regression"],
                       autolag=case["autolag"].lower() if case["autolag"] not in (None, "t-stat") else case["autolag"],
                       maxlag=case["maxlag"])
        assert r["statistic"] == pytest.approx(case["stat"], rel=1e-8), case
        assert r["p_value"] == pytest.approx(case["pvalue"], rel=1e-6), case
        assert r["used_lag"] == case["usedlag"], case


def test_kpss_matches_statsmodels():
    for case in UR["kpss"]:
        y = np.array(UR[case["series"]])
        r = tsecon.kpss(y, regression=case["regression"], nlags=case["nlags"])
        assert r["statistic"] == pytest.approx(case["stat"], rel=1e-8), case
        assert r["lags"] == case["lags"], case


def test_check_stationarity_quadrants():
    rw = np.array(UR["rw"])
    rep = tsecon.check_stationarity(rw)
    assert rep["quadrant"] == "UnitRoot"
    assert rep["recommendation"] == "Difference"
    assert "unit root" in rep["interpretation"].lower()
    wn = np.random.default_rng(0).standard_normal(300)
    rep2 = tsecon.check_stationarity(wn)
    assert rep2["quadrant"] == "Stationary"
    assert rep2["recommendation"] == "Proceed"


def test_ols_hac_matches_statsmodels():
    reg = HAC["regression"]
    y = np.array(reg["y"])
    X = np.column_stack([np.ones(len(y)), reg["x1"], reg["x2"]])
    for case in reg["hac_cases"]:
        r = tsecon.ols(y, X, se_type="hac", maxlags=case["maxlags"],
                       use_correction=case["use_correction"])
        np.testing.assert_allclose(r["params"], reg["ols_params"], rtol=1e-10)
        np.testing.assert_allclose(r["bse"], case["bse"], rtol=1e-10)
        np.testing.assert_allclose(r["tvalues"], case["tvalues"], rtol=1e-10)
    rn = tsecon.ols(y, X, se_type="nonrobust")
    np.testing.assert_allclose(rn["bse"], reg["ols_bse_nonrobust"], rtol=1e-10)


def test_long_run_variance_matches_fixture():
    lrv_fx = HAC["lrv_nile_demeaned"]["bartlett"]
    for bw, val in lrv_fx.items():
        assert tsecon.long_run_variance(NILE, kernel="bartlett", bandwidth=float(bw)) == pytest.approx(val, rel=1e-10)


VARFX = json.loads((FIXTURES / "var.json").read_text())
FILTFX = json.loads((FIXTURES / "filters.json").read_text())
FCFX = json.loads((FIXTURES / "forecast.json").read_text())
MACRO = np.array(VARFX["data_100dlog_gdp_cons_inv"])
GDP = np.array(FILTFX["y_100_log_realgdp"])


def test_var_fit_matches_statsmodels():
    r = tsecon.var_fit(MACRO, lags=2, trend="c")
    fx = VARFX["var2c"]
    np.testing.assert_allclose(r["params"], fx["params"], rtol=1e-8)
    np.testing.assert_allclose(r["sigma_u"], fx["sigma_u"], rtol=1e-8)
    assert r["llf"] == pytest.approx(fx["llf"], rel=1e-10)
    assert r["aic"] == pytest.approx(fx["aic"], rel=1e-10)
    assert r["max_root"] == pytest.approx(fx["stable_max_root"], rel=1e-8)


def test_var_irf_fevd_match_statsmodels():
    irf = np.array(tsecon.var_irf(MACRO, lags=2, horizon=10, orth=True))
    np.testing.assert_allclose(irf, VARFX["irf_orth_h10"], atol=1e-10)
    fevd = np.array(tsecon.var_fevd(MACRO, lags=2, horizon=10))
    np.testing.assert_allclose(fevd, VARFX["fevd_h10"], atol=1e-10)
    assert np.allclose(fevd.sum(axis=2), 1.0)


def test_var_forecast_and_granger():
    fc = tsecon.var_forecast(MACRO, lags=2, steps=8)
    np.testing.assert_allclose(fc["point"], VARFX["forecast_8"]["point"], atol=1e-8)
    np.testing.assert_allclose(fc["lower"], VARFX["forecast_8"]["lower95"], atol=1e-8)
    g = tsecon.var_granger(MACRO, caused=[0], causing=[1], lags=2)
    fx = VARFX["granger_cons_causes_gdp"]
    assert g["statistic"] == pytest.approx(fx["stat"], rel=1e-8)
    assert g["p_value"] == pytest.approx(fx["pvalue"], rel=1e-6)


def test_filters_match_statsmodels():
    hp = tsecon.hp_filter(GDP, lamb=1600.0)
    np.testing.assert_allclose(hp["cycle"], FILTFX["hp_1600"]["cycle"], atol=1e-8)
    np.testing.assert_allclose(hp["trend"], FILTFX["hp_1600"]["trend"], atol=1e-8)
    bk = tsecon.bk_filter(GDP, low=6, high=32, k=12)
    np.testing.assert_allclose(bk["cycle"], FILTFX["bk_6_32_K12"], atol=1e-8)
    assert bk["first_index"] == 12
    cf = tsecon.cf_filter(GDP, low=6, high=32, drift=True)
    np.testing.assert_allclose(cf["cycle"], FILTFX["cf_6_32_drift"]["cycle"], atol=1e-8)
    ham = tsecon.hamilton_filter(GDP, h=8, p=4)
    np.testing.assert_allclose(ham["beta"], FILTFX["hamilton_h8_p4"]["beta"], rtol=1e-8)
    np.testing.assert_allclose(ham["cycle"], FILTFX["hamilton_h8_p4"]["cycle"], atol=1e-8)


def test_dm_and_theta_match_fixtures():
    fx = FCFX["dm_test"]
    r = tsecon.dm_test(np.array(fx["e1"]), np.array(fx["e2"]), h=fx["h"], loss="squared")
    assert r["dm_stat"] == pytest.approx(fx["dm_stat"], rel=1e-10)
    assert r["hln_stat"] == pytest.approx(fx["hln_stat"], rel=1e-10)
    assert r["p_value"] == pytest.approx(fx["hln_pvalue_t_nminus1"], rel=1e-9)
    realgdp = None
    # theta fixture used raw realgdp; reconstruct from filters fixture is log —
    # so validate theta on the fixture's own stored forecast via the crate's
    # golden test instead; here just sanity-check the binding.
    th = tsecon.theta_forecast(GDP, steps=8, period=4)
    assert len(th) == 8 and np.isfinite(th).all()


def test_accuracy_measures():
    fx = FCFX["accuracy_small"]
    a, f = np.array(fx["actual"]), np.array(fx["forecast"])
    ins = np.array(fx["insample_for_mase"])
    r = tsecon.accuracy(a, f, insample=ins, period=1)
    assert r["mae"] == pytest.approx(np.abs(a - f).mean(), rel=1e-12)
    denom = np.abs(np.diff(ins)).mean()
    assert r["mase"] == pytest.approx(np.abs(a - f).mean() / denom, rel=1e-12)


GARCHFX = json.loads((FIXTURES / "garch.json").read_text())
BVARFX = json.loads((FIXTURES / "bvar_niw.json").read_text())
CONVFX = json.loads((FIXTURES / "convergence.json").read_text())


def test_garch_fit_matches_arch_package():
    ret = np.array(GARCHFX["returns"])
    case = next(c for c in GARCHFX["cases"] if c["name"] == "garch11_zero_normal")
    r = tsecon.garch_fit(ret, vol="garch", mean="zero", dist="normal", forecast_horizon=10)
    assert r["loglik"] >= case["fit_loglike"] - 1e-6      # match or beat arch's optimum
    fx_params = [case["fit_params"][k] for k in r["param_names"]]
    np.testing.assert_allclose(r["params"], fx_params, rtol=1e-3)
    fx_rob = [case["fit_bse_robust"][k] for k in r["param_names"]]
    np.testing.assert_allclose(r["se_robust"], fx_rob, rtol=5e-3)
    v = r["variance_forecast"]
    assert len(v) == 10 and (v > 0).all()


def test_garch_gjr_asymmetry_detected():
    ret = np.array(GARCHFX["returns"])
    r = tsecon.garch_fit(ret, vol="gjr", mean="zero", dist="normal")
    assert "gamma[1]" in " ".join(r["param_names"]).lower() or len(r["params"]) == 4
    assert np.isfinite(r["loglik"])


def test_bvar_posterior_matches_analytic_fixture():
    data = np.array(BVARFX["data"])
    s = BVARFX["spec"]
    r = tsecon.bvar_fit(data, lags=s["p"], lambda0=s["lambda0"], lambda1=s["lambda1"],
                        lambda3=s["lambda3"], delta=0.0)
    np.testing.assert_allclose(r["posterior_mean_coefs"], BVARFX["posterior"]["b_bar"], rtol=1e-8)
    np.testing.assert_allclose(r["sigma_posterior_mean"],
                               BVARFX["posterior"]["sigma_posterior_mean"], rtol=1e-8)
    assert r["log_marginal_likelihood"] == pytest.approx(
        BVARFX["posterior"]["log_marginal_likelihood"], rel=1e-10)


def test_bvar_irf_draws_reproducible_and_shaped():
    data = np.array(BVARFX["data"])
    a = np.array(tsecon.bvar_irf_draws(data, lags=2, horizon=8, n_draws=50, seed=7))
    b = np.array(tsecon.bvar_irf_draws(data, lags=2, horizon=8, n_draws=50, seed=7))
    assert a.shape == (50, 9, 3, 3)
    np.testing.assert_array_equal(a, b)          # same seed, same posterior draws
    lo, hi = np.quantile(a, [0.05, 0.95], axis=0)
    assert (lo <= hi).all()


def test_mcmc_diagnostics_match_arviz():
    for name, tol in [("good", 1e-6), ("bad", 1e-6)]:
        chains = np.array(CONVFX[name]["chains"])
        r = tsecon.mcmc_diagnostics(chains)
        assert r["rhat"] == pytest.approx(CONVFX[name]["rhat_rank"], rel=tol)
        assert r["ess_bulk"] == pytest.approx(CONVFX[name]["ess_bulk"], rel=1e-3)
        assert r["ess_tail"] == pytest.approx(CONVFX[name]["ess_tail"], rel=1e-3)
    assert tsecon.mcmc_diagnostics(np.array(CONVFX["bad"]["chains"]))["rhat"] > 1.01


def test_arima_fit_beats_statsmodels_on_nile():
    fx = json.loads((FIXTURES / "arima.json").read_text())["nile_arma11c_fit"]
    r = tsecon.arima_fit(NILE, p=1, d=0, q=1, constant=True, forecast_steps=12)
    assert r["loglik"] >= fx["loglike"] - 1e-6      # match or beat (fixture was non-converged)
    assert len(r["forecast_mean"]) == 12
    assert (np.diff(r["forecast_se"]) >= -1e-10).all()   # widening uncertainty
    lb = tsecon.ljung_box(r["residuals"], nlags=10)
    assert lb["lb_pvalue"][-1] > 0.01                    # residuals ~ white noise


def test_arima_d1_random_walk_law():
    rw = np.cumsum(np.random.default_rng(3).standard_normal(400)) * 1.7
    r = tsecon.arima_fit(rw, p=0, d=1, q=0, constant=False, forecast_steps=9)
    sig = np.sqrt(np.exp(0) * np.var(np.diff(rw)))
    np.testing.assert_allclose(r["forecast_se"], r["forecast_se"][0] * np.sqrt(np.arange(1, 10)),
                               rtol=1e-8)  # se_h = sigma * sqrt(h)
